### ISSUE TITLE
Maybe a Silly question

### ISSUE THREAD

**Issue by stephenstroud** [IdentityServer/IdentityServer3.Samples#100]
I normally create an authentication Web API on VS 2013 with the Web API template using "Individual User Accounts" selection, however, now moved over to VNext and not found any VNext Auth Web API samples. (Not the MVC template)

Silly question: What is the difference between Identity Server and ASP.Net Identity, I could create a web api service using Identity to achieve the identity server solution?
Any samples for VNext?

**Comment by brockallen** [comment]
ASP.NET Identity is an identity management library. IdentityServer3 is a token service.
