### ISSUE TITLE
Isn't it better to set the frame.src property after adding the eventlistener to listen for messages?

### ISSUE THREAD

**Issue by devlz303** [IdentityServer/IdentityServer3.Samples#101]
In the previous (jQuery)version of oidc.js the src property of the frame that is created to silently load the token in the background is set after the eventlistener that listens for the message from the iframe has been set.
In the latest code the frame is created, and the src property is set before add the listener.

This could be a problem if the token retrieval is very fast and the message from the IFrame is sent before the eventlistener is active.

**Comment by brockallen** [comment]
Possibly -- feel free to submit a PR (and sign the CLA, too please).

**Comment by devlz303** [comment]
Okay, I have never made a pull request so I have to figure out how to do this. :-)
And where can I sign the CLA?

**Comment by devlz303** [comment]
I have made a pull request for this issue, but I still don't know where and how to sign the CLA.

**Comment by leastprivilege** [comment]
:) no worries.

* clone the repo
* create a new branch
* do just the one thing you want to fix on that branch
* use that branch for the PR

**Comment by devlz303** [comment]
As a newbie to Github I'm already stuck on the "clone the repo" step.
The "Clone in Desktop" button only opens the Github for Windows app.

I will take a look at this later, because I have some work to do right now.
