### ISSUE TITLE
login page errro/unavailable

### ISSUE THREAD

**Issue by pjirsa** [IdentityServer/IdentityServer3.Samples#105]
I am trying to get the MVC Authentication sample working. I can get to the .well-known url and see the config. However, when I click Login or About it tells me that the /identity/login page is unavailable. Did I miss a step somewhere? Thanks

**Comment by leastprivilege** [comment]
Hard to say if you missed a step ;)

you can always check with the full sample "solution".

**Comment by pjirsa** [comment]
Thanks. I did try the full solution and it had the same result. I am running this on a windows 10 preview machine. everything seems to work fine on my win 8.1 build. i'll chalk it up to the "preview". thanks.
