### ISSUE TITLE
AspNetIdentity sample missing the IdentityManager 

### ISSUE THREAD

**Issue by dzolnjan** [IdentityServer/IdentityServer3.Samples#108]
NuGet Package restore failed for project UserService-AspNetIdentity: Unable to find version '1.0.0-pre-10032' of package 'IdentityManager'

Anyone else having this issues when building/restoring lastest AspNetIdentity sample? 

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity

**Comment by brockallen** [comment]
You'll have to grab the samples from dev -- they're updated with the right feed. Alternatively, you can remove the reference and add the reference from NuGet.

**Comment by dzolnjan** [comment]
Yes, nuget worked without specifying version >> Install-Package IdentityManager -Pre

It adds >> <package id="IdentityManager" version="1.0.0-beta4" targetFramework="net45" />

**Comment by brockallen** [comment]
Ok, thanks - we're in the middle of moving over to a different myget feed, so the old one have gone stale. Sorry.

**Comment by JoshKewleyEdoc** [comment]
FWIW, master appears to still have the issue as of today. Dev seems fine. Perhaps readme.md should suggest using dev until master is fixed.
