### ISSUE TITLE
IdentityServerServiceFactory present on EF sample is different from IdentityServer Core?

### ISSUE THREAD

**Issue by felippeDev** [IdentityServer/IdentityServer3.Samples#110]
Hi folks,

I´m so confused.. I building a toy robust example with an IdentityServer.Core class Library project and one web app where i should use to build my own UI to CRUD users, scopes and clients.

However, when i try to implement factory.RegisterConfigurationServices like EF sample i face a lot number of errors due this missing method. Maybe @brockallen used some custom implementation for sample purposes inside IndentityServer.dll like RegisterConfigurationServices and RegisterOperationalServices factory methods?!

Could you please help me with the implementation of these methods? i can see the properties, but i dont know what they should do..

![capture](https://cloud.githubusercontent.com/assets/1347061/6907677/a1a433ce-d70e-11e4-829a-2dc79ac62af8.JPG)

Or should i delete my Class Library with pure IdentityServer3 and use IdentityServer3.dll from this sample? (This is sad.. but solves..)

Tks,
^LF.

**Comment by brockallen** [comment]
Hmm, perhaps we have a bug in the NuGet dependencies -- can you update the EF nuget to the latest?

**Comment by felippeDev** [comment]
I´ve just updated all nugget content in the projects and doesnt work.. =*(

However, i remove my reference to pure Idsrv project and copy IdentityServer3.dll from EF example. 

This action resolve the problem for now.. But if i will customize views of Login page (for example) or something from Idsrv i think i will need customize Pure Idsrv3 proj and use this references on web UI proj and the issue will show up again..

I will use a couple of days to test Idsrv + EF + ADFS + WAAD + APIs until customize some entities and... ufff i have too much work ahead studying all of this ;) so.. when i face this issue again i will investigate better and re-open this thread.

Thx Brock! :+1: 
^LF.

**Comment by brockallen** [comment]
Ok, thanks -- keep us posted.
