### ISSUE TITLE
Using multiple tabs causes errors with silent token renewal

### ISSUE THREAD

**Issue by devlz303** [IdentityServer/IdentityServer3.Samples#111]
Today I ran into a strange problem in my application when I was debugging the silent renewal of the token. For my test I have set the accesstoken lifetime to 70 seconds so it would be refresh about every 10 seconds.
For some reason I was getting the following javascript errors in the console:
'No request state loaded' and 'Invalid state'. This problem is caused when the application is opened in more than one tab. In both tabs the code is running to retrieve a new access token. Because the token retrieval code uses localstorage to store the requestDataKey and also to remove this data after the new token is retrieved, this leads to problems because this data is shared between the tabs.

Maybe this problem can be solved using the localstorage event to communicate between tabs, when the localstorage changes and make sure only one of the tabs is used to refresh the token?

**Comment by brockallen** [comment]
Same issue as this, perhaps? https://github.com/IdentityServer/IdentityServer3/issues/1105

**Comment by devlz303** [comment]
It look likes the same issue. In the meantime I think I have found a solution.
Each tab has it's own TokenManager and is renewing the tokens on their own. But once a token is received, the token is saved in localstorage and at this moment the "storage" event is fired and all listening tabs will load the token. At this time the token refresh interval is automatically synchronized between the tabs, so the silent renew of each tab is going to happen almost at the same time.

Right now I have changed the readResponseAsync function of the OidcClient and make sure the 
requestData is only removed from localstorage if the result.state is the same as the state in the data stored in localstorage.

Now, when the first response comes in and the result.state doesn't match the data.state it will cause an "Invalid state" error. But when the response with the valid state arrives, the data still exists in localstorage and the token can be stored.

So the change I made is as follows:

 if (result.state !== data.state) {
            return error("Invalid state");
 }
settings.store.removeItem(requestDataKey);

instead of

var data = settings.store.getItem(requestDataKey);
settings.store.removeItem(requestDataKey);

Ofcourse it would be nicer if there was only one TokenManager in charge of renewing the tokens, but I think that is a bit harder to do.

**Comment by brockallen** [comment]
Ah, not a bad change -- I'll consider adding into the library.

**Comment by brockallen** [comment]
Also, you can always change the storage being used to session storage.

**Comment by devlz303** [comment]
Yes, I think this little change will solve the problem but I still think it's not nice to send a token request in each tab when they all end up having one shared token.
And because I have to support IE9 at this moment I don't think I can use sessionStorage.

Which brings me to another problem I "solved" regarding IE9. My STS is on a different domain and using IE9 you can't use the XmlHttpRequest object to make an crossdomain request. So I made a change to use the XDomainRequest object in this case. But that's another problem, so I will open a new issue for that one.

**Comment by brockallen** [comment]
Well, I'd suggest not doing it on each tab and coordinate so only one does the automatic token renewal.

**Comment by devlz303** [comment]
Yeah, I think that is the best way to do it. Right now the token renewal is done 60 seconds before the token lifetime ends. I was thinking about a solution where one tokenmanager is "in charge" to renew tokens. But the problem is, who is "the one"? And what happend if "the one" is not available anymore (because the tab is closed or some other cause).

**Comment by brockallen** [comment]
Sure -- you can disable the silent review all but one.

**Comment by devlz303** [comment]
Sure, but this has to be "dynamicly updateable", it's exactly the same application running in different tabs. I can open a new tab and navigate to my application and when the application starts it has to determine if there is already another application running that is renewing the tokens. And if so, when that instantie of the application stops the one (or another) has to take over this renewal task.

**Comment by brockallen** [comment]
FYI all future oidc.js issues should be directed here:

https://github.com/IdentityModel/oidc-client

or here:

https://github.com/IdentityModel/oidc-token-manager

I'll close this for now and if you still have problems, open a new issue in the correct repo. Thx.
