### ISSUE TITLE
 Using the oidc.js library with a crossdomain STS doesn't work in IE9

### ISSUE THREAD

**Issue by devlz303** [IdentityServer/IdentityServer3.Samples#112]
Our STS is on a different domain than the client and when I use IE9 I am not able to request a token. The call will result in an Acces Denied error. This is because in IE9 crossdomain requests can't be made using the XmlHttpRequest object. You have to use the (not so good :)) XDomainRequest object.
Although the XDomainRequest object isn't as good as the XmlHttpRequest object I have made a change in the oidc.js library we are using so it is possible to sign in using IE9.

I will show you the code change I have made in our copy of the oidc.js (or make a pull request) so you can review the change. Right now I'm not at work, so I will show the changes later.

**Comment by brockallen** [comment]
So I'm a bit behind on this issue -- what's the status and are you asking us to do anything?

**Comment by brockallen** [comment]
Also, FYI all future oidc.js issues should be directed here: 

https://github.com/IdentityModel/oidc-client

or here:

https://github.com/IdentityModel/oidc-token-manager

**Comment by brockallen** [comment]
I'll close this for now and you can open a new issue in the correct repo.
