### ISSUE TITLE
AspNetIdentity sample won't compile

### ISSUE THREAD

**Issue by omidkrad** [IdentityServer/IdentityServer3.Samples#114]
I installed the `Thinktecture.IdentityServer3` and `Thinktecture.IdentityManager` nuget packages which fixed some of the build errors but still there are more. Can't find a reference to `AspNetIdentityManagerService` class.

**Comment by brockallen** [comment]
On master or dev?

**Comment by omidkrad** [comment]
In master. I made a PL with the fixes #115

**Comment by brockallen** [comment]
Thanks.

**Comment by brockallen** [comment]
I think this was fixed when we merged from dev to master.
