### ISSUE TITLE
OAuthJS - callback redirect allways to the same page /index.html

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3.Samples#117]
Do you support or plan to support differet redirect page? Maybe it's a good idea to store address in session/local storage and redirect back after obtaining token ?

**Comment by brockallen** [comment]
I don't follow. It's a sample and the callback is configurable.

**Comment by pawepaw** [comment]
Sure i know. But i'm thinking about mechanism that callback will always redirect to source page (page from which redirect occured)

**Comment by brockallen** [comment]
The OAuthJS sample is really a place to showcase the token manager library and the different ways it can provide callbacks.

**Comment by pawepaw** [comment]
Sure i understand this. But according to this demo I'm asking if there is any mechanism i can use to redirect user back to page from which he was redirected? Or i have to write my own mechanism. Because I understand that this address isn't stored anywhere and isn't returned from openId server.

**Comment by brockallen** [comment]
Just configure the token manager settings to use the current page, and then you'd have to ensure that URL is also configured as a legal redirect URL in the client config in IdSvr.

**Comment by pawepaw** [comment]
Sure i get it. But then I'd have to implement some custom logic depended on QueryString like you did in  https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/JavaScriptImplicitClient/index.html

```javascript
 if (window.location.hash) {
            handleCallback();
        }
```

I thought that i'd be better to have callback as separate webpage, like in this demo https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/OAuthJS/JsImplicitOAuthLibraryDemo .

**Comment by brockallen** [comment]
Yes, in general it might make the most sense to put callback logic into a dedicated page (especially since that's where the token handling will be).

**Comment by pawepaw** [comment]
That's summary of my question. Then I have to write mechanism to store initial address somewhere (local or session storage perhaps) before redirecting and after processing callback redirect back.

**Comment by brockallen** [comment]
Ok, then that's why I've not been very helpful on this thread -- because I'm still confused. What address? You code the client to know which callback page you are using, that URL is then used in the config in the client app for the redirect, and then you also need configure that URL in IdSvr. What am I missing?

**Comment by pawepaw** [comment]
Ok i'll try to clarify.

You have application with implicit flow.

1. navigatge to page example.com/restricted.html which requires authentication. 
2. redirect to server for log in
3. end user fill login form
4. end user is redirected to example.com/callback.html page, query string is parsed and token goes to store. 
5. ?

Problem is that User remains on callback page. I have to redirect him back to example.com/restricted.html (page which he wanted to open) this address isn't stored anywhere. 

I understand that i can treat example.com/restricted.html as callback page but i don't want it. I'd prefer separate callback page.

My possible solution:

1. navigatge to page example.com/restricted.html which requires authentication. 
2. store current url (example.com/restricted.html) in sessionStorage
2. redirect to server for log in
3. end user fill login form
4. end user is redirected to example.com/callback.html page, query string is parsed and token goes to store. 
5. read url from sessionStorage and redirect to (example.com/restricted.html)

**Comment by brockallen** [comment]
Oh I see now -- you need to remember the original URL the user requested. So yes -- that's normally done with some state management within your client app -- like you suggested: local storage, cookie, something.

**Comment by pawepaw** [comment]
ok ;) thanks finally.

**Comment by RPM1984** [comment]
@brockallen is this still the case? Can't we pass an additional querystring param to the authorise endpoint (signifying the original url), which IdSrv can then echo back in the redirect uri along with the token? Using cookies/locskstorage etc to remember a url seems hacky..

**Comment by brockallen** [comment]
Because you don't want open redirect attacks.
