### ISSUE TITLE
Directory structure in Samples repository

### ISSUE THREAD

**Issue by pawepaw** [IdentityServer/IdentityServer3.Samples#118]
I've got a little bit confused about directory structure in this repository. There is directory called "Clients"  where you placed sample clients, but as i understand you have some clients also in root directory (source), like OAuthJS.

What's the difference?

**Comment by brockallen** [comment]
None really -- OAuthJS will go away now that the oidc-client and oidc-token-manager repos are now finally active.

**Comment by pawepaw** [comment]
Where can I find it?

**Comment by brockallen** [comment]
https://github.com/IdentityModel/
