### ISSUE TITLE
User authentication against database 

### ISSUE THREAD

**Issue by mkjv** [IdentityServer/IdentityServer3.Samples#119]
I'm new to Thinktecture Identity Server, and i'm struggling to find any sample code or simple description on authenticating a user against a database. All the code samples i came across are based on the "InMemoryUser" which is great to quickly understand how it all works. But now I need to see how it works with a database. Is there anywhere a simple code sample using a database that someone could point me to? Also, does Identity Server require Entity Framework to use a database? I would prefer non Entity Framework sample if that is supported. Thanks.

**Comment by leastprivilege** [comment]
Look at the IUserService interface, the user service documentation and then ASP.NET Identity and MembershipReboot integration repos.

**Comment by mkjv** [comment]
Thanks so much. IUserService interface is exactly what i was looking for, and somehow missed. i just implemented it and it works! Thanks again!
