### ISSUE TITLE
Example of AuthorizeAttribute in ASP.NET 5

### ISSUE THREAD

**Issue by fekberg** [IdentityServer/IdentityServer3.Samples#122]
The ASP.NET 5 example does not include information on how to validate the bearer token using `[Authorize]` and the previous methods does not seem to be supported.

It would be very helpful to get some details on how this would work in ASP.NET 5.

My assumptions were (but failed to work):

1. Use `Microsoft.AspNet.Authentication.OAuthBearer`
2. Add `UseOAuthBearerAuthentication` like this:

```
app.Map("/api", api => {
    api.UseOAuthBearerAuthentication(options => {
        options.Authority = "http://localhost:5000";
    });
    api.UseMvc();
});
```

The above assumes the identity service at the following url: `http://localhost:5000/identity`.

Any insight would be much appreciated!

**Comment by fekberg** [comment]
I think the issue I was facing was the order of app.Map.

**Comment by leastprivilege** [comment]
Well - the above can't work - you are not validating the audience.

**Comment by fekberg** [comment]
Indeed you are right, this is the complete configuration that worked:

```
app.UseOAuthBearerAuthentication(options =>
{
    options.Authority = "http://localhost:19686/oauth/";
    options.Audience = "http://localhost:19686/oauth/resources";

    options.TokenValidationParameters = new TokenValidationParameters
    {
        IssuerSigningKeys = new[] { new X509SecurityKey(cert) },
        ValidateLifetime = false,
    };
    options.AutomaticAuthentication = true;
                
    options.SecurityTokenValidators = new[]
    {
        new JwtSecurityTokenHandler()
    };
});
```

**Comment by matt-shepherd** [comment]
Hi @fekberg, are you issuing the token from the same project?  I have it being issued from another app, used your example above however still getting a 401.

Also why do you need to provide the IssuerSigningKeys?  I thought the idea of JWT was that it provided that info in the metadata?

**Comment by fekberg** [comment]
@matt-shepherd, I couldn't get that to work, using the meta-data that is, so I had to specify the public key manually and it works like a charm.

You say you are getting a 401, are you sure the header `Authorization` with the content `Bearer TOKEN` is set? (Where `TOKEN` is the actual access token).

Does your logs say anything about why it fails to accept the access token?

One of the endpoints in IdSvr will give you the public key, make sure you use the same one.

**Comment by matt-shepherd** [comment]
Thanks for replying @fekberg. I have the Authorization header set with bearer and token. I have even verified the token against the issuing WebAPI project. I also spun up another WebAPI 2 project which works fine.. It's just this vNext project which won't play ball.

As for the log, I only seem to be able to log the IdSrv request for the token, I can't get any output when hitting the vNext project and requesting auh with the token.

My setup: WebAPI 2 IdSrv providing tokens for gramt_type : password
ASP.NET vNext project with controllers decorated with Authorize attribute and Startup.cs configured as you described.

**Comment by fekberg** [comment]
Did you try adding `app.UseErrorPage(ErrorPageOptions.ShowAll);` ? or even 

```
app.UseErrorHandler(errorApp => { errorApp.Run(context => { }) });
```

You might have validation errors that you're not getting, worth having a look. If you turn on verbose logging on IdSvr, does it indicate that the API tries to ping it? Should say something like "Starting Key Discovery".

I'm using the following `UseOAuthBearerAuthentication`:

```
app.UseOAuthBearerAuthentication(options =>
{
    options.Authority = "http://myoauthserver/oauth";
    options.Audience = "http://myoauthserver/oauth/resources";

    options.TokenValidationParameters = new TokenValidationParameters
    {
        IssuerSigningKeys = new[] { new X509SecurityKey(cert) },
        ValidateLifetime = true,
    };
    options.AutomaticAuthentication = true;
    options.SecurityTokenValidators = new[]
    {
        new JwtSecurityTokenHandler()
    };
});
```

And that works for me.

**Comment by matt-shepherd** [comment]
Hey @fekberg thanks so much for the time you've spent helping however I managed to get it working simply with:

app.UseOAuthBearerAuthentication(options =>
                {
                    options.Authority = "http://localhost:36416/core";
                    options.Audience = "https://auth.shipr.io/resources";

                    options.AutomaticAuthentication = true;
                });

Appreciate your help.

**Comment by fekberg** [comment]
That's excellent @matt-shepherd! So that automatically fetched the correct key from the server and validated the access token?

**Comment by stephenstroud** [comment]
@fekberg  Do you have an example how you created the bearer token on login please? I'm trying to achieve this http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api

**Comment by fekberg** [comment]
@stephenstroud IdentityServer returns the bearer token when you've done a successful request to `authorize/token`.
