### ISSUE TITLE
Using CORS with ASP.NET 5

### ISSUE THREAD

**Issue by fekberg** [IdentityServer/IdentityServer3.Samples#123]
The following fails when using the JavaScript Client example. I've configured the ASP.NET 5 startup like the following:

```
app.Map("/identity", oauth =>
{
    var factory = InMemoryFactory.Create(
                        users: Users.Get(),
                        clients: Clients.Get(),
                        scopes: Scopes.Get());

    factory.CorsPolicyService = 
             new Registration<ICorsPolicyService>(new InMemoryCorsPolicyService(Clients.Get()));

    var idsrvOptions = new IdentityServerOptions
    {
        Factory = factory,
        RequireSsl = false,
        SigningCertificate = cert
    };

    oauth.UseIdentityServer(idsrvOptions);
});
```

I've also tried to create a custom `ICorsPolicyService` but it never hits the method `IsOriginAllowedAsync(string)`. 

The client performs the following API call after having received a token using the Implicit Flow:

```
$.ajax({
    url: "http://localhost:5000/api/values",
    dataType: 'jsonp',
    beforeSend: function (xhr) {
        xhr.setRequestHeader("Authorization", "Bearer " + token);
    },
    success: function (data) {
        show(data);
    }
});
```

This results in a `HTTP 401`, but if I use the token and perform the request from Fiddler it works. It seems as the Authorization Header is never set properly, hence the server is not returning the correct headers to start with.

Any idea why this might be?

**Comment by brockallen** [comment]
What exact version of IdSvr, and what do the logs say?

**Comment by brockallen** [comment]
Perhaps related? https://github.com/IdentityServer/IdentityServer3/issues/1293

**Comment by brockallen** [comment]
Oh sorry -- Your Ajax call is to your API, not to IdSvr. Maybe that's why your CORS code in IdSvr is not called -- it's your API that needs to allow CORS.

**Comment by brockallen** [comment]
Any progress?

**Comment by fekberg** [comment]
@brockallen sorry for the long response time. I'm using the latest IdentityServer3 with MVC6.

You are right, it's a call to the API so most likely need to set the correct CORS settings for that as well.

Close this question for now, if I end up having the same issue I'll reach out again!

Thanks a lot!
