### ISSUE TITLE
AspNetIdentity_2fa owin context AuthenticateAsync null

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3.Samples#124]
Hello,

I try to run this sample project **AspNetIdentity_2fa** and after i login using https://localhost:44333/core/permissions i try to access https://localhost:44333/core/2fa and this code:
```C#
var ctx = Request.GetOwinContext();
            var authentication = await ctx.Authentication.AuthenticateAsync(Constants.PartialSignInAuthenticationType);```
return null. why?

**Comment by leastprivilege** [comment]
You can't access the 2fa controller directly - it must be part of a login flow.

**Comment by totpero** [comment]
i login when i access this link: https://localhost:44333/core/permissions

**Comment by brockallen** [comment]
Did you ever resolve this? I was just working with that sample the other day and it was working fine.
