### ISSUE TITLE
Angular.js client sample for token manager integration

### ISSUE THREAD

**Issue by gilm0079** [IdentityServer/IdentityServer3.Samples#127]
Maybe this is a lot simpler than I'm making it out to be.  I have an angular app and I'm trying to integrate the javascript token manager sample into it.  My authentication page works, obtains a token, routes to the next angular page and can use the token from the manager to make an authenticated API call.  I'm using an authentication http provider interceptor to inject the bearer token into all requests.  As long as the window.mgr is alive it works.  It seems though that the window.mgr object becomes undefined if the page reloads like when I refresh the browser.

Any suggestions on the appropriate way to integrate the Token Manager into Angular?  I've seen a authentication service used as a popular route for code separation.  It seems like I can new up the mgr object in each Angular controller (mgr = new OidcTokenManager()) and that gives me back access to the token from localStorage.  I would assume though that the config object for the constructor would need to follow though so the TokenManager knows where to refresh tokens from.   I tried moving it to a service, but the console complains that some of the manager event handlers are not functions. ie. addOnTokenObtained is not a function

I'll put my code below for those looking to make use of the bearer token http interceptor in angular.  Keep in mind that it references the window.mgr so if that is not the proper place to get the token manager from then it will need to be changed accordingly.

I put this in my core project's config.js and added it as a factory to my core module.
### Http Interceptor for bearer token injection
```
var core = angular.module('coreMod');

core.factory('authInjector', authInjector);
authInjector.$inject = ['$q', '$window'];
function authInjector($q, $window) {
        return {
            request: function (config) {
                var mgr = $window.mgr;
                if (!!mgr) {
                    config.headers = config.headers || {};
                    if (!!mgr['access_token']) {
                        config.headers['Authorization'] = 'Bearer ' + mgr.access_token;
                    }
                }
                return config;
            },
            responseError: function (response) {
                var mgr = $window.mgr;
                if (!!mgr) {
                    if (response.status === 401 && !!mgr['access_token']) {
                        mgr.removeToken();
                    }
                    if (response.status === 403 && !!mgr['access_token']) {
                        mgr.removeToken();
                    }
                }
                return $q.reject(response);
            }
        };
    }

core.config(configure);

configure.$inject = ['$httpProvider'];
function configure($httpProvider) {
    $httpProvider.interceptors.push('authInjector');
}
```

I stripped out irrelevant code to simplify. If you are used to the angular architecture of john papa this should look familiar.

**Comment by iltera** [comment]
I strumbled getting and checking the access_token from OIDC Manager a couple of months ago. I found the solution by moving OIDC Manager out of the scope of Angular app by defining a global mgr object and only getting access_token and profile info from that global variable where needed, in order to not recall and create instances of the OIDC Manager object everytime a call to the API is made. Creating multiple instances of Manager coused only headaches for me when used in a service or interceptor. It gets a new access_token everytime when Manager is accessed and if you're renewing the access_tokens automatically, there are errors appearing on the console and application breaks at some point.

Moving the Manager object out of Angular and accessing it once during the app lifecycle works for now, but I am still questioning this approach as it is very far from an elegant Angular Way solution.

Can you please explain, how and where are you creating the $window.mgr object in your app? Are you having the side effects that I've explained below?

**Comment by gilm0079** [comment]
Storing the Token Manager in window.mgr comes from the Identity server client sample OAuthJS.  The login page instantiates the Token Manager and sets it to the window.mgr.  In angular I'm just swapping out window.mgr for $window.mgr as it sounds like $window is the proper wrapper to use for testing or something.  

I was hoping someone from the Identity Server dev team could chime in on their thoughts for angular integration.  I'm still working out some issues regarding silent token renewal, moving the Token Manager to an authentication service module and I'm not fond of the token manager getting attached to the "window". It seems to be destroyed on a browser refresh.

For the time being I'm probably just going to have to include code in my controllers to rebuild the Token Manager and set it to the window each time to make sure that the window.mgr exists.

**Comment by brockallen** [comment]
Yea, create a global TokenMgr and inject it into as a constant into NG. That's one idea -- i'm sure there are others.

**Comment by iltera** [comment]
@brockallen, thanks for the input. That was what I came up doing a few months back. Wasn't sure it was the right thing to do till I saw your message. Now I am relaxed :)

**Comment by gilm0079** [comment]
Thanks @brockallen , good to hear a the tokenMgr will work fine if I stick it in the $rootScope.  I have the TokenManager working now as an Angular service.

The only issue I ran into was trying to put the callback endpoint as an angular route/controller.  I don't think it will work in my setup right now.  My Angular app is not running in Html5 mode so the Angular app uses the hash sign in the URL space to separate the server side route from the angular route.  I think that hash is breaking the callback id_token hash coming back from the identity server.  I'm watching fiddler and normally the callback will look something like ".../callback.html#id_token=<some_token>".  When I try using the angular callback route/controller the identity server response url looks like this ".../app#/callbackid_token=<some_token>".  You can see that the Identity server doesn't insert a hash between the redirect Uri and the token response.  Because of that I think the Oidc.js fails to parse the window.location.hash correctly.

Do you know if there is a way to make this work with angular or why the identity server doesn't insert a preceeding hash in this case?  I'm not overly concerned if not.  a non-angular callback page doesn't seem to hurt anything.  I think the only overhead is the non-angular callback will need to pull down the required script files (oidc.js and jquery) and new up the Token Manager before it can process the callback vs. the angular page would have the 3rd party libraries and Token Manager already initialized.

**Comment by brockallen** [comment]
Yes, I do this in IdentityManager -- here's the route[1]/controller[2] that accept the token via the hash fragment:

[1] https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Assets/Scripts/App/ttIdmApp.js#L16

[2] https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Assets/Scripts/App/ttIdmApp.js#L96

**Comment by brockallen** [comment]
Oh and for everyone, here's how i inject the token manager:

https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Assets/Scripts/App/ttIdm.js#L253

and then I wrap it with my own service:

https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Assets/Scripts/App/ttIdm.js#L57

**Comment by gilm0079** [comment]
Thanks @brockallen .  I updated the route with the /:response and the response hash parsing and that fixed it.  The callback is now operating with in angular.
