### ISSUE TITLE
Custom Registration Workflow Sample

### ISSUE THREAD

**Issue by peske** [IdentityServer/IdentityServer3.Samples#128]
I'm trying to implement IdentityServer3 with MembershipReboot + external providers. But when a user uses external provider I would like to enforce him to pick local username (instead of using auto-generated username). I've saw Brock Allen's video at vimeo where he's mentioned that such custom workflows are possible, but he hasn't explained how to accomplish this. (There he's promised that this topic will be explained in other video but obviously it hasn't happened.)
Is there any sample where any kind of custom registration workflow is implemented?
Thanks!

**Comment by leastprivilege** [comment]
Sure. Check the custom user service samples.

**Comment by peske** [comment]
Thanks Dominick!

Btw. I've enjoyed in your Pluralsight courses...

On Sat, May 23, 2015 at 4:57 PM, Dominick Baier <notifications@github.com>
wrote:

> Sure. Check the custom user service samples.
>
> Sent from my iPhone
>
> > On 23.05.2015, at 14:54, peske <notifications@github.com> wrote:
> >
> > I'm trying to implement IdentityServer3 with MembershipReboot + external
> providers. But when a user uses external provider I would like to enforce
> him to pick local username (instead of using auto-generated username). I've
> saw Brock Allen's video at vimeo where he's mentioned that such custom
> workflows are possible, but he hasn't explained how to accomplish this.
> (There he's promised that this topic will be explained in other video but
> obviously it hasn't happened.)
> > Is there any sample where any kind of custom registration workflow is
> implemented?
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3.Samples/issues/128#issuecomment-104904666>
> .
>



-- 
Aleksandar Pesic
MS, MCAD
Software Architect

**Comment by peske** [comment]
Yes, that's it!

Thanks Dominick!
