### ISSUE TITLE
401 response running Client Samples

### ISSUE THREAD

**Issue by DarrenMa** [IdentityServer/IdentityServer3.Samples#129]
Hi,

Cloned IdentityServer3.Samples, 
Run Webhost (minimal) [IDsrv] and added some logging with `LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());`
**Run Console Resource Owner Flow** (Client samples)

Receive HTTP Error = not found.

Change Constants projects from
`public const string BaseAddress = "https://localhost:44333/core"; `
to
`public const string BaseAddress = "https://localhost:44333";`

Rerun the Console Resource Owner Flow  and now the call to the IDsrv works and a token is issued. ([Execution up to line 19 in Program.cs](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/ConsoleResourceOwnerClient/Program.cs#L19) )
Viewing the logs of the web server I can see the token response has been returned.
There is also nothing futher on the logs after this.

Press enter to now call the WebAPI (Continue execution of Console Resource Owner Flow)

App throws an error on [line 50](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/ConsoleResourceOwnerClient/Program.cs#L50) which I believe to be a 401 response, when placed into a try catch and viewing the inner exception.

I copied the access token and tried to use Postman to hit the WebAPI http://localhost:2727/identity with Authorization : Bearer xxxxxxx and I still get back "Message": "Authorization has been denied for this request." 401 Unauthorized.

What am I doing wrong?

**Comment by brockallen** [comment]
You need to run the API sample host as well.

**Comment by DarrenMa** [comment]
I think I am running the SampleAspNetWebApi because if I hit http://localhost:2727/test then I do get a response from the TestController.

**Comment by DarrenMa** [comment]
@brockallen I changed the order my projects were building and it's working now. Sorry for the false alarm.
