### ISSUE TITLE
Adding registration link in login page

### ISSUE THREAD

**Issue by prasadnadendla** [IdentityServer/IdentityServer3.Samples#130]
Hi , I am using Membershipreboot  for user management and SQL server as data store. I want to add resgistration link to the login page and then i want to create user in database using menbershipreboot.

I got to know how to add registration link in login page but , i am not getting any idea how to create user in database using membership reboot. Here i am using MembershipReboot(SelfHost) sample.

Here My intention is if users have credentials then they will login or else they will  register

**Comment by brockallen** [comment]
If you want to build a registration page you should look at the MR samples: https://github.com/brockallen/BrockAllen.MembershipReboot/
