### ISSUE TITLE
Problem with calling Web API

### ISSUE THREAD

**Issue by peske** [IdentityServer/IdentityServer3.Samples#131]
I've created my own custom implementation of IdSrv, and I've added all your sample client apps for testing. I have problem when using "WPF Implicit Client" and "JavaScript Implicit Client". Although in both cases clients do get Id and Access tokens, call to Web API included in samples (http://localhost:2727/identity) results in "Unauthorized" response in both cases.

One thing that I've changed in my custom IdSrv implementation is signing certificate, that is loaded from certificate store, instead of using your default idsrv3test.pfx, so I suspect that this is the reason for Web API to reject the calls. But I've analyzed Web API code, and I haven't found any code that validates certificate.

Any advise?

Thanks!

**Comment by brockallen** [comment]
I'd make sure the Web API is still pointing to the correct metadata for IdSvr. Not sure what else to say, other than to trace the HTTP calls to find out where it dies.
