### ISSUE TITLE
MVC 6 Client example

### ISSUE THREAD

**Issue by f0rt** [IdentityServer/IdentityServer3.Samples#132]
Hi,

I'm looking for a ASP.NET 5 Client example. Can you please assist.

Thanks,
f0rt

**Comment by brockallen** [comment]
I'm not sure if there's an OIDC MW yet for ASP.NET 5.

**Comment by f0rt** [comment]
I've found it: "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-beta4"
I was able to run some existing examples with it. Thanks.
