### ISSUE TITLE
implicitflow client with iframe

### ISSUE THREAD

**Issue by mynkow** [IdentityServer/IdentityServer3.Samples#133]
I am looking at the client here https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/JavaScriptImplicitClient/oidc.js

It works with frame which means that on the IdSrv side I have to plugin to the OWIN middleware and add a bunch of headers like this:

```
app.Use((context, next) =>
{
    context.Response.Headers.Add("X-Frame-Options", new string[] { "ALLOW-FROM https://domain.com" });
    context.Response.Headers.Add("Access-Control-Allow-Origin", new string[] { https://domain.com" });
    context.Response.Headers.Add("Access-Control-Allow-Methods", new string[] { "GET,HEAD,POST,OPTIONS,TRACE" });
    context.Response.Headers.Add("Access-Control-Allow-Headers", new string[] { "Content-Type,Authorization,Accept" });
    context.Response.Headers.Add("Access-Control-Allow-Credentials", new string[] { "true" });
    context.Response.Headers.Add("Allow", new string[] { "GET,HEAD,POST,OPTIONS,TRACE" });
    if (context.Request.Method == "OPTIONS")
    {
        return context.Response.WriteAsync(string.Empty);
    }
    return next();
 });
-----------------------



Is there any updated implicitflow client which works without adding these headers or I should write my own which does not use iframe?

PS: the client application is pure html + javascript hosted on IIS + https

**Comment by mynkow** [comment]
Well, reading the documentation for 10 min can save you a day of try/fail tactics

http://identityserver.github.io/Documentation/docs/configuration/cors.html

**Comment by brockallen** [comment]
_Well, reading the documentation for 10 min can save you a day of try/fail tactics_

I wish everyone knew that! :)

**Comment by mynkow** [comment]
I wrote it wrong. The correct one is:

Well, a day of try/fail tactics can save you 10 min reading the documentation :)

**Comment by brockallen** [comment]
In any event, the docs save time -- that's for sure.
