### ISSUE TITLE
WebAPI is not getting authorized in ASP.NET 5

### ISSUE THREAD

**Issue by zoranpro** [IdentityServer/IdentityServer3.Samples#134]
Hi,

I am trying to implement solution like you did but I am having trouble for my api resource to authorize. I am using `1.0.0-beta4` libraries.
Here is how my user and client look like:
``` 
new InMemoryUser  {
        Username = "bob",
        Password = "secret",
        Subject = "1"
   }

new Client
            {
                ClientName = "Silicon on behalf of Carbon Client",
                ClientId = "carbon",
                Enabled = true,
                AccessTokenType = AccessTokenType.Reference,

                Flow = Flows.ResourceOwner,
                ClientSecrets = new List<ClientSecret>
                {
                    new ClientSecret("21B5F798-BE55-42BC-8AA8-0025B903DC3B".Sha256())
                }
            }
```
I have also tried with `AccessTokenType = AccessTokenType.Jwt`

Settings in Startup class are the same. 

Here you can see how do I call the token and what I get for the result.
![access_token](https://cloud.githubusercontent.com/assets/2167739/7960729/0573d0b8-0a03-11e5-99e8-be966a4987d2.PNG)
![not_authorized](https://cloud.githubusercontent.com/assets/2167739/7960740/18a5c89e-0a03-11e5-92a7-9f224188fa4c.PNG)

I am not sure what I am missing here? 
Also I am not quite sure how will API resource server validate the token?

**Comment by brockallen** [comment]
It looks like you got back a valid access token -- what's wrong?

**Comment by zoranpro** [comment]
As you can see on second image, I do exactly that. But for some reason token does not get validated. I always get 401 when I try to call the API. Its like that API doesn't make proper check for that token, not sure.

**Comment by brockallen** [comment]
I guess it depends on how your API is coded to validate the token. Did you follow the sample code in the API sample?

**Comment by zoranpro** [comment]
Yes I did. Here is how the code in `Startup.cs` look like:

```
 app.Map("/core", core =>
            {
                var certFile = env.ApplicationBasePath + "\\Configurations\\idsrv3test.pfx";

                var factory = InMemoryFactory.Create(
                                users: Users.Get(),
                                clients: Clients.Get(),
                                scopes: Scopes.Get());

                var idsrvOptions = new IdentityServerOptions
                {
                    IssuerUri = "https://idsrv3.com",
                    Factory = factory,
                    SiteName = "test vnext Identity server",
                    RequireSsl = false,
                    
                    SigningCertificate = new X509Certificate2(certFile, "idsrv3test"),
                    CorsPolicy = CorsPolicy.AllowAll,

                    AuthenticationOptions = new AuthenticationOptions {    }
                };

                core.UseIdentityServer(idsrvOptions);
            });
            
            app.Map("/api", api =>
            {
                api.UseOAuthBearerAuthentication(options => {
                    options.Authority = "http://localhost:58382/core";
                    options.MetadataAddress = "http://localhost:58382/core/.well-known/openid-configuration";
                    options.TokenValidationParameters.ValidAudience = "https://idsrv3.com/resources";
                });
                api.UseMvc();
            });
```

**Comment by brockallen** [comment]
This is your IdSvr config, not your API config.

**Comment by brockallen** [comment]
Any update?

**Comment by zoranpro** [comment]
I was missing `IssuerSigningKey = new X509SecurityKey(new X509Certificate2(certFile, "idsrv3test"))` in `TokenValidationParameters`. After that I manage to make it to work.
