### ISSUE TITLE
Configuring email event handler

### ISSUE THREAD

**Issue by prasadnadendla** [IdentityServer/IdentityServer3.Samples#135]
Hi I am using Identity server Membership sample.I want to configure event handler for sending verification key to the email on password reset.Could you please guide me how could I configure?

**Comment by brockallen** [comment]
You're using MembershipReboot? See the MR samples: https://github.com/brockallen/BrockAllen.MembershipReboot/tree/master/samples

**Comment by prasadnadendla** [comment]
Can you able to specifically tell me which example should i have to look into from the above link?

**Comment by brockallen** [comment]
I think any of the single tenant samples configures the email event handler. Also, you don't need to use the built-in email event handlers - you can use your own custom event handlers (https://github.com/brockallen/BrockAllen.MembershipReboot/wiki/Account-Events).

**Comment by prasadnadendla** [comment]
would you able to tell me the builtin event handler for password reset?

**Comment by brockallen** [comment]
Here are the events raised: https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot/AccountService/UserAccountEvents.cs
