### ISSUE TITLE
401 Unauthorized Error for Implicit flow client example while accessing Web Api

### ISSUE THREAD

**Issue by RahulNET** [IdentityServer/IdentityServer3.Samples#136]
Hi,
Here is my scenario:
1. A configured instance of Identity Server 3 is running.
2. From the "Clients" solution, ran the SampleAspNetWebApi (as Relying Party)
3. Ran the client (https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient-Simple) for implicit flow
4. I click on "Get Token" in the UI from point 3 above.  I am presented the login screen.  I login.  I receive the access token and is shown in the page.
5.  I click on "Use Token".  I receive the following.
{
  "status": 401,
  "statusText": "Unauthorized",
  "wwwAuthenticate": "Bearer"
}

Note:  I tried running the following sample as well.

http://identityserver.github.io/Documentation/docs/overview/simplestOAuth.html

 got same 401 Unauthorized while accessing the Web Api.

Please suggest.

**Comment by brockallen** [comment]
Hmm, not sure. You'd need to debug some more into why the API is rejecting the token.

**Comment by ghidello** [comment]
Can you check if the authority property of the IdentityServerBearerTokenAuthenticationOptions class is correctly configured with your IdentityServer url?

**Comment by brockallen** [comment]
@RahulNET any update?
