### ISSUE TITLE
ASP.NET 5 client sample is good to have.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer3.Samples#139]

**Comment by matt-shepherd** [comment]
Appears AccessTokenValidation hasn't made it across to vNext so UseIdentityServerBearerTokenAuthentication doesn't exist and I'm having issues with UseOAuthBearerAuthentication, or it just generally not working.  Even with a valid token i get a 401.

**Comment by brockallen** [comment]
We will put one out when we can. I'll close this for now.
