### ISSUE TITLE
IViewService after login CurrentUser is null and IsAuthenticated = false

### ISSUE THREAD

**Issue by Mounske** [IdentityServer/IdentityServer3.Samples#145]
Hi,

Based on the sample provided, I have implemented in my solution the "CustomViewService" (IViewService), which load automatically login, logout etc.. that works perfectly!

However when I have created another Controller (to update user name for example), when I login and then go to that new page, the issue is that I'm losing any info regarding the login (IsAuthenticated = false) and even when I'm adding the [Authorize] above my controller I can't access the page..
And also, User.GetUserID() is giving error..

Could you please give some lead, maybe I'm missing something..

Thanks in advance

**Comment by brockallen** [comment]
You need to check the authenticated user via the OWIN environment extensions exposed from IdSvr.
