### ISSUE TITLE
UseOAuthBearerAuthentication Usage in ASP.NET 5 Guidance

### ISSUE THREAD

**Issue by matt-shepherd** [IdentityServer/IdentityServer3.Samples#146]
Would it be possible to get some guidance or advice as how to get a vNext API to authenticate a token generated by an externally hosted IdSrv?

I've tried:

    appi.UseOAuthBearerAuthentication(options => {
        options.Authority = "http://localhost:36416/core";
        options.MetadataAddress = "http://localhost:36416/core/.well-known/openid-configuration";
        options.TokenValidationParameters.ValidAudience = "https://shipr/resources";
    });

but im just getting a 401 in response.  Have validated the token and IdSrv is working ok with a WebAPI 2 implementation of UseIdentityServerBearerTokenAuthentication which works fine, but struggling with a vNext project and UseOAuthBearerAuthentication.

**Comment by leastprivilege** [comment]
IIRC - you need to do this

```csharp
app.UseOAuthBearerAuthentication(options =>
{
    options.Authority = "https://base_address_of_idsrv";
    options.Audience = "https://base_address_of_idsrv/resources";

    options.AutomaticAuthentication = true;
});
```

If you have manually configured the issuer name of idsrv then you need to use `issuerName/resources` as audience.

**Comment by leastprivilege** [comment]
The scope checking has to be done manually as well.

**Comment by matt-shepherd** [comment]
When you say that you have to do the scope checking manually..  strictly speaking, thats optional right?  Without checking the scope it should still work?

**Comment by brockallen** [comment]
By work, you mean the call will be allowed in? Yes. But if you're using scopes and the caller does not have the right scope then you want to reject the call.

**Comment by matt-shepherd** [comment]
thank you guys so much!  I honestly don't know what i was doing other than that, but it worked a treat!
