### ISSUE TITLE
ASP.NET vNext - invalid_scope

### ISSUE THREAD

**Issue by matt-shepherd** [IdentityServer/IdentityServer3.Samples#147]
First of all thanks for all the help and support upto now.  It's very much appreciated but I have this little issue below..

So for simplicity I've tried moving the IdSrv3 into my web app, rather than maintaining two separate apps.

My Setup.cs looks like:

            app.Map("/core", core =>
            {
                var factory = InMemoryFactory.Create(
                                Users.Get(),
                                Clients.Get(),
                                Scopes.Get());

                factory.CorsPolicyService =
                    new Registration<IdentityServer3.Core.Services.ICorsPolicyService>(
                        new DefaultCorsPolicyService() { AllowAll = true });

                var idsrvOptions = new IdentityServerOptions
                {
                    Factory = factory,
                    RequireSsl = false,
                    SigningCertificate = new X509Certificate2(certFile, "idsrv3test")
                };

                core.UseIdentityServer(idsrvOptions);
            });

and Scopes.cs:

   public class Scopes
    {
        public static IEnumerable<Scope> Get()
        {
            List<Scope> scopes = new List<Scope>();

            scopes.AddRange(StandardScopes.All);

            scopes.Add(new Scope
            {
                Name = "api1",
                DisplayName = "some scope",
                Emphasize = true,
                ShowInDiscoveryDocument = true,
                Type = ScopeType.Resource

            });

            return scopes;
        }
    }

with all other implementation being the same as the vNext sample.  However when requesting a token using grant_type password I get a 400 with an "invalid_Scope" error.

Looking in the log and i see:

iisexpress.exe Warning: 0 : [IdentityServer3.Core.Configuration.IdentityServerServiceFactory]: 15/07/2015 12:44:24 +00:00 -- AuthorizationCodeStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : [IdentityServer3.Core.Configuration.IdentityServerServiceFactory]: 15/07/2015 12:44:24 +00:00 -- TokenHandleStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : [IdentityServer3.Core.Configuration.IdentityServerServiceFactory]: 15/07/2015 12:44:24 +00:00 -- ConsentStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : [IdentityServer3.Core.Configuration.IdentityServerServiceFactory]: 15/07/2015 12:44:24 +00:00 -- RefreshTokenStore not configured - falling back to InMemory
iisexpress.exe Information: 0 : [IdentityServer3.Core.Configuration.Hosting.CorsPolicyProvider]: 15/07/2015 12:44:25 +00:00 -- CORS request made for path: {0} from origin: {1}
iisexpress.exe Information: 0 : [IdentityServer3.Core.Services.Default.DefaultCorsPolicyService]: 15/07/2015 12:44:25 +00:00 -- AllowAll true, so origin: {0} is allowed
iisexpress.exe Information: 0 : [IdentityServer3.Core.Configuration.Hosting.CorsPolicyProvider]: 15/07/2015 12:44:25 +00:00 -- CorsPolicyService allowed origin
iisexpress.exe Information: 0 : [IdentityServer3.Core.Endpoints.TokenEndpointController]: 15/07/2015 12:44:25 +00:00 -- Start token request
iisexpress.exe Information: 0 : [IdentityServer3.Core.Services.Default.DefaultClientValidator]: 15/07/2015 12:44:25 +00:00 -- Starting client validation.
Debug: [IdentityServer3.Core.Validation.ClientValidatorBase]: 15/07/2015 12:44:25 +00:00 -- No credential found: BasicAuthenticationClientValidator
iisexpress.exe Information: 0 : [IdentityServer3.Core.Validation.ClientValidatorBase]: 15/07/2015 12:44:25 +00:00 -- {0}
 {1}
iisexpress.exe Information: 0 : [IdentityServer3.Core.Validation.TokenRequestValidator]: 15/07/2015 12:44:25 +00:00 -- Start token request validation
iisexpress.exe Information: 0 : [IdentityServer3.Core.Validation.TokenRequestValidator]: 15/07/2015 12:44:25 +00:00 -- Start password token request validation
iisexpress.exe Error: 0 : [IdentityServer3.Core.Validation.ScopeValidator]: 15/07/2015 12:44:25 +00:00 -- Requested scope not allowed: {0}
iisexpress.exe Error: 0 : [IdentityServer3.Core.Validation.TokenRequestValidator]: 15/07/2015 12:44:25 +00:00 -- {0}
 {1}
iisexpress.exe Information: 0 : [IdentityServer3.Core.Endpoints.TokenEndpointController]: 15/07/2015 12:44:25 +00:00 -- End token request
iisexpress.exe Information: 0 : [IdentityServer3.Core.Results.TokenErrorResult]: 15/07/2015 12:44:25 +00:00 -- Returning error: invalid_scope

running almost identical code from a WebAPI 2 app returns the token and validates fine.  Just seem to be tripping up on vNext.  Any ideas?

**Comment by brockallen** [comment]
If you're on 2.0.0 then you need to set AllowedScopes on the Client config.

**Comment by matt-shepherd** [comment]
You sir, are a genius!  Thank you!

Now how to setup ASPNET Identity 3 with IdSrv3 on vNext :)

**Comment by brockallen** [comment]
G'dluck -- I've not ever tried that myself.

**Comment by matt-shepherd** [comment]
Not what I wanted to read!! :)

**Comment by matt-shepherd** [comment]
So that worked and was quite easy!  Just had to refactor the AspNetIdentityUserService to use the new bits from IUserService and the new UserManager, pretty painless!

Next step is to tie an authenticated user back into the ApplicationUser to access profile data, any pointers as where / how to do this?

**Comment by matt-shepherd** [comment]
For some reason, im not getting the subject back from my access token.  it Validates fine against the accesstokenvalidation endpoint and contains all the claims, but I cant seem to get them inside my protected Controller Action.

Any ideas?

**Comment by brockallen** [comment]
Not sure -- inspect the token with http://jwt.io

**Comment by matt-shepherd** [comment]
that worked: 
{
  "client_id": "shipr_admin",
  "scope": [
    "email",
    "openid"
  ],
  "sub": "fd11756d-49a7-4541-90c8-14505030c81b",
  "amr": "password",
  "auth_time": 1437049321,
  "idp": "idsrv",
  "iss": "http://dev.shipr.io/core",
  "aud": "http://dev.shipr.io/core/resources",
  "exp": 1437052921,
  "nbf": 1437049321
}

I seem to of "found" the subject..  but nested quite deep:

           return ((ClaimsIdentity)User.Identity).Claims.First().Subject.Claims.Select(s => new
            {
                label = s.Type,
                value = s.Value
            });

Whats the preferred way to pull the subject out?

Claims.First().Subject.Name is where i expected it, but thats null.

**Comment by brockallen** [comment]
Use LINQ

**Comment by matt-shepherd** [comment]
So the framework wont help me out at all in serving up the subject? It seems to carry the "type" http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier...  so im just searching the claims for that?

**Comment by brockallen** [comment]
That's Microsoft's fault -- they're changing the claims types because they think it's helpful. Add this line of code to your app at startup time and they won't do that:

```
JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
```

**Comment by matt-shepherd** [comment]
Figured as much, thanks Brock.

**Comment by matt-shepherd** [comment]
Just incase its helpful to anyone else trying to use the Microsoft bits in the client, the ClaimsIdentity will not have a name, as Microsoft are looking for a unique_name claim.

   JwtSecurityTokenHandler.InboundClaimTypeMap.Add("name", System.Security.Claims.ClaimTypes.Name); 

adds a mapping so the username is hydrated.

Not sure if this is the best way about it, but it saves manual mapping and ClaimsPrinciple creation.

**Comment by rh78** [comment]
Hi i also tried to use ASP.NET vnext + IdSrv3 + ASP.NET Identity 3. I used the same approach as Matt mentioned, but whenever I try to access data through the Identity 3 user service I got from IServiceProvider (it is queried within the "refactored" AspNetIdentityUserService), I get ObjectDisposedException - it seems to be impossible to me to get the correct, up to date instance of the user service as it is registered in a scoped way. IdSrv3 Autofac of course knows nothing about the vnext dependency system so this way is also blocked. Any hints?

**Comment by rh78** [comment]
In general after some research there is a critical problem. Of course, the ASP.NET vNext IdSrv3 integration works and it can RUN the IdSrv3. But as soon as one wants to access some scoped services (like Entity Framework) etc. registered to the new vNext DI container it will fail because it is IMHO impossible to get the "current" version of the ServiceProvider - if you pass the ServiceProvider from Startup it will always contain disposed objects. Allen is this right or do you have a solution?

**Comment by rh78** [comment]
Actually I found the solution. It is possible to get OwinEnvironmentService injected into the UserService constructor. I checked the vnext-OWIN bridge and actually the current HttpContext containing the RequestServices is being passed to the OWIN environment, and can be extracted like this:

HttpContext context = (HttpContext)(owin.Environment)[typeof(HttpContext).FullName];

ServiceProvider = context.RequestServices;
