### ISSUE TITLE
Add Role Claims to ID Token

### ISSUE THREAD

**Issue by daishisystems** [IdentityServer/IdentityServer3.Samples#148]
Connecting to the /connect/token endpoint in the following manner:

```
grant_type=authorization_code&code=702c3bef1c6e5eee3059f70227000709&redirect_uri=https://localhost:44304/account/callback&scope=openid profile email roles offline_access
```

yields an ID Token, but without any role, email, or profile claims, despite the fact that these are set in the Auth Token request, and in the Scopes.cs class.

How do I ensure that my ID Token contains these claims?

**Comment by brockallen** [comment]
`ScopeClaim.AlwaysIncludeInIdToken`

https://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html

**Comment by daishisystems** [comment]
Thanks. So there is no way to add claims associated with default scopes to an ID Token. I must add a new custom scope and tag associated claims with *_AlwaysIncludeInIdToken_* = true?

**Comment by brockallen** [comment]
We have "AlwaysInclude" versions of our StandardScopes.
