### ISSUE TITLE
Ninject causes problems for deploying to IdentityServer production

### ISSUE THREAD

**Issue by cloudybrain** [IdentityServer/IdentityServer3.Samples#155]
This isn't a question, but it proposes a new suggestion for future samples.

So I've been trying to deploy my developed code onto a production server for the last 12 hours, and I found out the culprit.

I took the MVC Authentication sample code, and I expanded on it. I used other samples as well and integrated that in to the MVC Authentication sample. I took sample membershipreboot controllers and added them to my embedded identityserver project. Using sampled ninject code, I was able to get a working project on my localmachine. Example:

    kernel.Bind<UserAccountService>().ToSelf();
    kernel.Bind<AuthenticationService>().To<SamAuthenticationService>();
    kernel.Bind<IUserAccountQuery>().To<DefaultUserAccountRepository>().InRequestScope();
    kernel.Bind<IUserAccountRepository>().To<DefaultUserAccountRepository>().InRequestScope();

However, when I deployed my code to the server, it broke. The error message was extremely weird.

I was getting a yellow screen of death:

“Cannot Connect to Server - A network-related or instance-specific error”

So I checked my connectionstrings, and everything seemed to be okay. My embedded identityserver was logging in with no problems. But when I wanted to use membershipreboot controllers, it caused the ysod.

By chance I also noticed one other thing in my ysod at the very bottom:

An error occurred when trying to create a controller of type 'RegisterController'. Make sure that the controller has a parameterless public constructor.

What?! So I kept checking my code, trying to figure out what I missed. It works on my development machine, not on my remote computer. So I started to remote debug the server, and I found out that ninject in app_start wasn't even doing anything on IIS.. nothing was registering at all. I tried a few more hours to get it to work, and nothing!

So I changed my IoC to SimpleInjector. I've used this utility in the past, it's faster, and it adhere's to SOLID principles. For example, the services you try to register must be set to one constructor only, doing so helps with your testing environment. There's a good article that explains this principle here:

https://cuttingedge.it/blogs/steven/pivot/entry.php?id=97

Instead of placing my code in app_start, I placed it in global.asax and came up with this solution:

    protected void Application_Start()
    {
        // Create the container as usual.
        var container = new Container();

        // Register your types, for instance:
        container.Register<UserAccountService>(() => new UserAccountService(container.GetInstance<IUserAccountRepository>()));
        container.Register<AuthenticationService, SamAuthenticationService>();
        container.Register<IUserAccountQuery>(() => new DefaultUserAccountRepository(new DefaultMembershipRebootDatabase("MyIdentityDb")));
        container.Register<IUserAccountRepository>(() => new DefaultUserAccountRepository(new DefaultMembershipRebootDatabase("MyIdentityDb")));

        // This is an extension method from the integration package.
        container.RegisterMvcControllers(Assembly.GetExecutingAssembly());

        // This is an extension method from the integration package as well.
        container.RegisterMvcIntegratedFilterProvider();
        container.Verify();
        DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));
    }

Notice the registration actually establishes the new connectionstring within the injection. This actually forced me to realize what problems I was encountering when i had ninject. My DefaultUserAccountRepository was using a default connectionstring that I wasn't setting properly. I missed it in the docs. With simpleinjector, as I was trying to get my application to work, it threw a fit telling me good details about what my application needed.

After deploying this project to production, I was finally able to successfully see all my membershipreboot webpages

I'm really hoping that maybe you guys can consider switching IoC container from ninject to something else (like simpleinjector) for future samples.. as sticking with ninject might pose some potential problems down the line.

**Comment by leastprivilege** [comment]
We are using Autofac - not ninject. And this has been discussed before - the DI system will stay as is.

**Comment by cloudybrain** [comment]
Ah sorry! I got confused, I had a MembershipReboot sample from BrockAllen's repo, and migrated a sample from here to integrate with that.. that's where I got the ninject from. MembershipReboot examples have ninject in them, and it caused some headaches and issues.
