### ISSUE TITLE
Question: Custom View Service Example with AngularJS 1.3.15 problem with ng-show directive

### ISSUE THREAD

**Issue by Condor2708** [IdentityServer/IdentityServer3.Samples#158]
The ng-show directive it is always showing the content using angularjs 1.3.15? I want to know if someone experimented the same problem? 

Thanks

**Comment by brockallen** [comment]
what's the expression in the `ng-show`? If it's a collection, then make sure to add the `.length` -- something changed in angular at some point where it was necessary to use `.length`.

**Comment by Condor2708** [comment]
I am using a simple value to test what's happening 
I've added $scope.showText = false;
in the controller and my view is using 
<span ng-show="showText">Here Is What I want to hide/show</span>
