### ISSUE TITLE
ASP.NET 5 Issues

### ISSUE THREAD

**Issue by louislewis2** [IdentityServer/IdentityServer3.Samples#160]
Hi,
I would like to know if I am doing anything wrong.
I am simply trying to extend the demo code you have for ASP.NET 5,
and turn it onto one that uses a persistent data store (SQL).

I get the Microsoft.AspNet.Identity.EntityFramework side of the configuration
done and running as expected.

I also upgraded to your 2.0 release on the server, and went through the minor changes to
get the InMemory stores running again.

I then went down the path and added your IdentityServer3.AspNetIdentity package and
after a few hours and cloning into the repo, this pointed me to take a look at the actual package and 
realised there was no dll, after some more scratching I found the "fix" IdentityServer3.AspNetIdentity.dll. Once I added this, my compiler says that it no longer wants to play along anymore.

I get ambiguous references, your package brings in Microsoft.AspNet.Identity.Core which has a few items defined that are also defined in the Microsoft.AspNet.Identity package. I have not yet been able to get passed this stage.

Where does the fault lie? Am I possibly doing something wrong, is there a problem with package references, dependencies?

Has anyone got the server running using Entity Framework, Sql, AspNet.Identity on ASP.NET 5?
If so, could someone please be so kind as to direct me to it?

**Comment by leastprivilege** [comment]
we recently updated to beta8 - maybe that makes it easier. Besides that - I don't see a point in running idsrv on a beta host (katana works just fine).
