### ISSUE TITLE
"Unauthorized" error requesting access token while testing "Simplest OAuth2 Walkthrough"

### ISSUE THREAD

**Issue by arkreddy16** [IdentityServer/IdentityServer3.Samples#161]
Hi,
Am new to OAuth implementation, so started off with setting up "Simplest OAuth2 Walkthrough" sample. I have just removed SSL for this sample i.e renamed "https://localhost:44333" to "http://localhost:44333" and  
var options = new IdentityServerOptions
            {
                Factory = factory,
                RequireSsl = false //introduced this line of code to bypass SSL
            };
and also hosted "IdSrv" project on IIS(http://localhost/IdSrv") instead of calling "WebApp.Start<Startup>("http://localhost:44333")"

when am trying to run the client i get "Unauthorized" while trying to get "GetClientToken".

**Comment by brockallen** [comment]
Hit F4 on your project in visual studio to see what URL IIS express is configured to use.

**Comment by arkreddy16** [comment]
In IIS Express it is configured as "http://localhost:44333" and this works fine for me, but the problem is when i host same project on IIS Local i.e."http://localhost/IdSrv" and execute the client project i get  "Unauthorized" as HttpErrorReason in TokenResponse that is returned from "GetClientToken" method.

**Comment by brockallen** [comment]
So enable logging in IdSvr and see what it says. If you don't have anything in the log, then I wonder if you have anon disabled in IIS.

**Comment by arkreddy16** [comment]
I have verified that anonymous is enabled in IIS, need to verify logs! Am able to access identity server from browser.

**Comment by brockallen** [comment]
Check the docs.

**Comment by codesilverback** [comment]
I noticed that the packages.config in the samples directory refers to IdentityServer3--a particular build.  When I try to build this from scratch using NuGet, I get the same 401.  Do the samples use pre-release versions that make following along from scratch not work?

**Comment by brockallen** [comment]
All the samples point to myget -- it's just easier for us that way. There's a nuget.config in the project directory that should configure your VS for the right URLs.

**Comment by brockallen** [comment]
Also, please open new issues when asking unrelated/new questions.
