### ISSUE TITLE
Reference-token returns 401

### ISSUE THREAD

**Issue by mohannadkhirallah** [IdentityServer/IdentityServer3.Samples#163]
When I try to invoke an API protected by Identity Server using reference access token, the response code is 401 unauthorized, but when I use JWT access tokens, the API returns 200.

The https://localhost:44303/core/connect/accesstokenvalidation is enabled and working correctly, the reference token is validated and returns 200.

Here is the client configuration in the Identity Server,

![clientconfig](https://cloud.githubusercontent.com/assets/10743014/9386660/2f31f188-4765-11e5-8d4a-8b723c0e2f89.png)

Here is the startup for the identity server
![startup](https://cloud.githubusercontent.com/assets/10743014/9386670/3c1e61ce-4765-11e5-9864-36922942e1f7.png)

Here is the configuration for the Api startup:
![scnapistartup](https://cloud.githubusercontent.com/assets/10743014/9386344/b971b27c-4763-11e5-915b-5fda9a529380.png)

Any ideas how to fix this issue?

**Comment by brockallen** [comment]
Sorry, I don't understand what the issue is.

**Comment by tjoudeh** [comment]
Hi @brockallen, in the clients samples repo [(MvcCodeFlowClientManual)](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MvcCodeFlowClientManual). There is a client with id "codeclient" configured in the IdentityServer to use reference access tokens not JWTs. Everything is working correctly and we are able to receive reference access tokens, but once this client tries to call the Api (Resource Api which is protected by the Identity server) and by sitting the reference access token in the Authorization header using Bearer scheme, we always receive 401, taking in consideration that once we try to validate this reference access token using the endpoint "connect/accesstokenvalidation" we receive 200 and this token is valid.

If we tried to change the access token type for this client to JWT everything works correctly, we receive a JWT, and we are able to use it to access the Resource API, so I believe receiving 401 has nothing to do with missing scopes or misconfigurations between client, Identity Server, and Resource API.

I guess I missed something when I tried to configure Identity Server so those reference access tokens are not validated correctly.

Can you guide me where to look further and try to debug the issue?

Regards,
Taiseer

**Comment by leastprivilege** [comment]
My money is on ssl problems between web api server and idsrv. 

In any case - we use katana logging for more info.
