### ISSUE TITLE
CustomUserService signin querystring

### ISSUE THREAD

**Issue by EliotJones** [IdentityServer/IdentityServer3.Samples#164]
For the LocalRegistrationController in the CustomUserService sample, the register controller takes a ```string signin``` for both Get and Post actions.

The registration works for me but then when it redirects to the login page the signin querystring is blank. Where does the value for signin come from and what is it meant to be. From the other samples I can tell it's some kind of token used to identify the client but I can't tell how the value should be set in this sample so the login page gives an error.

Any hints would be much appreciated.

**Comment by brockallen** [comment]
It should be passed back since in the view it's using  Html.BeginForm() to build the form.

**Comment by EliotJones** [comment]
Thank you, I added an MVC client application to the sample and it redirected to the login page from which I could access the register link with the correct signin querystring.
