### ISSUE TITLE
Create a branch for each release of IdentityServer

### ISSUE THREAD

**Issue by bloudraak** [IdentityServer/IdentityServer3.Samples#167]
Since there are some breaking changes going from 1.6 to 2.0, I'd like to suggest to create a branch for every release. This simply means that every IdentityServer3 repository has v2.0, v1.6 and v1.0 branches.   This allows folks to automatically build those branches as part of their build processes, submit patches for older releases, or if we need to do security scans of a particular release.

**Comment by brockallen** [comment]
Use the labels if you need to look at a specific version.

**Comment by bloudraak** [comment]
The labels do not indicate which version of IdentityServer3 they relate to and there lies my frustration.

**Comment by brockallen** [comment]
Ah yes, in the samples repo -- I see your point. We'll try harder for this one. One workaround is to look at the dates on the core repo for the releases, and then look at when those were merged in samples. Not perfect, but there is correlation.

**Comment by bloudraak** [comment]
Can we just create a branch for each of the 1.6 and 2.0 releases? I made a similar request on the official repo of IdentityServer3.  We can close this one here and keep discussing the merits on the other one.
