### ISSUE TITLE
Issue installing idsrv3test.pfx

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/IdentityServer3.Samples#169]
I was following the instructions laid out in the [Certificates Readme.md](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Certificates). Specifically the first step,

> 1. Install idsrv3test.pfx into your local computer/personal store (password is: idsrv3test)

After running this, I don't see either of the certificates(idsrv3test.cer or DevRoot.cer) in the personal store. 

Should these be present? Or is there a different way to verify that the pfx file installed correctly?

**Comment by ryanvgates** [comment]
I was able to resolve this issue, but I believe that the readme could be more specific and descriptive. I'll add a pull request with my suggested changes.

**Comment by leastprivilege** [comment]
please do that.
