### ISSUE TITLE
Claims Mapping - question

### ISSUE THREAD

**Issue by zebamba** [IdentityServer/IdentityServer3.Samples#173]
We upgraded most of our projects from Think Thinktecture.IdentityServer3 v1.6.2 to IdentityServer3 v2.0.0

<pre>
    var principal = this.User as ClaimsPrincipal;

	if (claim.Type == "sub" && claim.Value != null)
	{
        user.UserId = Guid.Parse(claim.Value);
    }
</pre>

I notice that the code above is creating a user Id full of zeros.

Becouse the Claim Type sub now has type "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier".

I found this file example on the sample source 
https://github.com/IdentityServer/IdentityServer3.Samples/blob/0e4a2036d0ef39d10d09ce98323a13046d7e1bf7/source/SelfHost%20(InMem%20with%20WS-Fed)/SelfHost/Config/RelyingParties.cs

The Identity Manager api is using OAuth2Configuration.

Would you help to with the mapping?

**Comment by zebamba** [comment]
I updated the code as follow:

<pre>
if (claim.Type == ClaimTypes.NameIdentifier && claim.Value != null)
{
  user.UserId = Guid.Parse(claim.Value);
}
</pre>

It works.

you can add any comment or please close the issue/question

**Comment by brockallen** [comment]
Not sure why updating to 2.0 would have changed that. The WS-Fed config you link might be a red herring.

**Comment by zebamba** [comment]
This is on another api that gets Data from my Auth Server (Token and Identity Provider).

it is System.Security.Claims class fro the principal 

And the claims is from ClaimsIdentity class.

**Comment by pawepaw** [comment]
After upgrading to newest IdentityServer3 v2.0.0, IdentityModel and IdentityServer Access Token validation I have similar problem. I no longer have sub claim while calling WebAPI and I have http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier instead.

Did anything changed? You did some mapping?

**Comment by zebamba** [comment]
I have my Token Server running apart.

On the My other application Web Api on the App_start or on my case it is SecurityConfig

I added this line

            #region Claims Transformation

            // Please refer to the link below for mode details about Claims Transformation:
            // http://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

            // Turn off Microsoft's JWT handler that maps claim types to .NET's long claim type names
            JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            // Adjust the configuration for anti-CSRF protection to the new unique sub claim type
            AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.Subject;

            #endregion

It Works for me.

**Comment by pawepaw** [comment]
Ok so it's caused by JwtSecurityTokenHandler.InboundClaimTypeMap this mapping yes? By default there is some map that turns sub claim into http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier ?

**Comment by pawepaw** [comment]
Digged into and i see this map. So by default it will map sub into name identifier.
     ``` {
        "sub",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"
      },```

It changed in new version of System.IdentityModel.Tokens.Jwt

**Comment by kcd83** [comment]
FYI Microsoft have fun on the way out too, outbound `"sub"` becomes `"nameid"` and both map inbound to `ClaimTypes.NameIdentifier`

In MVC 6 
```
	services.Configure<JwtBearerOptions>(options =>
	{
	...
		var validator = options.SecurityTokenValidators.OfType<JwtSecurityTokenHandler>().SingleOrDefault();

		// Turn off Microsoft's JWT handler that maps claim types to .NET's long claim type names
		validator.InboundClaimTypeMap = new Dictionary<string, string>();
		validator.OutboundClaimTypeMap = new Dictionary<string, string>();
	});
```

**Comment by nathan-alden** [comment]
Talk about shitty design... For some reason, Microsoft made those two properties **static** on the `JwtSecurityTokenHandler` class. That means each use of the class is not guaranteed to have the lists initialized properly because other code could be overwriting the values!

**Comment by brockallen** [comment]
> Talk about shitty design... For some reason, Microsoft made those two properties static on the JwtSecurityTokenHandler class.

Amen.

**Comment by plioi** [comment]
I'm trying to accomplish the same using Identity Server 4.

I rephrased the type map clearer to use "DefaultInboundClaimTypeMap" as suggested here: https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

    JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

That makes the claims come in as expected ("sub").

However, @zebamba 's code above also does the following,
        AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.Subject;

Some discussion of Identity Server 3 also claims that the AntiForgery change is required in combination with the clearing of the type map: http://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

I can't get that line to compile when using Identity Server 4:
     AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;

Are the AntiForgeryConfig and Constants part of Identity Server? If not, are they accessible to an MVC Core app?

**Comment by brockallen** [comment]
AntiForgery is a MVC5 feature.
