### ISSUE TITLE
Custom IViewService MVC Sample

### ISSUE THREAD

**Issue by ceastwood** [IdentityServer/IdentityServer3.Samples#174]
I just wanted to know if you would like me to submit a sample for an implementation of IViewService which uses bootstrap/mvc?

**Comment by brockallen** [comment]
If you have a open repo with it, we can link to it from our docs.

**Comment by ceastwood** [comment]
I will create one, I have a closed-source project where I worked through it
and felt I should offer a sample.

**Comment by leastprivilege** [comment]
we have a MVC view service sampe now
