### ISSUE TITLE
Internal Server Error when loading certificate from Certificate store

### ISSUE THREAD

**Issue by majhoos** [IdentityServer/IdentityServer3.Samples#176]
In Self-Host Project everything works perfectly fine when I use the default configuration and Cert.cs in particular however when I load the certificate from the Certificate Store using the following code :

     public static X509Certificate2 LoadFromStore()
       {
        var s = "‎‎600bc077f3494b38277ab640038ae61fb6bdd968"; // hardcoded for testing 

        var thumbprint = Regex.Replace(s, @"[^\da-zA-z]", string.Empty).ToUpper();
        var store = new X509Store(StoreName.Root, StoreLocation.LocalMachine);

        try
        {
            store.Open(OpenFlags.ReadOnly);

            var certCollection = store.Certificates;
            var signingCert = certCollection.Find(X509FindType.FindByThumbprint, thumbprint, false);
            if (signingCert.Count == 0)
            {
                throw new FileNotFoundException(string.Format("Cert with thumbprint: '{0}' not found in local machine cert store.", thumbprint));
            }

            return signingCert[0];
        }
        finally
        {
            store.Close();
        }
    }

I still manage to run the Host with no problem and browser doesn't complain either but on the client side I get Internal Server Error :

    {StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
    {
      X-SourceFiles: =?UTF-8?B?Rjpcc291cmNlXFJlZlwwNC0wNC0yMDE0XERpc3RyaWJ1dGVkUmVmZXJyYWxcSG9zdFxjb25uZWN0XHRva2Vu?=
      Date: Thu, 01 Oct 2015 11:41:22 GMT
      Server: Microsoft-IIS/10.0
      X-Powered-By: ASP.NET
      Content-Length: 8455
      Content-Type: application/json; charset=utf-8
    }}

To be more precise I managed to narrow down the problem to the RequestAsync method of the OAuth2Client :

        public async Task<TokenResponse> RequestAsync(Dictionary<string, string> form, CancellationToken cancellationToken = default(CancellationToken))
        {
            var response = await _client.PostAsync(string.Empty, new FormUrlEncodedContent(form), cancellationToken).ConfigureAwait(false);

            if (response.StatusCode == HttpStatusCode.OK || response.StatusCode == HttpStatusCode.BadRequest)
            {
                var content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                return new TokenResponse(content);
            }
            else
            {
                return new TokenResponse(response.StatusCode, response.ReasonPhrase);
            }
        }

If I use default certificate (the one which comes with the project) above code happily works and response.Status == HttpStatusCode.OK however when I load the certificate from the store as explained above it gets into the 

            else
            {
                return new TokenResponse(response.StatusCode, response.ReasonPhrase);
            }

with ResponsePhrase = 'Internal Server Error"'.

How can I capture what is going wrong on Host? I tried to play around with the inital setup to resolve the issue but no luck:

            var certificate = Certificate.LoadFromStore();

            var options = new IdentityServerOptions
            {
                SiteName = "Thinktecture IdentityServer3 (EntityFramework)",
                SigningCertificate = certificate,
                //SecondarySigningCertificate = certificate,
                Factory = Factory.Configure(connectionString)
                ,RequireSsl = true
                //Factory = InMemoryFactory.Create(
                //            users: Users.Get(),
                //            clients: Clients.Get(),
                //            scopes: Scopes.Get())

            };

            app.UseIdentityServer(options);

[Certificate is valid and is located inside Trusted Root Certificate of the same machine which both client and server are running]
[Both client and server are running with administrative privileges]

**Comment by leastprivilege** [comment]
As always - turn on logging.

**Comment by majhoos** [comment]
As you suggested I turned on logging and looked at the log and realized I was using keys less than 2048. Changed the key size of 4096 using "-len 4096" parameter and it works fine now.
Thanks Dominic,
