### ISSUE TITLE
Duplicate StandardScope.OpenId

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/IdentityServer3.Samples#177]
In the [ASP.NET Identity Sample](), there seems to be `StandardScope.OpenId` duplicated twice in the following [code](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/AspNetIdentity/WebHost/IdSvr/Scopes.cs#L29-L30).

                StandardScopes.OpenId,
                StandardScopes.OpenId,

Is there a reason for this? Or is this just an oversight?

**Comment by brockallen** [comment]
We accept PRs :)

**Comment by brockallen** [comment]
thanks
