### ISSUE TITLE
Further troubleshooting of Identity Manager New User, Roles and New Role not redirecting

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/IdentityServer3.Samples#179]
How can I further troubleshoot the issue of New User, Roles and New Role not redirecting in Identity Manager? I have based my code off of the [AspNetIdentity](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity), which is working correctly.

I have turned on logging with the following code.

```
            LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());
            Log.Logger = new LoggerConfiguration()
               .MinimumLevel.Debug()
               .WriteTo.Trace()
               .CreateLogger();
```

When I make the request in Postman, I can see the response, but I don't see anything in the browser.

Request
```
https://localhost:44300/admin/#/users/create
```

Response
```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>IdentityManager</title>
        <link href="/admin/assets/Content.Bundle.min.css" rel="stylesheet" />
        <link rel="icon" type="image/x-icon" href="/admin/assets/Content.favicon.ico" />
        <link rel="shortcut icon" type="image/x-icon" href="/admin/assets/Content.favicon.ico" />
    </head>
    <body lang="en" ng-app="ttIdmApp" ng-csp ng-controller="LayoutCtrl" ng-cloak>
        <div ng-include="'/admin/assets/Templates.navbar.html'"></div>
        <div class="container" ng-cloak>
            <ng-view tt-focus></ng-view>
        </div>
        <script id="model" type="application/json">
        {"PathBase":"/admin","ShowLoginButton":false,"oauthSettings":{"authorization_endpoint":"/admin/authorize","client_id":"idmgr"}}
    </script>
        <script src="/admin/assets/Scripts.Bundle.js"></script>
    </body>
</html>
```

However I haven't found anything useful in the logs. Is there something else that I can do to troubleshoot this?

**Comment by brockallen** [comment]
Is this an IdentityManager question, then (if so, wrong repo)? I'm a bit unclear on the exact issue, though.

**Comment by ryanvgates** [comment]
@brockallen I wasn't sure whether it belonged int the Identity Manager or the IdentityServer3.Samples since it came out of the sample project in IdentityServer3.Samples/source/AspNetIdentity.

The issue is that in Identity Manager when I click try to go into Identity Manager through the admin portion, like in [the sample](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/AspNetIdentity/WebHost/Startup.cs#L41-L51), the page will not load and there doesn't seem to be any errors either. I'm having trouble understanding where to go next to research the issue.

**Comment by brockallen** [comment]
RAMMFAR?

**Comment by ryanvgates** [comment]
@brockallen I was able to get it working when I set runAllManagedModulesForAllRequests(RAMMFAR) to true like below in the web.config.

```
<system.webServer>
   <modules runAllManagedModulesForAllRequests="true"/>
</system.webServer>
```

I was not getting any 404s from the HTTP request for the assets. 

Is there any logging that I can turn on in the future to help troubleshoot this or similar issues?

**Comment by brockallen** [comment]
Well, since the request wasn't being handled by the IdMgr middleware (or even Katana), it's hard to have to emit a log messaging saying you should have been invoked.

**Comment by ryanvgates** [comment]
@brockallen I see what you mean. Would IIS Express (since I'm in development) be handling the request then? Should I look into their logs?

**Comment by brockallen** [comment]
It should be returning the 404. I'm confused why you didn't see any 404s tho...

**Comment by ryanvgates** [comment]
@brockallen I agree. I am able to reproduce it by commenting it out RAMMFAR in the web.config for the example [AspNetIdentity](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNetIdentity).

**Comment by brockallen** [comment]
So we can close this issue?

**Comment by ryanvgates** [comment]
@brockallen Thank you for your help. Yes, this issue can be closed.

**Comment by ryanvgates** [comment]
For anyone else coming across this issue, RAMMFAR is covered in [the walk through videos](http://brockallen.com/2015/04/20/walk-through-videos-for-identitymanager/).
