### ISSUE TITLE
Where there is a database IdentityServer3.Samples example? 

### ISSUE THREAD

**Issue by sxlvalue** [IdentityServer/IdentityServer3.Samples#181]
Where have IdentityServer3.Samples databases? I use the Identity Asp.Net sample database not to work.

**Comment by brockallen** [comment]
For the ASP.NET ID sample it's relying upon EF auto creating the DB on first use. Also, it's using IdentityManager as a way to allow you to create users for testing.

**Comment by sxlvalue** [comment]
thank you very much.
