### ISSUE TITLE
Multi-Hop Delegation Example

### ISSUE THREAD

**Issue by KMC13** [IdentityServer/IdentityServer3.Samples#182]
Hi, 

I wondered if there were any Multi-Hop Examples around or if you had any pointers. I am basically trying to achieve the ADFS Identity Delegation scenario without Ws-Fed https://technet.microsoft.com/en-gb/library/dd807122.aspx.

I have an application that has multiple front end clients both .NET and Browser based, these call a WebAPI that then calls WCF/WebAPI's.

For example, 
Client -> WebService1 -> WebService2

Is this as simple as forwarding the access_token received by WebService1 to WebService2 and have them both using Bearer authentication with the Client asking for the scope for WebService1 and WebService2? Does this mean the client needs to ask for the scope for both WebServices?

**Comment by brockallen** [comment]
If you need each layer to have its own scope, but want to shield the client from knowing these details you could do something like act-as tokens. This would be done as a custom grant validator -- we have extensibility points for this (but no sample currently).

**Comment by leastprivilege** [comment]
But some documentation

**Comment by KMC13** [comment]
Thanks for the help. I got something working and much easier than I thought too.

So, the CustomGrantValidator looks like the following (it just takes one param the subject of the user to act as): 

```c#
class ActAsGrantValidator : ICustomGrantValidator
{
    private IUserService _users;

    public ActAsGrantValidator(IUserService users)
    {
        _users = users;
    }

    Task<CustomGrantValidationResult> ICustomGrantValidator.ValidateAsync(ValidatedTokenRequest request)
    {
        var param = request.Raw.Get("act_as_subject");
        if (string.IsNullOrWhiteSpace(param))
        {
            return Task.FromResult<CustomGrantValidationResult>(
                new CustomGrantValidationResult("Missing parameters."));
        }

        return Task.FromResult(new CustomGrantValidationResult(param, "act-as"));
    }

    public string GrantType
    {
        get { return "act-as"; }
    }
}
```

Then from the WebAPI in the middle which calls onto the next WebApi I just have the following:

```c#
TokenClient tokenClient = new TokenClient(
    "https://localhost:44333/connect/token",
    "WebApi1",
    "4B79A70F-3919-435C-B46C-571068F7AF37"
);

var caller = User as ClaimsPrincipal;

var customParams = new Dictionary<string, string>
{
    { "act_as_subject", caller.FindFirst("sub").Value }
};

var tokenResponse = tokenClient.RequestCustomGrantAsync("act-as", "WebApi2", customParams).Result;
```

As you can see WebApi1 is registered as a client in the IdSrv with Flow set to custom and AllowedCustomGrantTypes set to be act-as. 

This looks solid to me.

**Comment by brockallen** [comment]
Well, you're trusting the client of this endpoint to ask for tokens without any further proof. Normally when we use this technique the input is the access token. This can then be validated and the subject extracted from that.

**Comment by KMC13** [comment]
Arr yes, thanks, I thought maybe that because the client is already registered in the id server the identity server is already trusting the client at this point. But I can see the client could use this as a loophole to get any users account via there subject name which is not so good. 

So, slight change to pass in the access_token for the API as the param for the custom grant and then take the subject from that. So, the CustomGrantValidator looks like the following:

```c#
class ActAsGrantValidator : ICustomGrantValidator
{
    private TokenValidator _validator;

    public ActAsGrantValidator(TokenValidator validator)
    {
        _validator = validator;
    }

    Task<CustomGrantValidationResult> ICustomGrantValidator.ValidateAsync(ValidatedTokenRequest request)
    {
        var param = request.Raw.Get("token");
        if (string.IsNullOrWhiteSpace(param))
        {
            return Task.FromResult<CustomGrantValidationResult>(
                new CustomGrantValidationResult("Token parameter not set."));
        }

        var result = _validator.ValidateAccessTokenAsync(param).Result;
        if (result.IsError)
        {
            return Task.FromResult<CustomGrantValidationResult>(
                new CustomGrantValidationResult(result.Error));
        }

        var subjectClaim = result.Claims.FirstOrDefault(x => x.Type == "sub");
        if(subjectClaim == null)
        {
            return Task.FromResult<CustomGrantValidationResult>(
                new CustomGrantValidationResult("No subject claim for the token."));
        }

        return Task.FromResult(new CustomGrantValidationResult(subjectClaim.Value, "act-as"));
    }

    public string GrantType
    {
        get { return "act-as"; }
    }
}
```

And the middle tier WebAPI just passes its access token as the argument.

```c#

var customParams = new Dictionary<string, string>
{
    { "token", caller.FindFirst("token").Value }
};

```

**Comment by brockallen** [comment]
This would be a great sample or blog post that we'd happily link to from our docs.

**Comment by KMC13** [comment]
I don't have a blog unfortunately but I have put in a pull request instead with the sample #188.

**Comment by KMC13** [comment]
I don't have a blog unfortunately but I have put in a pull request instead with the sample #188.

**Comment by novikod** [comment]
Hi,

This example does not work with custom user service, for example AspId.
When I configure 

idSvrFactory.ConfigureUserService("AspId");

and after that register custom grant validator

idSvrFactory.CustomGrantValidators.Add(new Registration<ICustomGrantValidator>(typeof(ActAsGrantValidator)));

I can't find error but problem is with token validation.
All logging options are set to true.

var result = _validator.ValidateAccessTokenAsync(param).Result;

Validator never return a result.

Please help,

Igor

**Comment by chippiearnold** [comment]
I've had the same issue as novikod / Igor above - it works fine when using inmemory scopes and inmemory clients, but then I switched to using the EntityFramework nuget package and couldn't get ValidateAccessTokenAsync(param).Result to work.

Turns out it is because the entity framework calls are all using the async methods. After downloading the Core.EntityFramework source and debugging through I found that the call to `FindClientByIdAsync(string clientId)` in the ClientStore was never returning.

It seems the reason is that the line in the example CustomGrantValidator is blocking and so causes a deadlock.

After 2 days of debugging the simple fix is to change the line to:

`var result = Task.Run(() => _validator.ValidateAccessTokenAsync(param)).Result;`

**Comment by olonga** [comment]
Hi @KMC13, I have a situation where: 
a WebApp (with auth code flow) calls WebApi1 (custom flow) 
then WebApi1 calls WebApi2.
However, all calls need to happen on behalf of the original authenticated user. 
In other words, I could just examine the Authorization header and grab the access_token and pass it along.  However, I would like to properly use identity delegation scenario with a custom grant validator similar to the example from @KMC13 on multi-hop delegation.  
I see that you call WebApi1 from the consoleApplication client:
 var client = new TokenClient(
                "http://localhost:44333/connect/token",
                "ConsoleApplication",
                "F621F470-9731-4A25-80EF-67A6F7C5F4B8");
return client.RequestResourceOwnerPasswordAsync("bob", "secret", "WebApi1").Result;

Then, when the call arrives at WebApi1, there is a Claim called 'token' in the ClaimsPrincipal:
var caller = User as ClaimsPrincipal;
var customParams = new Dictionary<string, string>
{
         { "token", caller.FindFirst("token").Value }
};

This is what I am not understanding, how is consoleApplication client able to attach this 'token' claim in the ClaimsPrincipal object or how is WebApi1 able to see this new 'token' Claim in TestController.  In my application, I am not able to see this claim in the WebApi1? I can see the same claim via the authorization header.
