### ISSUE TITLE
Request for sample demonstrating the use of refresh tokens

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/IdentityServer3.Samples#185]
Can a sample be added that demonstrates the use of refresh tokens?

I couldn't find any in the samples that already exist. The [documentation](https://identityserver.github.io/Documentation/docsv2/advanced/refreshTokens.html) explains the process, but links to examples that don't include that functionality.

**Comment by brockallen** [comment]
Not sufficient? https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/ConsoleResourceOwnerRefreshTokenClient

**Comment by ryanvgates** [comment]
No that certainly covers it. Not sure how I missed it. Thank you for pointing me in the right direction.
