### ISSUE TITLE
Expired token (longer than 5min) is validating

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer3.Samples#186]
I am using the MVC OWIN Hybrid sample.  I have my id and access token set to 5min in the IDSvr.  

When 10+ (even 60+) minutes have gone by, User.Identity.IsAuthenticated == true.  How?

To prove things are expired, I then pull the access token out (from the Auth cookie, re: mvc sample) and call the Sample Service, and I get a 401 as expected. 

Why does the MVC app not do the same, and reflect User.Identity.IsAuthenticated == false?

**Comment by leastprivilege** [comment]
The lifetime of the id_token is not related to the length of the authentication session in your client.

You set a cookie in your client - the parameters of its lifetime is up to your client app (you can synchronize their lifetime using the UseTokenLifetime setting on the OIDC MW).

**Comment by dapug** [comment]
ok, interesting.  I may have misunderstood what was being "validated".  It sounds like the AuthCookie was "valid" but it is not parsing and verifying the id_token OnAuthentication()?

Anyway, I'll sync as suggested, thx.
