### ISSUE TITLE
Update Custom User Service reference to IdentityServer3

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/IdentityServer3.Samples#187]
The [Custom User Service sample](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/CustomUserService) currently has [a custom nuget source](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/NuGet.config#L4) and [a reference to a build specific version of IdentityServer3 in packages.config](https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/CustomUserService/packages.config#L5). I think we should update it to use the latest release version [2.0.2](https://www.nuget.org/packages/IdentityServer3/) which will get rid of the nuget.config file that is needed to add the custom nuget source. 

What do you think?

**Comment by brockallen** [comment]
All samples always use the myget builds -- it's just easier for us to work that way. To make it easy for folks such as yourself to compile these projects we pin certain versions of the binaries on myget to ensure you can restore. 

Are you having a problem restoring?

**Comment by ryanvgates** [comment]
No it worked just fine. I just wasn't sure if it was necessary, but changing it isn't worth it if it would the dev process for your team.
