### ISSUE TITLE
Bug in error logging within configureAutoRenewToken()

### ISSUE THREAD

**Issue by pinnprophead** [IdentityServer/IdentityServer3.Samples#189]
configureAutoRenewToken() function contains 

console.error(console.error(e.message || e);

In some cases e is undefined, so an error is thrown 
"Uncaught (in promise) TypeError: Cannot read property 'message' of undefined(…)"

Suggest:
                    var msg = 'unknown error in renewTokenSilentAsync()';
                    if (e) {
                        if (e.message) {
                            msg = e.message;
                        } else { 
                            msg = e;
                        }
                    }
                    console.error(msg);

Or something that protects e being undefined.

console.error(e ? (e.message ? e.message : e) : 'unknown error in confugureAutoRenewToken()');
 
would be the shortest version.

PS: I encountered this situation (of an empty error object) when attempting to renew access token using the javascript implicit client, and the "silent_renew.html" page was not specified as a valid callback url in identityServer.

**Comment by brockallen** [comment]
Is this in the callback in the html or in the JS library itself?

**Comment by pinnprophead** [comment]
It is about line 829 in oidc.js -- function configureAutoRenewToken(mgr)

**Comment by brockallen** [comment]
Moved to the oidc-client repo.
