### ISSUE TITLE
User registration & identityToken

### ISSUE THREAD

**Issue by wrustel** [IdentityServer/IdentityServer3.Samples#196]
Hi everyone,

I am trying to configure my identity server mapping both points admin and identity.

when I access to my admin point via browser (.../admin) I can get the default admin console made in angularJs. I want to customize this admin "console" and restrict its access because now, you dont need any kind of loggin to work on it, I means, there is a loggin button but never need credentials.

picture 1: https://gyazo.com/6f22f12002a5fe7e19ddc8113ac24fdc

Picture 2: https://gyazo.com/a845b70449c2435914e9afc09a7dd823

Also I would like to know how can I do a signup's form for users (typical user form registration). 

Second question:

When I call from my console client to my identity server for get any user access token I can see the scopes and claims(role,email,user_name,etc) relationated:

Picture 3: https://gyazo.com/7a29fdbd699c5cd2aa273c7aef63ad02

But I never get in any case the IdentityToken or the right claims.
Here is how I do my token endpoint call:

        static TokenResponse RequestToken()
        {
            
            return _tokenClient.RequestResourceOwnerPasswordAsync("paco", "123456", "openid roles offline_access profile").Result;
            //return client.RequestClientCredentialsAsync("read openid").Result;
        }

My client configuration via json:

 {
          "Enabled": true,
          "ClientId": "demo-webapi",
          "ClientName": "Demo Web Api",
          "ClientUri": "https://localhost:44306/",
          "Flow": "ResourceOwner",
          "ClientSecrets": [
            { "Value": "sha256:C893EA72-CA50-475E-BC55-161D1557FE5F" }
          ],
          "RequireConsent": true,
          "AllowedScopes": [
            "openid",
            "profile",
            "roles",
            "offline_access",
            "demo-webapi"
          ],
          "AccessTokenType": "JWT",
          "AccessTokenLifetime": 3600
        }

My profile scope configuration via json:

  "Name": "profile",
            "DisplayName": "User profile",
            "Required": true,
            "Type": "Identity",
        "Claims": [          
          {
            "Name": "sub",
            "AlwaysIncludeInIdToken": true
          },
          {
            "Name": "Profesion",
            "AlwaysIncludeInIdToken": true
          },
          {
            "Name": "dni",
            "AlwaysIncludeInIdToken": true
          }
        ]
 {
          "Enabled": true,
          "ClientId": "demo-webapi",
          "ClientName": "Demo Web Api",
          "ClientUri": "https://localhost:44306/",
          "Flow": "ResourceOwner",
          "ClientSecrets": [
            { "Value": "sha256:C893EA72-CA50-475E-BC55-161D1557FE5F" }
          ],
          "RequireConsent": true,
          "AllowedScopes": [
            "openid",
            "profile",
            "roles",
            "offline_access",
            "demo-webapi"
          ],
          "AccessTokenType": "JWT",
          "AccessTokenLifetime": 3600
        }

My profile scope configuration via json:

  "Name": "profile",
            "DisplayName": "User profile",
            "Required": true,
            "Type": "Identity",
        "Claims": [          
          {
            "Name": "sub",
            "AlwaysIncludeInIdToken": true
          },
          {
            "Name": "Profesion",
            "AlwaysIncludeInIdToken": true
          },
          {
            "Name": "dni",
            "AlwaysIncludeInIdToken": true
          }
        ]

I can get only the claims if I do calls to the end point .../connect/userinfo but I dont want to do this every time that I need any user information, it's pointless do this call from my resource server. If I am not wrong this claims and info should be in my identity token, but I dont know how to get it.

thanks in advance.

**Comment by brockallen** [comment]
To configure security for IdentityManager, check the IdentityManager repo and samples: https://github.com/IdentityManager/IdentityManager/

For for claims in the id_token and access_token, this depends on how you configure the type of scopes. Check the scope docs or the and the issue tracker history as this has been asked before many time. Also, there is no identity token with resource owner password flow.

**Comment by wrustel** [comment]
Thank you for your quickly response but I can't still customice my admin end point, I did something like this:


     app.Map("/identity", id => {                
                var factory =  new IdentityServerServiceFactory().Configure(connectionString);
                factory.ViewService = new IdentityServer3.Core.Configuration.Registration<IViewService>(typeof(CustomViewService));

                id.UseIdentityServer(new IdentityServerOptions {
                    SiteName = "Demo Identity Server",
                    IssuerUri = (string)ConfigurationManager.AppSettings["options.issuerUri"],                  
                    Factory = factory,                    
                    SigningCertificate = LoadCertificate(),                    
                });                
            });

            app.Map("/admin", adminApp => {
                var factory = new IdentityManagerServiceFactory().Configure(connectionString);              
                adminApp.UseIdentityManager(new IdentityManagerOptions() {
                    Factory = factory
                });
            });
           
The /identity/permissions end point works well and can do my custom view, but there isn't any ViewService for the IdentityManager ServiceFactory doing this uncustomized. Also the admin panel only works for clients CRUD In memory but I didn't find any way to work on entity framework yet.

Kind regards.

**Comment by leastprivilege** [comment]
closing - feel free to re-open if necessary.
