### ISSUE TITLE
No 'Access-Control-Allow-Origin' - endsession endpoint - IdentityServer3 - 2.2.1

### ISSUE THREAD

**Issue by InnovaSmart** [IdentityServer/IdentityServer3.Samples#198]
Hello,

I have setup a Javascript Client with a button that calls the endsession endpoint on the Authority url. 
I'm getting this error. 

XMLHttpRequest cannot load https://localhost:44302/core/connect/endsession?post_logout_redirect_uri=ht…/localhost:44300/index.html&id_token_hint=f4c519696f16ae4659a88c624a6f7e1f. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:44300' is therefore not allowed access.

I have configured cors 2 different ways and it hasn't resolved the issue. Additionally, I've configured the Clients CorsOrgin property as well.

I am able to Get a Token "redirect and login" then redirect back.
I'm able to Use the Token on a Resource endpoint.

Not sure why endsession is not working. I want to call endsession without a redirect.

```javascript
        function endsession() {
            var endSessionUrl = 'https://localhost:44302/core/connect/endsession';
            var post_logout_redirect_uri = 'https://localhost:44300/index.html';
            var state = Date.now() + "" + Math.random();

            localStorage["state"] = state;

            //var url =
            //    endSessionUrl + "?" +
            //    "id_token_hint=" + encodeURI(token) + "&" +
            //    "post_logout_redirect_uri=" + encodeURI(post_logout_redirect_uri) + "&" +
            //    "state=" + encodeURI(state);

            var url =
                endSessionUrl + "?post_logout_redirect_uri=" + encodeURI(post_logout_redirect_uri);
            url += "&id_token_hint=" + encodeURI(token);

            var xhr = new XMLHttpRequest();
            xhr.onload = function (e) {
                if (xhr.status >= 400) {
                    show({
                        status: xhr.status,
                        statusText: xhr.statusText,
                        wwwAuthenticate: xhr.getResponseHeader("WWW-Authenticate")
                    });
                }
                else {
                    show(JSON.parse(xhr.response));
                }
            };
            xhr.onerror = function (e) {
                console.log(e, xhr);
                show({ error: "unknown http error" });
            };
            xhr.open("GET", url, true);
            xhr.setRequestHeader("Authorization", "Bearer " + token);
            xhr.send();
        }

**Comment by InnovaSmart** [comment]
Client Setup.

                new Client // Just the Default - Only for LocalHost Sample Only
                {                    
                    ClientName = "Sample",
                    Enabled = true, 
                    ClientId = "SampleClientImplicit",
                    Flow = Flows.Implicit,
                    AllowedScopes = new List<string>
                    {      
                        Constants.StandardScopes.AllClaims,
                        Constants.StandardScopes.Address,
                        Constants.StandardScopes.OpenId,
                        Constants.StandardScopes.Roles,
                        Constants.StandardScopes.Profile,
                        Constants.StandardScopes.Email,
                        Constants.StandardScopes.OfflineAccess,
                        "sample"
                    },

                    RequireConsent = false,
                    RedirectUris = new List<string> 
                    {
                        "https://localhost:44300/index.html",  
                    },

                    PostLogoutRedirectUris = new List<string> 
                    {
                        "https://localhost:44300/index.html", 
                    },
                    AllowedCorsOrigins = new List<string>{
                        "https://localhost:44300"
                    },
                    //LogoutUri = "https://localhost:44300/index.html",
                    IdentityTokenLifetime = IdentityTokenLifetime,
                    AccessTokenLifetime = AccessTokenLifetime,
                    AccessTokenType = AccessTokenType.Reference
                },

Authority Server Setup
            app.Map("/core", core =>
            {
                var idSvrFactory = new IdentityServerServiceFactory();
                idSvrFactory.ConfigureUserService(ConnectionStringName);
                idSvrFactory.UseInMemoryClients(Clients.Get()); 
                idSvrFactory.UseInMemoryScopes(Scopes.Get()); 
                //idSvrFactory.CorsPolicyService = new IdentityServer3.Core.Configuration.Registration<ICorsPolicyService>(resolver => new DefaultCorsPolicyService() { AllowAll = true, AllowedOrigins = new []{ "https://localhost:44300"}});

                idSvrFactory.CorsPolicyService = new IdentityServer3.Core.Configuration.Registration<ICorsPolicyService>(new InMemoryCorsPolicyService(Clients.Get()));

                idSvrFactory.ConfigureClientStoreCache();
                idSvrFactory.ConfigureScopeStoreCache();
                idSvrFactory.ConfigureUserServiceCache();

                var options = new IdentityServerOptions
                {
                    SiteName = "Authority", 
                    SigningCertificate = Certificate.Get(),
                    Endpoints = new EndpointOptions()
                    {
                        EnableCspReportEndpoint = true,
                        EnableAuthorizeEndpoint = true,
                        EnableTokenRevocationEndpoint = true,
                        EnableEndSessionEndpoint = true,
                        EnableCheckSessionEndpoint = true,
                        EnableUserInfoEndpoint = true,
                        EnableDiscoveryEndpoint = true,
                        EnableTokenEndpoint = true,
                        EnableIdentityTokenValidationEndpoint = true,
                        EnableClientPermissionsEndpoint = true,
                        EnableAccessTokenValidationEndpoint = true,
                        EnableIntrospectionEndpoint = true
                    },
                    Factory = idSvrFactory,
                    RequireSsl = true,
                    SecondarySigningCertificate = null 

                };

                core.UseIdentityServer(options);
            });

**Comment by InnovaSmart** [comment]
If I add this to the Authority web.config, then it stops the error.

    <httpProtocol>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
        <add name="Access-Control-Allow-Methods" value="GET, POST, OPTIONS, PUT, DELETE" />
      </customHeaders>
    </httpProtocol>

**Comment by leastprivilege** [comment]
IIRC we did not design the end session endpoint to be called by AJAX. If you think this is an oversight - please open an issue in the main repo.
