### ISSUE TITLE
Debugging Customer service and Core Module from Identity server master sln

### ISSUE THREAD

**Issue by lpranith** [IdentityServer/IdentityServer3.Samples#199]
I had couple of issues,

first: was not able to build the customer service project , since nuget always showed ,it could not find the package or could not download it. So copied the dlls from the Core module and modifed web.config and packages.config accordingly made it to run. 

But now 

I wanted to debug the customer service module and core to get familiar with the flow. I am trying to include the LocalRegistration service to the Core where the identity server is been implemented.
 I could successfully host the server. So before authentication ,Registration(I need the local user registration) page should be seen. I did mention the start page in the properties of the customer service project properties. But i still get the error"HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory. "
 Any suggestion would help.

Thanks

**Comment by leastprivilege** [comment]
I don't follow. feel free to re-open (maybe rather on core than here).
