### ISSUE TITLE
AspNet5 - AspNetIdentity sample

### ISSUE THREAD

**Issue by Cybrosys** [IdentityServer/IdentityServer3.Samples#201]
Hi,

I'm trying to wrap my head around IdentityServer3 and ASP.NET 5 at the same time (might not be the best idea haha). I would love to have a sample project that demonstrates the AspNetIdentity provider for IdentityServer3 in ASP.NET5. Maybe i'm just over complicating things and it's easy to set up using the pre-existing ones. The other examples are however a bit intimidating because they also set up a IdentityManager(?) and I don't know how that fits in.

**Comment by brockallen** [comment]
I don't think IdMgr will work with AspId3.
