### ISSUE TITLE
Authorization code flow problem

### ISSUE THREAD

**Issue by kbrekke** [IdentityServer/IdentityServer3.Samples#202]
I'm testing the authorization code flow, and I'm experiencing an issue. I can see that the authorization code is posted back to my client, but the AuthorizationCodeReceived notification is not triggered. The MessageReceived notification is triggered, and I can pull the authorization code out of the post data.

I have looked at your manual implementation in the samples, but I'd like to avoid as many manual steps as possible, and rather make it work like your hybrid flow sample.

Here is the request that's being sent to the authorize endpoint:

https://localhost:44300/identity/connect/authorize?client_id=mvcAuthCode&redirect_uri=https%3a%2f%2flocalhost%3a44303%2f&response_mode=form_post&response_type=code&scope=openid+profile+read+write+offline_access&state=the_state&nonce=the_nonce

Here is the relevant code in Startup.cs:

```
JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationType = "Cookies"
});

app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
    ClientId = "mvcAuthCode",
    Authority = AuthorityConstants.BaseAddress,
    RedirectUri = "https://localhost:44303/",
    PostLogoutRedirectUri = "https://localhost:44303/",
    ResponseType = "code",
    Scope = "openid profile read write offline_access",

    SignInAsAuthenticationType = "Cookies",

    Notifications ...
```

Any clues? Maybe the problem is the post back to my client. Maybe the authorization code should be in the querystring, with a get in stead of post to my client? If so, how do I configure it?

**Comment by kbrekke** [comment]
I have intercepted the redirect to the IdentityServer, removing the response_mode, which resulted in a get redirect to my client, with the authorization code in the querystring. Still, the AuthorizationCodeReceived notification is not triggered.

**Comment by leastprivilege** [comment]
seems like a problem with the MS middleware. would need to do some more tests myself. feel free to re-open when you made progress / have more questions

**Comment by akamud** [comment]
Was this ever solved? I have the same behavior. 

The problem with using `MessageReceived` is that retrieving the fields is not as trivial. For example: I'm still looking for the `sid` field.
