### ISSUE TITLE
using identityserver in asp.net 5 mvc 6 + angularJS + asp.net 5 web api

### ISSUE THREAD

**Issue by stombeur** [IdentityServer/IdentityServer3.Samples#203]
Hi, I made an addition to the asp.net 5 sample here
https://github.com/stombeur/IdentityServer3.Samples/tree/master/source/AspNet5/src/MvcAngularClient

I'm combining identityserver and asp.net 5 mvc 6 with angularjs and typescript. Logging in is done in the asp.net page, but the angularjs app needs to call an asp.net web api that is also secured with identityserver.

My current approach is to fetch the user's access_token on resolve of the angular route by calling an asp.net MVC controller (in the same site) and storing the access_token in a variable (because I could not yet figure out how to use oidc tokenmanager).

Is this the right approach? Is there a danger to storing the access_token in the angular app?

If you like the sample I can create a pr for it.

**Comment by leastprivilege** [comment]
thanks! let's talk again once asp.net 5 is released. too much beta code right now.

**Comment by lewis-almeyda** [comment]
I had the same idea but I guess I'm looking to validate the concept, with my app, I would create an MVC page(regardless of the MVC version) used for the login in the user against an private api + identity server, then most of the client interaction with the resource api(serving the application data) would be done via angular http calls, that would need to include the token. I've seen examples of that tokek included in browsers local storage.

Is this a good security model? How can I find holes in it? What about CSRF attacks?
Thanks in advance

**Comment by stombeur** [comment]
you should also look at oidc-token-manager https://www.npmjs.com/package/oidc-token-manager
also by @brockallen 
I changed my implementation to login via angular instead of MVC. It makes it easier to also check for authentication (is user logged in) and check claims in angular.
