### ISSUE TITLE
Authenticating from a NodeJS/Express app

### ISSUE THREAD

**Issue by mithun-daa** [IdentityServer/IdentityServer3.Samples#207]
I have IdSrv3 set up and I am able to authenticate users to my ASP.Net MVC app just fine. However, when I am trying to authenticate users of my NodeJS application, I keep getting redirected back to my call back with `#error=invalid_request` in the request to my callback. I am using PassportJS for authentication and I am using (passport-openidconnect)[https://github.com/jaredhanson/passport-openidconnect] strategy. 
Here are the network requests:
![image](https://cloud.githubusercontent.com/assets/852171/11984828/6fbdfc34-a984-11e5-8b5e-ac44fed9e22d.png)

When I try to access a protected resource from my ASP.Net MVC app I see that the request to the `authorize` url on my IdSrv has an additional query string parameter and looks like this:
````
&state=OpenIdConnect.AuthenticationProperties=CHVe1uECk3BbDIC7l_3wOOuybrGQ8e863jnwI8OZZomfvpsQTd26NTmZwM5X0R3j3AgCh1U4h6DaVPbIljtudJZ7lOGMA7xC-SdCHWHj06o625CCJ5KLEI8H6k4_FBFp8xdYmfeF7hS3yeBsBaRtbaeFa_bNPDNuNT8U0vUBZvzGmHcBOmoYbGZmnRwMpWqb0HOjKtTruQLBNn7A897FfQ&nonce=635864961265352867.MTdlODk3ODEtODAxOS00ZTM5LTg1MWUtNDU4Y2JmYTQxOWFjZDA0YTYxMDQtMzlhZi00NDUzLWFlY2QtMTRjZDk0OWY0ZjBm
````
This query string param is missing when my node app is trying to authenticate a user. Is this query string parameter necessary and if it is is there anyway I can build it by hand so that I can tack it to my request?

**Comment by leastprivilege** [comment]
thats the wrong repo. Use core.

But as always - first check the logs.

**Comment by mithun-daa** [comment]
But my ASP.Net application works just fine? Also, how and where do I check the logs? Which repo are you talking about? If this is not the best place to ask Qs i can ask on stackoverflow.

**Comment by brockallen** [comment]
I think he means check the IdSvr logs.

**Comment by mithun-daa** [comment]
Do i need to turn on the logs? How do i see the IdSrv logs?

**Comment by brockallen** [comment]
Check the docs for how to enable logging.

**Comment by mithun-daa** [comment]
:+1: 
Here is what the log spat out:
````
iisexpress.exe Information: 0 : 2015-12-24 09:02:44.490 -06:00 [Information] Start authorize request
iisexpress.exe Information: 0 : 2015-12-24 09:02:44.494 -06:00 [Information] Start authorize request protocol validation
iisexpress.exe Error: 0 : 2015-12-24 09:02:44.522 -06:00 [Error] "Nonce required for implicit and hybrid flow with openid scope"
 "{
  \"ClientId\": \"mvc\",
  \"ClientName\": \"MVC Client\",
  \"RedirectUri\": \"http://localhost:3000/callback\",
  \"AllowedRedirectUris\": [
    \"http://localhost:3000/callback\"
  ],
  \"SubjectId\": \"unknown\",
  \"ResponseType\": \"id_token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid\",
  \"Raw\": {
    \"response_type\": \"id_token\",
    \"client_id\": \"mvc\",
    \"redirect_uri\": \"http://localhost:3000/callback\",
    \"scope\": \"openid\"
  }
}"
iisexpress.exe Information: 0 : 2015-12-24 09:02:44.527 -06:00 [Information] {
  "Category": "Endpoints",
  "Name": "Endpoint failure",
  "EventType": "Failure",
  "Id": 3001,
  "Message": "invalid_request",
  "Details": {
    "EndpointName": "authorize"
  },
  "Context": {
    "ActivityId": "00000000-0000-0000-e502-0080060000ff",
    "TimeStamp": "2015-12-24T15:02:44.5252844+00:00",
    "ProcessId": 18980,
    "MachineName": "MPATEL-787",
    "RemoteIpAddress": "::1"
  }
}
iisexpress.exe Information: 0 : 2015-12-24 09:02:44.528 -06:00 [Information] End authorize request
iisexpress.exe Information: 0 : 2015-12-24 09:02:44.532 -06:00 [Information] Redirecting to: http://localhost:3000/callback#error=invalid_request
````

**Comment by brockallen** [comment]
So now you have your answer.

**Comment by mithun-daa** [comment]
Sweet!!!! that did it. Thank you!
