### ISSUE TITLE
Importing Existing Membership tables data to AspNetIdenity Sample Tables

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#209]
We have an application that currently uses Microsoft membership tables. I've seen that it's possible to import data from membership tables to Identity tables. If I use something just like the AspNetIdentity sample as my IdentityServer and import the data, will the old passwords work in the new IdentityServer?

**Comment by brockallen** [comment]
That's a question for Microsoft.
