### ISSUE TITLE
No security for the admin url of AspNetIdentity sample?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#210]
I ran the AspNetIdentity sample. https://localhost:44333/admin url is the admin page. In a production environment the public would have access to that page which wouldn't be good. Could somebody please explain to me how that can be secured?

**Comment by brockallen** [comment]
This endpoint is provided in the sample and it's using IdentityManager. Check that repo for more info.

**Comment by farzad99** [comment]
OK, thanks
