### ISSUE TITLE
ASP.NET 5 MVC Client Hybrid Example

### ISSUE THREAD

**Issue by jimnorth55** [IdentityServer/IdentityServer3.Samples#212]
The ASP.NET 5 Examples have been very helpful, but they don't include a Hybrid flow example for an MVC client.  With the changes to the OpenIdConnect middleware, I am having difficulty translating the Startup.cs code in the MVC Owin Client (Hybrid) example.   Can you point me to an example?  Thanks.

**Comment by brockallen** [comment]
This is a MVC hybrid sample client: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MVC%20OWIN%20Client%20%28Hybrid%29

Is this not what you're looking for?

**Comment by jimnorth55** [comment]
I was looking for some guidance in translating the OWIN sample you
referenced to ASP.Net 5 ( pardon... ASP.Net Core 1.0).  Perhaps all the
required pieces are not available as yet?

**Comment by brockallen** [comment]
The OIDC MW in ASP.NET Core does many of those addition steps that the OIDC MW did not do in Katana. IOW, it exchanges the code for token(s) and accesses the user profile endpoint.
