### ISSUE TITLE
Simplest OAuth2 workflow does not work for Resource Owner

### ISSUE THREAD

**Issue by aseemflowingly** [IdentityServer/IdentityServer3.Samples#215]
The code below from the Main method in Client => Program.cs works fine:

           var response = GetClientToken();
           CallApi(response);

Output:

![image](https://cloud.githubusercontent.com/assets/16090447/12133244/4e6add9a-b488-11e5-9203-eab71190ee59.png)

But when calling:

          response = GetUserToken();
          CallApi(response);

It comes back with response of "Not Found"

Screenshot:
![image](https://cloud.githubusercontent.com/assets/16090447/12133229/2b832b02-b488-11e5-9e27-4decdd0d4ef8.png)

**Comment by leastprivilege** [comment]
Maybe some URL is wrong - hard to tell.

**Comment by aseemflowingly** [comment]
Yes, apparently, the URL was pointing to "core/token" instead of "connect/token" for get user token.
