### ISSUE TITLE
Where should user settings page go in  IdSvr3 app based on "AspNetIdentity_2fa" sample?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#217]
My IdSvr3 application is based on the "AspNetIdentity_2fa" sample. I'd like to have a page that lets user change his accounts settings, for example, enable or disable 2FA, change phone number, etc. Of course, the user has to be first authenticated to have access to this page. Where should this page go? In my IdSvr3 application, or one of the client applications that uses  IdSvr3 application for authentication, or another application?

**Comment by brockallen** [comment]
This would just be a client app of IdSvr that can access the user database.

**Comment by farzad99** [comment]
Good, thanks
