### ISSUE TITLE
Letting user pick between phone or email 2fa in "AspNetIdentity_2fa" sample based application?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#218]
I'm just looking for some general guidance on how to go about implementing the following feature. I have an IdSvr3 application based on the "AspNetIdentity_2fa" sample. If the user has 2fa enabled and has an email and a phone number I'd like to show him a page that lets him choose between sending the code to either phone or email. What's the general approach of showing a page in between the initial login page and the page that let's user enter the code sent to him?

**Comment by brockallen** [comment]
To take over the UI workflow from the user service you return a partial login. You can send the user to as many pages as you want before returning back into IdentityServer.

**Comment by farzad99** [comment]
OK, thank you. I have to look into a partial login. As soon as I figure that out I'll close this issue.
