### ISSUE TITLE
HTML Customization

### ISSUE THREAD

**Issue by mlunn01** [IdentityServer/IdentityServer3.Samples#219]
The documentation for this repository is excellent. In the docs, it explains very clearly that you can override the layout or partial views that are generated by the ViewService by simply adding a templates folder to the root of your hosting application. I've forked the repo, and have loaded the following project: IdentityServer3.Samples/source/AspNet5/src/AspNet5. I added a templates folder to the IdentityServer project root with a customized login.html file. However, when reloading the IdentityServer WebApp the embedded login page is still being served. Any guidance on how to serve the customized login page would be greatly appreciated.

**Comment by brockallen** [comment]
The HTML files are cached by default -- you probably want to disable the cache during development. It's a flag on the default view service options. You can do this in onw of two ways:

```
factory.ConfigureDefaultViewService(new DefaultViewServiceOptions
{
    CacheViews = false
});
```
or 
```
factory.ViewService = new DefaultViewServiceRegistration(new DefaultViewServiceOptions
{
    CacheViews = false
});
```
