### ISSUE TITLE
Please support Mono, at least support it for one MVC client in samples

### ISSUE THREAD

**Issue by abelondev** [IdentityServer/IdentityServer3.Samples#223]
Is there any configuration to make Single-Sign On on mono using IdentityServer3. I don't have Windows computer to use Microsoft itself. Make one sample mvc server/client which can be run on Mono with right settings.

Now I am stuck on: 
"Could not load type 'Microsoft.IdentityModel.Tokens.Saml2SecurityTokenHandler' from assembly 'Microsoft.IdentityModel.Protocol.Extensions, Version=1.0.2.33, Culture=neutral, PublicKeyToken=31bf3856ad364e35'."

when I run "MVC Owin Client Implicit" sample

**Comment by seburgi** [comment]
I would also be very interested in a mono sample.

**Comment by leastprivilege** [comment]
You can try porting this to Mono:

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MvcFormPostClient
