### ISSUE TITLE
Two Factor Remember Browser Cookie Question

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#224]
In Microsoft ASP.NET individual accounts authentication the user is given the option to skip the second step of two factor verification on the device where he logged in from. I'm using IdSvr3 "AspNetIdentity_2fa" sample. What would be the approach to add that feature to the IdSvr3 "AspNetIdentity_2fa" sample?

The following is from the Startup class of a MVC5 project that uses individual user account authentication:

        // Enables the application to remember the second login verification factor such as phone or email.
        // Once you check this option, your second step of verification during the login process will be remembered on the device where you logged in from.
        // This is similar to the RememberMe option when you log in.
        app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);

**Comment by brockallen** [comment]
Put that MW in the pipeline and check it wherever you need to (in the user service, mainly). You can inject the OWIN environment into your ctor in the user service.

**Comment by farzad99** [comment]
Thank you @brockallen. 

In the Startup class of the WebHost project of the IdSvr3 "AspNetIdentity_2fa", I can place the following line:

`app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);`

which of course places the middleware in the pipeline. In the Microsoft code for local user account authentication they set the cookie using:

`
var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent:  model.RememberMe, rememberBrowser: model.RememberBrowser);
`

so I think something like that would interfere with the cookies that IdSvr3 generates or the IdSvr3 operation in general.

So could you please shed some light on this? Is there another way to set that cookie?

**Comment by brockallen** [comment]
It's just another cookie middleware with a diff name -- they should not conflict.

**Comment by farzad99** [comment]
OK, thank you.
