### ISSUE TITLE
Why two authentication middlewares?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#226]
So in the Startup class of my MVC application I have:

```
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://localhost:44340/core",

                ClientId = "PPSUsers",
                ResponseType = "id_token",
                RedirectUri = "https://localhost:44322/",

                SignInAsAuthenticationType = "Cookies",

            });

```

It works. But I don't understand why the first middleware is needed. I'd appreciate if somebody could explain how the two middlewares work together? I'm just trying to get a better understanding of the process.

**Comment by brockallen** [comment]
OIDC sends a token to the MVC app to authenticate the user. This happens once. You'd not want it to happen on each request into the MVC app, so the MVC app takes the token and issues a cookie to then represent the user. This is standard security when dealing with external authentication.

**Comment by farzad99** [comment]
OK, thank you
