### ISSUE TITLE
Signing in an already authenticated user with updated claims without having user login again

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#228]
I'm using "AspNetIdentity_2fa" sample as my IdSvr (IdSvr from this point on), I have another MVC project that's used to register users and handle user account settings such as changing email, etc (mvcApp from this point on). To make changes to his account settings the user is authenticated by the IdSvr. When the user changes his email or phone number I'd like to sign in the user again without logging out the user and having him re enter his user name and password on the IdSvr login page again. How can I accomplish that? 

If I use the following line which causes the cookie authentication middleware to generate a new authentication cookie for the user in the mvcApp, will the IdSvr know that it's the same user that it logged in before?

`AuthenticationManager.SignIn(await user.GenerateUserIdentityAsync(UserManager));`

**Comment by brockallen** [comment]
> will the IdSvr know that it's the same user that it logged in before?

Yes, since IdSvr uses its own authentication cookie and that cookie will most likely only have the user's subject and name claims (not email, for example).

**Comment by farzad99** [comment]
OK, thank you.
