### ISSUE TITLE
Why got Error 401.0 when I use mvc authentication follow samples?

### ISSUE THREAD

**Issue by sPhinX-LHJ** [IdentityServer/IdentityServer3.Samples#229]
First I want  to say IdentityServer is aweome, Thank you guys!

Now I want integrate identityserver in my MVC project, at first i create a mvc project(like mvc authentication sample), then create second web project for Identityserver(like js application sample). So I got 2 project now, I try everything but when I click the about link(like mvc authentication sample), web page always got "HTTP Error 401.0 - Unauthorized" error. Then I try the slefhost, mvc authentication and js ahthentication sample by myself (I create above samples from scratch follow document instruction), these newly-created sample worked. I don't know what's wrong with my MVC client, somebody can give some advice or a worked sample which mvc client and IdentityServer seperated into 2 project not like MVC authentication sample?

BTW: The newly-created IdentityServer web project is worked, I can use discovery endpoint to get config information, so I think this is not a IdentityServer problem.

**Comment by brockallen** [comment]
Sounds like something in your app -- i'd compare yours to the working samples.

**Comment by sPhinX-LHJ** [comment]
Sorry for the late response.

Today i re-create the project, now the project worked after solved one 404 error.

I found that app.map function not point to the map path when identityserver is hosted in sperated project from mvc project.
for example, when I UseIdentityServer like below, the identityserver still runing on https://localhost:44300/, not https://localhost:44300/identity.
Is this a issue? I am newbie at mvc, also plz forgive my poor english.
BTW: I know the meaning of your avatar pic, because chinese is my mother language, haha.

            app.Map("/identity", idsrvApp =>
            {
                app.UseIdentityServer(new IdentityServerOptions
                {
                    SiteName = "Embedded IdentityServer",
                    SigningCertificate = LoadCertificate(),

                    Factory = new IdentityServerServiceFactory()
                                    .UseInMemoryUsers(Users.Get())
                                    .UseInMemoryClients(Clients.Get())
                                    .UseInMemoryScopes(StandardScopes.All)
                });
            });
