### ISSUE TITLE
webform example missing

### ISSUE THREAD

**Issue by pinale** [IdentityServer/IdentityServer3.Samples#230]
May you please add a very simple classic  asp.net webform example that authorize users by identity server?
it would be great!
thanks

**Comment by brockallen** [comment]
The webforms sample would be the same as the MVC ones, except instead of controllers you have aspx pages. The Startup code would be the same and that's the most important part.

**Comment by pinale** [comment]
The redirection to the idetityserver in case of a not authenticated request to a protected page is made automatically by the  RedirectUri property of the app.UseOpenIdConnectAuthentication() extension method? No other changes are needed to the webform client?
thanks a lot!



 = "https://localhost:44300/




----Messaggio originale----

Da: Brock Allen <notifications@github.com>

Data: 08/02/2016 15.10

A: "IdentityServer/IdentityServer3.Samples"<IdentityServer3.Samples@noreply.github.com>

Cc: "pinale"<cicciottino@libero.it>

Ogg: Re: [IdentityServer3.Samples] webform example missing (#230)




The webforms sample would be the same as the MVC ones, except instead of controllers you have aspx pages. The Startup code would be the same and that's the most important part.

**Comment by avmp2208** [comment]
Hello Brock I hope you are well, I have the same question, the problem is, I have the start up class running Ok, once the app start it triggers the connfiguration method inside the start up class and in my web.config I have this to protect all my pages, So when I try to access to a basic page, a Default.aspx page the app tell efectively access denied but It doesn´t redirect to the STS,

web.config
`<system.web>
		<compilation debug="true" targetFramework="4.5" />
		<httpRuntime targetFramework="4.5" />
		<authorization>
			<deny users="?" />
		</authorization>
	</system.web>`

And this my Start up class

`public void Configuration(IAppBuilder app)
		{
			// For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=316888
			JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

			app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				AuthenticationType = "Cookies",
				//LoginPath = new PathString(ConstansValues.BaseAddress + @"permissions/")
			});

			app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
			{
				ClientId = "Prueba",
				Authority = ConstansValues.BaseAddress,
				RedirectUri = ConstansValues.UrlClient,
				PostLogoutRedirectUri = ConstansValues.UrlClient,
				ResponseType = "id_token token",
				Scope = "openid email write",

				SignInAsAuthenticationType = "Cookies",
				Notifications = new OpenIdConnectAuthenticationNotifications
				{
					SecurityTokenValidated = async n =>
					{

						var token = n.ProtocolMessage.AccessToken;
						// persist access token in cookie
						if (!string.IsNullOrEmpty(token))
						{
							n.AuthenticationTicket.Identity.AddClaim(
								new Claim("access_token", token));
						}
						var nid = new ClaimsIdentity();
						nid.AddClaim(new Claim(@"id_token", n.ProtocolMessage.IdToken));
					},
					RedirectToIdentityProvider = n =>
					{
						// if signing out, add the id_token_hint
						if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
						{
							var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
							if (idTokenHint != null)
								n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
						}
						return Task.FromResult(0);
					}
				},
			});
		}`

I'm really sure that I'm missing something but I don´t know what.

**Comment by brockallen** [comment]
Not sure -- does your Configuration run?

**Comment by pinale** [comment]
With the same configuration of an mvc application, a webform application doesn't seem to redirect to the IdentityServer in case of "http 401 not authorized" response.
I've posted the question here: http://stackoverflow.com/questions/35338035/identityserver3-authentication-on-asp-net-webform

**Comment by brockallen** [comment]
I suspect it's something configured from system.web that's interfering. If I have some time I can try to create a quick web forms sample.

**Comment by avmp2208** [comment]
Thanks Brock I'll appreciate that, really thanks.

**Comment by pinale** [comment]
It would be great!, thanks

**Comment by brockallen** [comment]
WebForms sample is now on dev branch

**Comment by techdetail** [comment]
@brockallen : Could you please guide me to the url of Dev branch which you were referring, i'm exactly running into same issue.

**Comment by techdetail** [comment]
I figured out Thank you, https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WebFormsClient
