### ISSUE TITLE
For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method. 

### ISSUE THREAD

**Issue by venkatrv** [IdentityServer/IdentityServer3.Samples#232]
I am getting the following error when I try to use Windows Login with IdentityServer3. Any one knows how to fix this?

"For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method."

**Comment by brockallen** [comment]
No idea.

**Comment by naveenkumarreddy** [comment]
I am also getting the same error, is there any solution to resolve it?

**Comment by venkatrv** [comment]
some of files might have been corrupted. Just try to resetup the
IdentityServer.
In my case it worked when tried setting up this from scratch.

On Thu, Jul 14, 2016 at 1:52 PM, naveenkumarreddy <notifications@github.com>
wrote:

> I am also getting the same error, is there any solution to resolve it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3.Samples/issues/232#issuecomment-232597981>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMo-U4zaV2cs2L-7cv8iBoUwDFHOBHViks5qVfHJgaJpZM4HaRdH>
> .
>



-- 
Regards,
Venkat

**Comment by PhilOchu** [comment]
Had the same error message earlier today and in our case the problem was we entered a wrong url for WsFederationAuthenticationOptions.MetadataAddress - it took a while to figure out so hope this helps someone.
