### ISSUE TITLE
Authenticated File Upload API Question

### ISSUE THREAD

**Issue by robmen** [IdentityServer/IdentityServer3.Samples#233]
First of all, great work you've done with Identity Server. I'm very impressed with the flexibility you've built into the system and the many examples are very helpful.

I've been searching far and wide for an example of uploading a file to an authenticated WebApi. I need to upload from both a native client and a web page. Implementing the native client client will be very straight forward using Bearer tokens to POST the file stream to the WebApi. It's the web page where I'm less certain what to do.

My plan was to host a form with an `<input type='file'/>` on the web page and set the `action` to post directly to the WebApi URL. That way the multi-part file contents are sent directly to the WebApi (do *not* want to upload to the web page's server then have to send the contents to the WebApi).

The problem is how to send the authorization token with the posted form contents? Some options I've considered:

1. Enable both bearer token and cookie authentication on the WebApi end point. Thus native client uploads with a bearer token and the web page naturally sends its cookie along (web page and WebApi can be made to be in the same domain).  I haven't seen anyone do this, so I'm wondering if this is a bad idea (or even possible).

2. Web page post with javascript. Getting the token out of the cookie with javascript is out (HTTP-only, right?) so I was thinking the token could be stored in a hidden input field and the javascript could read it and concoct the bearer Authorization header and a post request to the WebApi. I'm not big on javascript (more backend) so I'm not sure this is even a good idea.

3. Something better?

Any insight would be appreciated.

**Comment by brockallen** [comment]
With XHR2 you can do programmatic file uploads (and thus set the access token as the authorization header). But if you can't use that then just send the token in an input field.

**Comment by robmen** [comment]
So it sounds like Option 2 is the way to go and if I don't want to worry about browser support I can standardize on sending the token via a hidden input field. If I got any of that wrong feel free to correct me. :)

Thank you for your insight.
