### ISSUE TITLE
the version of dlls in IdentityServer3.Samples does not match the version of dlls in IdentityServer3

### ISSUE THREAD

**Issue by JustFreedom** [IdentityServer/IdentityServer3.Samples#237]
some of the projects in IdentityServer3.Samples updated except the MVC Authentication.the demo always show errors with unload the special version of dll when run it.
the version of dlls in IdentityServer3.Samples  does not match the version of dlls in dentityServer3.

**Comment by brockallen** [comment]
We recently updated many of them. Please check again and see if the situation is improved. Thanks.
