### ISSUE TITLE
Handle token expiry

### ISSUE THREAD

**Issue by malichishti** [IdentityServer/IdentityServer3.Samples#239]
I'm using IdentityServer3.Samples/source/Clients/WcfService/IdentityServerWrappedJwtHandler.cs to enable JWT for my WCF. however once the time span of the token expires i get 

"At least one security token in the message could not be validated." at 
`var handler = new JwtSecurityTokenHandler();
var principal = handler.ValidateToken(jwt, parameters, out validatedToken);`

My question is if there is a way for the token to be refreshed here? or would it be best if the original requester validates and updates the token before making a request to WCF?

Also is there a way to set the expiry of token to e.g. 10 hours?

Thank you

**Comment by leastprivilege** [comment]
access token lifetime is set on the client config in idsrv.

the sender either proactively makes sure the token is valid (e.g. using refresh tokens) - or it waits for an error from the service.
