### ISSUE TITLE
Embedded Idp

### ISSUE THREAD

**Issue by mohanr** [IdentityServer/IdentityServer3.Samples#240]
A question about the difference between embedded Idp and Idp code included and built as part of the project.
We are using embedded mode for development only. But we deploy this to the Azure ASE. Are there any performance impacts ? Our performance team will run load tests even if Idp is embedded as part of their process.

If this is related to Azure/.NET and not really Idp I will research elsewhere.

**Comment by brockallen** [comment]
I don't follow -- what does "embedded mode" mean?

**Comment by mohanr** [comment]
This is my confusion. I see the IdentityServer3 source code being built as part of a project and deployed.

I use the nuget packages directly.
Can I ask if there are any performance metrics that I can refer ?

**Comment by brockallen** [comment]
We recommend that you use IdentityServer via a NuGet reference.

**Comment by mohanr** [comment]
Can I ask ? Which of these interfaces should I use ? _IdentityServer3_ is from nuget.

`

                      namespace IdentityServer3.Core.Services
                     {
                         //
                       // Summary:
                      //     This interface allows IdentityServer to connect to your user and profile store.
                      public interface IUserService
                        {
                               //
        // Summary:
        //     This method gets called when the user uses an external identity provider to authenticate.
        //     The user's identity from the external provider is passed via the `externalUser`
        //     parameter which contains the provider identifier, the provider's identifier for
        //     the user, and the claims from the provider for the external user.
        //
        // Parameters:
        //   context:
        //     The context.
        Task AuthenticateExternalAsync(ExternalAuthenticationContext context);
        //
        // Summary:
        //     This method gets called for local authentication (whenever the user uses the
        //     username and password dialog).
        //
        // Parameters:
        //   context:
        //     The context.
        Task AuthenticateLocalAsync(LocalAuthenticationContext context);
        //
        // Summary:
        //     This method is called whenever claims about the user are requested (e.g. during
        //     token creation or via the userinfo endpoint)
        //
        // Parameters:
        //   context:
        //     The context.
        Task GetProfileDataAsync(ProfileDataRequestContext context);
        //
        // Summary:
        //     This method gets called whenever identity server needs to determine if the user
        //     is valid or active (e.g. if the user's account has been deactivated since they
        //     logged in). (e.g. during token issuance or validation).
        //
        // Parameters:
        //   context:
        //     The context.
        Task IsActiveAsync(IsActiveContext context);
        //
        // Summary:
        //     This method is called prior to the user being issued a login cookie for IdentityServer.
        //
        // Parameters:
        //   context:
        //     The context.
        Task PostAuthenticateAsync(PostAuthenticationContext context);
        //
        // Summary:
        //     This method gets called before the login page is shown. This allows you to determine
        //     if the user should be authenticated by some out of band mechanism (e.g. client
        //     certificates or trusted headers).
        //
        // Parameters:
        //   context:
        //     The context.
        Task PreAuthenticateAsync(PreAuthenticationContext context);
        //
        // Summary:
        //     This method gets called when the user signs out.
        //
        // Parameters:
        //   context:
        //     The context.
        Task SignOutAsync(SignOutContext context);
    }
}

`


`
                    
                     namespace Thinktecture.IdentityServer.Core.Services
                     {
                                 public interface IUserService
                                 {
                                 Task<AuthenticateResult> AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message);
                                Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message);
                                Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null);
                                Task<bool> IsActiveAsync(ClaimsPrincipal subject);
                                Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message);
                                Task SignOutAsync(ClaimsPrincipal subject);
    }
}
`

**Comment by mohanr** [comment]
I have managed to implement the new methods. More specifically

`
        
         Task IsActiveAsync(IsActiveContext context);
`

was

`
             
                  Task<bool> IsActiveAsync(ClaimsPrincipal subject);
                 
`

The code was returning 'bool' but now the return type is _Task_.

**Comment by mohanr** [comment]
I believe we need to do this.

               `

         public Task IsActiveAsync(IsActiveContext context)
        {
            context.IsActive = true;
            return Task.FromResult(0);
        }
`

**Comment by brockallen** [comment]
You're asking lots of fundamental questions that can be answered by reading the docs, or watching the intro video. https://identityserver.github.io/Documentation/
