### ISSUE TITLE
Can I keep login.html outside from Identity Server 3 application ?

### ISSUE THREAD

**Issue by amoldorkar-ezest** [IdentityServer/IdentityServer3.Samples#244]
I developed a project using ASP.Net 5 which has 2 projects
1. Web Project
2. Identity Server 3 project

by default login page kept in Identity Server 3 application but I want to move it from Identity Server 3 to my Web Project..

How can I do this..?

**Comment by brockallen** [comment]
You can implement the IViewService interface. Check the docs on custom view service.

Also, if you're doing ASP.NET 5, then maybe you'd prefer using IdentityServer4: https://github.com/IdentityServer/IdentityServer4/

**Comment by leastprivilege** [comment]
I think you also added a property to specify where to load the files from, no?

**Comment by brockallen** [comment]
Oh yea -- I think so. Yep, looks like there's this:

```
factory.ConfigureDefaultViewService(new IdentityServer3.Core.Services.Default.DefaultViewServiceOptions
{
    CustomViewDirectory = "c:\\views"
});
```
