### ISSUE TITLE
Tests with JavaScript Implicit clients fail in jwk request against WLP because of missing x5c parameter

### ISSUE THREAD

**Issue by giraone** [IdentityServer/IdentityServer3.Samples#245]
I am using the "JavaScriptImplicitClient" and "JavaScriptImplicitClient Manual" code to test against the OIDC provider implementation of IBM WebSphere Liberty (WLP). The basic steps work, but in the JWK request, the WLP returns only
`{
 "keys":[{
  "kid":"Bf61uuivwBnC4okpwzms","use":"sig","alg":"RS256","kty":"RSA","n":"..............","e":"AQAB"
 }, {
  "kid":"xsBu5rwvwcDB8bAjvCsx","use":"sig","alg":"RS256","kty":"RSA","n":"..............","e":"AQAB"
 }]
}
`
But both JavaScript samples are accessing directly the "x5c" parameter without checking its existence and therefore both client fail at this step.

"JavaScriptImplicitClient Manual" in `function validateToken()`:
`var cert = jwks.keys[0].x5c[0];`

"JavaScriptImplicitClient" in `function OidcClient.prototype.loadX509SigningKeyAsync()`
`
        if (!key.x5c || !key.x5c.length) {
            return error("RSA keys empty");
        }
`

The spec says "_The JWK x5c parameter MAY be used to provide X.509 representations of keys provided._", but I have to little experience to decide now which side (client, server, my server configuration) is wrong. 

Can you help me, to figure this out?

**Comment by brockallen** [comment]
Sounds similar: https://github.com/IdentityModel/oidc-token-manager/issues/51

You'll have to wait for the oidc-client library to be rewritten (https://github.com/IdentityModel/oidc-client/issues/2) to get this bug fixed.
