### ISSUE TITLE
Using IdentityServer with Postgres existing database

### ISSUE THREAD

**Issue by Sudkart** [IdentityServer/IdentityServer3.Samples#246]
Hi all,

We are using the nopostgresql as our current database now i want to integrate the application to the identityserver.
Can i connect the identityserver to the existing nopostgresql  database. If so how?
Please provide me a link to go through the next step.
Thanks in advance.

**Comment by brockallen** [comment]
You can use any data store you want with IdSvr, you just need to implement the various extensibility points that we document here: https://identityserver.github.io/Documentation/docsv2/configuration/serviceFactory.html
