### ISSUE TITLE
invalid_client error returned using x509 secret

### ISSUE THREAD

**Issue by adkendall** [IdentityServer/IdentityServer3.Samples#247]
Hi, I'm trying to get the "Console Client Credential Flow Using Certificate" sample to work. I've tried this with the self hosted server and the minimal web host. 

When requesting the token "Invalid_client" is returned and the logs also report "Parser found no secret". I get the same problem on our deployed identityserver.

I've tried everything I can think of. I've set the sslflags in a location element as instructed and also tried installing all the certs in the computer store. 

Can anyone confirm that the sample actually works? If it does, any ideas what my problem might be?

**Comment by leastprivilege** [comment]
The sample works. It is hard to tell what's might be wrong with your setup

**Comment by adkendall** [comment]
Apologies - I should have replied sooner to this. Thanks for the response - I can confirm that I tried this on a different machine and got the sample to work immediately - still unclear as to what the issue is/was.
