### ISSUE TITLE
How to Find Out Which Client is Asking for Authentication Inside UserService Code?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer3.Samples#248]
I'm using the ASP.NET Identity sample. I need to find out which one of the MVC clients has initiated an authentication request in the user service code. I have the following code:

        ```
        IOwinContext context;
        public UserService(UserManager userMgr, OwinEnvironmentService env)
            : base(userMgr)
        {
            context = new OwinContext(env.Environment);
        }
     ```

I've looked at what's available in the context object in the debugger.

`context.Request.Headers["Referer"]`

provides the url that I can use to determine which mvc client initiated the authentication sometimes. When the user enters his user name and password and clicks the submit button then 

`context.Request.Headers["Referer"]`

doesn't tell me the client that initiated the authentiation (it provides the IdSvr url). The reason that I need to know which client is that I've add multi tenancy to ASP.NET Identity and right before I search for the user I have to have the right Tenant or Application ID and the Referer then doesn't indicate the mvc client's url. 

So is there a reliable way that inside the constructor of the UserService I can determine which client initiated the authentication request when the user's login is submitted to the IdSvr?

Thank you

**Comment by brockallen** [comment]
Most of the context params have the Client as a property.

**Comment by farzad99** [comment]
Thank you for your response. Right after the login screen is displayed I wasn't able to find any information that would identify the client. I ended up using a cookie to store the client.

**Comment by farzad99** [comment]
I was able to find the ClientId in the LocalAuthenticationContext class:

`LocalAuthenticationContext.SignInMessage.ClientId`

Thank you for your help.

**Comment by naveenkumarreddy** [comment]
I am getting clientId null always from LocalAuthenticationContext.SignInMessage.ClientId
