### ISSUE TITLE
Suave.io support

### ISSUE THREAD

**Issue by sjuberman** [IdentityServer/IdentityServer3.Samples#249]
Hey, would it be hard to implement IdSrv3 support in Suave.io ?  Suave does have OWIN support (https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs) but since I'm both a newbie in OWIN and IdSrv3 I'm not sure where to start. 
I started looking at https://github.com/sjuberman/IdentityServer3.AccessTokenValidation to see if that would lead me somewhere but it seems like it's very much dependent on the IAppBuilder interface. Would it be hard/impossible to make a version of IdentityServer3.AccessTokenValidation that does not rely on IAppBuilder?

I'm wiling to try to make this version myself but I would really appreciate a few pointers on where to start.

**Comment by leastprivilege** [comment]
Is it that you cannot reference Katana at all - or that you can't use an IAppBuilder?

**Comment by JohnDoeKyrgyz** [comment]
I have a working sample with suave.io and IdentityServer up and running in this pull request on the Suave project [https://github.com/SuaveIO/suave/pull/473](https://github.com/SuaveIO/suave/pull/473).

Suave was not sending the Content-Length header being set by IdentityServer, which was causing clients to hang, thinking that there was always more of the response to load. This pull request fixes this bug, as well as provides a sample application.
