### ISSUE TITLE
Client secret in WPF client?

### ISSUE THREAD

**Issue by claq2** [IdentityServer/IdentityServer3.Samples#250]
This is just a question, not a technical issue... why is it ok to put the client secret in a thick client , like the WPF app that uses the hybrid flow? What prevents someone from extracting or capturing it and the client ID and impersonating your app? Or does that really matter? Sorry if this is obvious to OAuth2 veterans, I’m still wrapping my head around it.

**Comment by brockallen** [comment]
> What prevents someone from extracting or capturing it and the client ID and impersonating your app?

Nothing. For public clients the secret is not really secret. For public clients it's best to not make authorization decisions based on the client.

**Comment by claq2** [comment]
Ah, I get it. Don't assign rights based solely on the client's ID e.g. don't make it an admin tool capable of managing your whole system. Base access only on the user. Someone might clone your app and cause a copyright issue, but users can't do any more or less. 

Thanks.
