### ISSUE TITLE
Q: Locally enforced 2FA for external logins?

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer3.Samples#251]
Does it make sense conceptually?
Generally, the idea is - external is external - whatever the rules they have over there is up to "them" and we're only interested in the outcome. 
But sometimes "external" is not all that external, say a local adfs is used. There's a local knowledge about the users, just the part about authenticating them is outsourced to adfs.
Seems like it could make sense to want to locally (from IdSrv) enforce 2fa for some "external" users based on whatever local criteria.
Does this sound reasonable? Set me straight, please.Thanks.

**Comment by brockallen** [comment]
> Does it make sense conceptually?

I've never had a customer ask for this. But do whatever you need to -- IdSvr is sufficiently flexible to allow it.

**Comment by Peperud** [comment]
Thank you
