### ISSUE TITLE
Javascript hybrid / authorization code flow

### ISSUE THREAD

**Issue by olee** [IdentityServer/IdentityServer3.Samples#252]
It looks like there is no sample on how to do hybrid or authorization code flow running with javascript and oidc-token-manager.
Currently if I try to do this, it looks like the token manager doesn't perform the call to the token endpoint with the received code.
I'm trying to switch to this flow because I encountered problems with Internet Explorer 11 on redirects from the IdSrv and I think this is caused by the very long redirect URIs.

I hope you can help me there - either with the code flows or maybe if you know something about IE issues.

**Comment by olee** [comment]
After some more testing I got a hybrid flow to work, but I couldn't really get authorization code running.
I get the code, but it does not seem to fetch the id_token...

**Comment by leastprivilege** [comment]
JS clients use implicit flow.

**Comment by leastprivilege** [comment]
..and IE has a restriction of 2 KB on URLs.

You can use the userinfo endpoint to make your id_tokens smaller, and reference tokens to make the access tokens smaller. Has been discussed here numerous times. search the archives.
