### ISSUE TITLE
Compile error on MembershipReboot sample

### ISSUE THREAD

**Issue by lcssk8board** [IdentityServer/IdentityServer3.Samples#253]
New IdentityServer3 version (2.5) have a property called AllowAccessTokensViaBrowser that are used on the MembershipReboot sample but the IdentityServer3 used on it is 2.4 leading to compile error:

'Client' does not contain a definition for 'AllowAccessTokensViaBrowser' on WebHost.

**Comment by brockallen** [comment]
I think this got merged. Closing. Thx.
