### ISSUE TITLE
IdentityUser with default value as Username

### ISSUE THREAD

**Issue by florindpreda** [IdentityServer/IdentityServer3.Samples#255]
Hi,

Long story short, I'm delegating authentication from an external identity provider to IdentityServer3. That external identity provider uses the subject identifier (`sub`) to create in-memory users and forward them to its client systems. Those client systems then use the `sub`as internal usernames.

As I only have control over the IdentityServer3 the only option to implement this is to actually have the `sub `as a string with the same value as the `username`. Now, I tested this with InMemory users and it works fine but I will need to use AspNetIdentity users for the production environment.

I looked at the AspNetIdentity sample and noticed that I can control the primary key type of the User. I don't really need to change this as by default it's a string which is fine. I also noticed that this primary key is also used as the subject identifier (`sub`).

What I would like to know is what would be the easiest way to set the User Id, and hence the `sub`, to have the default value as the `username` instead of a Guid which is the current implementation?

Thanks.

**Comment by florindpreda** [comment]
Ok, after a little bit of research it seems that the easiest way to do this is to override the CreateAsync methods of the UserManager which looks like:

```
public override System.Threading.Tasks.Task<IdentityResult> CreateAsync(User user)
{
	user.Id = user.UserName;
	return base.CreateAsync(user);
}
```

```
public override System.Threading.Tasks.Task<IdentityResult> CreateAsync(User user, string password)
{
	user.Id = user.UserName;
	return base.CreateAsync(user, password);
}
```

I know it's not really according to standards but seems like a safe approach as the Username itself must always be unique so we won't end up with duplicated subject identifiers.

**Comment by brockallen** [comment]
Is that working for you? That piece of how you manage the DB for you users is really up to you. Our AspId library is really more of a sample to get you started, and at the end of the day it's your code that you need to manage.

**Comment by florindpreda** [comment]
Yes, it works fine. Instead of string guids now I have the username as the id in the database which then translates to the sub during runtime.

I think there might be an alternative though. Instead of actually storing the sub as the id of the entity in the database it should be possible to convert the username to sub (instead of the id) when reading it. Not sure if there are benefits to one approach over the other.

**Comment by brockallen** [comment]
We suggest people use GUIDs for the sub claim, since things like username might change or technically could get reused for different people.

**Comment by florindpreda** [comment]
I understand. 
Unfortunately I have a less straightforward setup. There's another Idp which acts as a client to IdentityServer3 which I can't easily modify. It creates an in-memory user based on the sub which will then be passed to it's own clients which must have users with matching usernames... Long story.

**Comment by brockallen** [comment]
Sure, I get it.

So are we all set on this issue?

**Comment by florindpreda** [comment]
Yep, all good. Thanks!
