### ISSUE TITLE
Cannot access IdentityManager UI when deploying IdentityServer3 to an Azure Website

### ISSUE THREAD

**Issue by florindpreda** [IdentityServer/IdentityServer3.Samples#258]
Hi,

I set-up IdentityServer3 to use ASP.NET Identity using the sample provided. Everything works fine locally, I can access the Identity Manager UI via '/admin' and can add/remove users/roles.
However, when I deploy it to Azure and try to access it then nothing happens and takes me to this URL:
https://IdentityServer3t/admin/authorize?state=11373557769572288&client_id=idmgr&response_type=token

I looked at the database and I noticed that the ASP.NET Identity tables were not automatically generated. I suspect this is the reason why the IdentityManager UI is not displaying. When I tested locally however, these tables were automatically created.

Any ideas how to overcome this?

**Comment by florindpreda** [comment]
I'm still experiencing this even after the ASP.NET IdentityTables have been created. I'm left with an empty page and a URL looking like this:
https://IdentityServer3t/admin/authorize?state=11373557769572288&client_id=idmgr&response_type=token

Any suggestions?

**Comment by brockallen** [comment]
RAMMFAR?

**Comment by florindpreda** [comment]
I think it's probably the default IdentityManager SecurityConfiguration which is LocalSecurity as I learned from this video: https://vimeo.com/125427106

Currently trying to use IdentityServer as the Idp for IdentityManager. I'm assuming it should work like any other client?

**Comment by brockallen** [comment]
Yep. Again, the samples have a sample config for that.

**Comment by florindpreda** [comment]
For IdentityManager with IdentityServer as Idp or any client in general?

**Comment by florindpreda** [comment]
In case someone else stumbles over this:
http://stackoverflow.com/questions/36717161/asp-net-identity-plugin-ui-identitymanager-for-identityserver3-not-working-aft
