### ISSUE TITLE
Full localization and OwinEnvironementService with LocalizationService example

### ISSUE THREAD

**Issue by deserthero** [IdentityServer/IdentityServer3.Samples#259]
I used a IdentityServer3.Contrib.Localization to provide localization for identityserver but i have 3 questions:

1- IdentityServer3.Contrib.Localization provide only translations for scopes,messages,events so it's ok but it's not provide a full localization that we want for example localization for a login and logout page, so how can i provide a localization for the text that it inside the html?

2- I know that i can provide a custom views so i can change the text inside the html views but i want to do a localization for example for Arabic language and English language so can i create an owin middleware to provide a localization for a specific strings inside html or is it an example for this?

3- is this an example on how to use OwinEnvironementService  with LocalizationService to determine the browser accept-language cause i searched for an example but i didn't found any?

**Comment by brockallen** [comment]
1: you'd have to do that via a custom view service.
2: no
3: you can inject the OwinEnvironmentService into the ctor of your LocalizationService.
