### ISSUE TITLE
Sample for External Authentication Provider

### ISSUE THREAD

**Issue by ajsblue** [IdentityServer/IdentityServer3.Samples#261]
I want the Identity Server to act as an External Authentication Provider.

Is there a sample available, for both the server part as the remote client part?

**Comment by brockallen** [comment]
All of the samples pretty much show this. The samples are preconfigured for the sample host from the core IdentityServer3 repo.

**Comment by ajsblue** [comment]
Which of the samples shows it best?

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs#L78

**Comment by ajsblue** [comment]
This is bot what I mean. I want an instance of IdentityServer to act as an external identity provider for other identity servers.

**Comment by brockallen** [comment]
Yes, that's also possible. I have no idea what other IdPs you're using, so you'd have to check their docs to learn how to configure an OIDC IdP.
