### ISSUE TITLE
User based resource authorization (not with roles)

### ISSUE THREAD

**Issue by mirac61** [IdentityServer/IdentityServer3.Samples#264]
Hello, I am developing a multi client project, and I try using Identity Server on authentication and authorization layer. But I don't want use roles, I need authorize user based, I will preapre authorize templates, while new user join system select one of them and can customize later. forexample: user x can access y page, user x can't delete on y page...  Is possible can do it with identity server?

**Comment by leastprivilege** [comment]
IdentityServer is “authentication as a service”. Authorization is an application concern.

— 
cheers
Dominick Baier

On 27 April 2016 at 16:40:23, mirac61 (notifications@github.com) wrote:

Hello, I am developing a multi client project, and I try using Identity Server on authentication and authorization layer. But I don't want use roles, I need authorize user based, I will preapre authorize templates, while new user join system select one of them and can customize later. forexample: user x can access y page, user x can't delete on y page... Is possible can do it with identity server?
