### ISSUE TITLE
 Null reference exception in MVC OWIN Client sample

### ISSUE THREAD

**Issue by nike61** [IdentityServer/IdentityServer3.Samples#271]
Getting null reference exception in MVC OWIN Client sample when try to call Web API in this line of code: 
`var token = (User as ClaimsPrincipal).FindFirst("access_token").Value`

I've tried to modified Startup.cs
```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "mvc.owin.implicit",
                Authority = Constants.BaseAddress,
                RedirectUri = "https://localhost:44301/",
                ResponseType = "id_token token",
                Scope = "openid email write",
                

                SignInAsAuthenticationType = "Cookies",
            });
 
```
But getting the same issue. It seems that it can't find access_token in response.

**Comment by aperisic** [comment]
The Authorize attribute is missing. I will branch with the fix. Without the attribute there is no User defined with Claims.

**Comment by aperisic** [comment]
Fixes now merge
https://github.com/IdentityServer/IdentityServer3.Samples/pull/293
https://github.com/IdentityServer/IdentityServer3.Samples/pull/294
