### ISSUE TITLE
Build errors for WPF clients

### ISSUE THREAD

**Issue by firasr** [IdentityServer/IdentityServer3.Samples#272]
The "Clients" solution is building successfully on **VS2015**. However, I get build error when building it using **VS2013** for the following projects:
1. WPF Client (Hybrid with PKCE and PoP)
2. WPF Client (Hybrid with PKCE)

Few error messages I get are the following:

```
> source\Clients\WpfOidcClient\MainWindow.xaml.cs(52,35,52,36): error CS1056: Unexpected character '$'
> source\Clients\WpfOidcClient\OidcClient\LoginResult.cs(8,43,8,44): error CS1519: Invalid token '=' in class, struct, or interface member declaration
> source\Clients\WpfOidcClientPop\MainWindow.xaml.cs(244,39,244,40): error CS1056: Unexpected character '$'
> source\Clients\WpfOidcClientPop\OidcClient\OidcSettings.cs(13,51,13,52): error CS1519: Invalid token '=' in class, struct, or interface member declaration
```

Any idea?

**Comment by leastprivilege** [comment]
That's C# 6 features. You need to remove them on 2013.

**Comment by firasr** [comment]
Modifying the samples source code to fit it with VS2013 while keeping up to date with the samples latest updates you guys are making is somehow inconvenient; especially for those who doesn't have VS2015.

**Comment by leastprivilege** [comment]
I am sorry if this is inconvenient for you. Maybe download the free VS2105 community edition?

**Comment by firasr** [comment]
Ya, that seems the best solution. Thanks Dominick!
