### ISSUE TITLE
Azure AD, Miscorosft Account, O365

### ISSUE THREAD

**Issue by tbasallo** [IdentityServer/IdentityServer3.Samples#273]
I wanted to share with everyone that Microsoft's v2 (Feb 2016?) supports authenticating against Azure AD and all of Microsoft's service that use Azure (Passport, live, Microsoft Account, Office 365 (O365)) in one easy end point. I'll try and write up a tutorial, but here's the gist:

[Azure v2 App Model](https://azure.microsoft.com/en-us/documentation/articles/active-directory-appmodel-v2-overview/) on Azure docs. There's a good video.

To implement in IS you use:

'Configure as OpenIdConnect

    app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
    {
         SignInAsAuthenticationType = signInAsType,
         ClientId = "Client_ID",
         Authority = "https://login.microsoftonline.com/common/v2.0",
         RedirectUri = "your return URL",
         Scope = "openid email profile",
         ResponseType = "id_token",
         AuthenticationType = "Microsoft",
         TokenValidationParameters = new TokenValidationParameters
         {
                AuthenticationType = IdentityServer3.Core.Constants.ExternalAuthenticationType,
                ValidateIssuer = false,
          }
      });`

And that's it, works like a charm.

**Comment by ranieuwe** [comment]
Note that this only works with selected applications. See https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-limitations/ for more information on that.

**Comment by leastprivilege** [comment]
Why is validate issuer set to false?

**Comment by ranieuwe** [comment]
From the looks of it the validation only seems to work if a specific tenant is passed in (making the request organization specific). As he has not passed in an organization specific tenant id in the Authority field but _common_ it fails with the following error when ValidateIssuer is set to true:

IDX10205: Issuer validation failed. Issuer: 'https://login.microsoftonline.com/1e355c04-e0a4-42ed-8e2d-7351591f0ef1/v2.0'. Did not match: validationParameters.ValidIssuer: 'null' or validationParameters.ValidIssuers: 'https://login.microsoftonline.com/{tenantid}/v2.0'.

Which makes sense as the issuer is my organisation. The only thing that puzzles me is the "ValidIssuer" field being null. 

Once the tenant is set, i.e. https://login.microsoftonline.com/1e355c04-e0a4-42ed-8e2d-7351591f0ef1/v2.0 it can validate the issuer is the organization. 

I am not sure how one would go at validating the issuer if it is a Microsoft account (common).

**Comment by tbasallo** [comment]
@ranieuwe after reading through that I think that some of those exceptions may not apply to IdentityServer because the token being used (for example with a standalone API) is being generated and managed by IdentityServer. I know that in my case I am using a website and a standalone Web API both (three actually) managed all through IdentityServer. 

Just mentioning so that this option is not immediately disregarded.

**Comment by tbasallo** [comment]
@leastprivilege I am not sure, but it did not work without setting it false.

What would be the concerns with that setting to false?

**Comment by leastprivilege** [comment]
Validating the issuer name is part of validating a token.

**Comment by CTDevRic** [comment]
@tbasallo I appreciate you showing your example and I was eager to implement this as a secondary provider, unfortunately, I am seeing an error when it gets over to Microsoft. Not a descriptive error, mind you, just a "oops, something went wrong" type of error. Did you ever happen to put together a more comprehensive tutorial? If so, I would love to be pointed to it...maybe I can find out the error of my ways.

**Comment by ranieuwe** [comment]
@CTDevRic keep in mind to specify a tenant if you are using Azure AD. Also @tbasallo is using v2.0. Also generally there is another error in small at the bottom of "oops, something went wrong" page.

Here is our OIDC configuration for Azure AD:

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
{
  AuthenticationType = "AzureAd",
  Caption = "Office 365",
  Scope = "openid email profile",
  ClientId = "client-id-guid-here",
  Authority = "https://login.microsoftonline.com/tenant-guid-id-here/",
  PostLogoutRedirectUri = "http://localhost",
  RedirectUri = "http://localhost:44300",
  AuthenticationMode = AuthenticationMode.Passive,
  SignInAsAuthenticationType = signInAsType
}
```

**Comment by CTDevRic** [comment]
@ranieuwe Roeland - thanks for your input. I went back and looked at the page I was getting from Microsoft, and found the following in light grey type at the bottom of the right sidebar:

> Additional technical information:
> Correlation ID: f73d8cd6-7fa9-4988-b457-b0e9e895fc6d
> Timestamp: 2016-08-19 18:11:31Z
> AADSTS90014: The request body must contain the following parameter: 'client_id'.

Obviously, that points to the ClientId property which I hadn't included, and I'm going to have to figure out where to get the tenant guid to append to the Authority URL.

I was having issues with this earlier, and I see you have it in your code snip...will this work with `localhost` URI's? I was getting an error about it not being a valid URI when I was testing. Obviously, the ClientId is the first error being trapped, but if I can prepare for other errors along the way, that will help, too.

Thanks again for the info! It's greatly appreciated!

**Comment by ranieuwe** [comment]
Without turning this issue into a chatbox. To quickly answer your questions:

- Yes you can use it with localhost, just add the reply URIs to your application configuration on the manage.windowsazure.com portal in your AD configuration
- Tenant ID can be grabbed from there as well. If you visit your application definition on the Azure AD, the tenant ID will be the first Guid in your URL.

**Comment by CTDevRic** [comment]
@ranieuwe Thanks, Roeland...that will get me on the right track. No more chatting needed...I hope.

Take care!
