### ISSUE TITLE
IdentityServer3.Core.Validation.SecretParser - Secret id found:

### ISSUE THREAD

**Issue by NovakSavicOPAL** [IdentityServer/IdentityServer3.Samples#274]
Hi, 

Is there possibility to turn off logging client secrets?

Regards,
Novak

**Comment by brockallen** [comment]
What are you logging settings?

**Comment by NovakSavicOPAL** [comment]
Is it possible to have verbose logs but without logging sensitive information (like. client secrets)?

**Comment by leastprivilege** [comment]
client secrets are not logged IIRC.

**Comment by NovakSavicOPAL** [comment]
Ok, I will check once again. But, I strongly believe that I saw this in one use case. If I reproduce this, I will report it. 

Cheers.

**Comment by leastprivilege** [comment]
It certainly depends on the logging settings - e.g. when you log http traffic - all secrets will be in the logs.

Logging is not made for production use as the docs explain.

**Comment by NovakSavicOPAL** [comment]
For sure I would not log https trafic, this is not what I mean. Sometimes I would like to turn on DEBUG logs for IDP even in production, for diagnostic just for short time, but I would not like to see client secrets, and user passwords in the logs. Is it safe to turn on IDP DEBUG log level?

**Comment by leastprivilege** [comment]
As I said before - I think yes. (unless you prove me wrong ;))

**Comment by NovakSavicOPAL** [comment]
Ok, sounds good. Thanks!
