### ISSUE TITLE
Windows Auth (All in one) receives "This site can’t be reached  The connection was reset." Out of the box.

### ISSUE THREAD

**Issue by chazt3n** [IdentityServer/IdentityServer3.Samples#275]
How do we get past this? Simply unzipped and hit F5, Windows Auth is enabled.

**Comment by chazt3n** [comment]
@estiller I was asked to talk toyou

**Comment by chazt3n** [comment]
I was able to get around this by hosting in IIS

**Comment by estiller** [comment]
Hi, I see you got around the issue but still let me ask - which sample were you trying to run? Anyway, to run in IIS Express with Windows Auth, you have to enable that on the property page of your web project in Visual Studio.

**Comment by chazt3n** [comment]
I was trying to run the Windows Auth (All In One) sample, Windows Auth was enabled as a property
