### ISSUE TITLE
Two separate errors and then, works?!

### ISSUE THREAD

**Issue by chazt3n** [IdentityServer/IdentityServer3.Samples#276]
@estiller I've been asked to include you here since this is related to Windows Authentication.

**Server Setup:**
---
**Startup.cs**

![image](https://cloud.githubusercontent.com/assets/3843179/15516040/8cfe3c82-21b6-11e6-9dd5-1f6aff5b2e74.png)
 I added AuthenticationType = "oidc" which may definitely be a bad idea...

**Controller**
![image](https://cloud.githubusercontent.com/assets/3843179/15516073/b1bd19e4-21b6-11e6-9ee7-e127b82ca371.png)

**Constants**
![image](https://cloud.githubusercontent.com/assets/3843179/15516083/c1e9d438-21b6-11e6-9ca3-022b1e42e225.png)

===

**Client Setup: (MVC App)**
---
**Only un-commented client**
![image](https://cloud.githubusercontent.com/assets/3843179/15516162/3417c2a4-21b7-11e6-9222-bdd2b143aead.png)

**Startup.cs**
![image](https://cloud.githubusercontent.com/assets/3843179/15516204/5b4da398-21b7-11e6-82c0-d3dedd370fb4.png)

===
**Behavior**
---

First up, I get this page when trying to access the /Home/Claims route
![image](https://cloud.githubusercontent.com/assets/3843179/15515995/5401e942-21b6-11e6-9fff-d723f5299841.png)

Refreshing the page gives me this:
![image](https://cloud.githubusercontent.com/assets/3843179/15516263/acdd0988-21b7-11e6-9509-70a1b479e363.png)

Finally, if I refresh the identityserver landing page and THEN refresh the /Home/Claims page, I get
![image](https://cloud.githubusercontent.com/assets/3843179/15516389/34e982de-21b8-11e6-9414-d3210b77fd6d.png)

I'm not getting a consent page. Any ideas, or ideas how I can help describe the issue?

Logs:
>iisexpress.exe Information: 0 : 05/24/2016 09:58:16 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
iisexpress.exe Information: 0 : 05/24/2016 09:58:16 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
iisexpress.exe Information: 0 : 05/24/2016 09:58:16 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 09:58:22 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
iisexpress.exe Information: 0 : 05/24/2016 10:01:38 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
iisexpress.exe Information: 0 : 05/24/2016 10:01:38 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
iisexpress.exe Information: 0 : 05/24/2016 10:01:38 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:01:39 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
iisexpress.exe Information: 0 : 05/24/2016 10:05:35 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
iisexpress.exe Information: 0 : 05/24/2016 10:05:35 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
iisexpress.exe Information: 0 : 05/24/2016 10:05:35 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
iisexpress.exe Warning: 0 : 05/24/2016 10:05:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:19:06 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:21:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:23:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 10:34:25 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 10:38:06 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 10:38:10 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:10:42 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:10:42 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:10:42 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:10:43 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:10:44 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:18:32 -05:00 [Information] (IdentityServer3.Core.Endpoints.DiscoveryEndpointController)
 Start discovery request
w3wp.exe Information: 0 : 05/24/2016 12:23:37 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:23:37 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:23:37 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:23:37 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:26:07 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:26:07 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:26:07 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:26:07 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:26:36 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:29:00 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:29:00 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:29:00 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:29:00 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:31:18 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:31:18 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:31:18 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:31:18 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:31:24 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 12:40:15 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 12:40:15 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 12:40:15 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 12:40:15 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 12:40:46 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:01:53 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Starting configuration.
w3wp.exe Information: 0 : 05/24/2016 13:01:53 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Adding WS-Federation endpoint
w3wp.exe Information: 0 : 05/24/2016 13:01:53 -05:00 [Information] (Owin.WindowsAuthenticationAppBuilderExtensions)
 Configuration done.
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 05/24/2016 13:01:53 -05:00 [Warning] (IdentityServer3.Core.Configuration.IdentityServerServiceFactory)
 RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 05/24/2016 13:01:54 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:30:51 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:30:53 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:32:11 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:32:33 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering
w3wp.exe Information: 0 : 05/24/2016 13:32:56 -05:00 [Information] (IdentityServer3.Core.Endpoints.WelcomeController)
 Welcome page requested - rendering

**Comment by brockallen** [comment]
The "remote cert is invalid" sounds like you just don't have SSL and the trust properly configured. That's all unrelated to IdentityServer.

**Comment by chazt3n** [comment]
@brockallen Wow I am silly, thank you, I was able to get past that. Now I'm actually looking at a new issue that may _still_ be unrelated, however it's very related to me getting a working STS. :( If you could take a moment to look at the setup here: https://github.com/IdentityServer/IdentityServer3/issues/2919 I would appreciate any insight very much. You and @leastprivilege are literally my heroes, unrelated
