### ISSUE TITLE
Is Windows Auth Working?

### ISSUE THREAD

**Issue by chazt3n** [IdentityServer/IdentityServer3.Samples#277]
Everything appears to be working, aside from the fact that sometimes I get 60 claims returned and sometimes I get 12... @estiller does this require ADFS or is AD sufficient?

**Comment by estiller** [comment]
Assuming you are referring to the Windows Auth samples, AD is sufficient (or even a workgroup if it a test environment on a single machine). If you have ADFS than it does the Windows Auth part for you, and you integrate it as a WS-Federation IdP.

**Comment by chazt3n** [comment]
@estiller yes thank you, I seem to have gotten the windows auth example working, however I'm a little concerned that sometimes I get many more claims than expected, does this image look like what you expect?:

![image](https://cloud.githubusercontent.com/assets/3843179/15540524/7e2f73e6-224d-11e6-8949-e451839d4a03.png)

**Comment by estiller** [comment]
Yes, it looks alright.

**Comment by chazt3n** [comment]
@estiller Ok, I'm a little nervous because after removing Windows Auth from the _client_ app, I no longer get these claims:

![image](https://cloud.githubusercontent.com/assets/3843179/15541717/6c5a1c92-2253-11e6-8554-25ef5533a9d3.png)


Are you familiar with that could be different here? (there were about 40 more entries outside of that screenshot) I'm just worried that it's creating a new user(/sub?) with my username and not actually talking to my AD

**Comment by chazt3n** [comment]
@estiller 
![image](https://cloud.githubusercontent.com/assets/3843179/15542951/8d41a4fc-2258-11e6-9962-8c4b9c225345.png)

Should there be anything at that /was endpoint? Currently I get a 404

**Comment by chazt3n** [comment]
@estiller  Ok, I see where I'm falling short, I don't know how to get AD groups using this WindowsAuth component, any advice?

**Comment by estiller** [comment]
Hi @chazt3n, you got me a little confused... 

When you say that you removed Windows Auth from the _client_ app, what do you mean? The claims you show us in the second screenshot are claims coming directly from the Winodws Auth layer, without going through the Identity Server transformation in the Windows Authentication Service, so I am not sure what it is exactly that you changed there.

Regarding your question about how to get the AD groups - first, you have to configure the Windows Authentication Service to emit the groups -
```cs
app.UseWindowsAuthenticationService(new WindowsAuthenticationOptions
{
    IdpReplyUrl = "https://localhost:44333/was",
    SigningCertificate = Certificate.Load(),
    EnableOAuth2Endpoint = false,
    EmitGroups = true
});
```
Then in your Identity Server user service when you implement the `AuthenticateExternalAsync()` method you get these groups as role claims on the incoming context.

And as for the other question - it is OK that you get a 404 on the _was_ address. That is not a problem.

**Comment by chazt3n** [comment]
@estiller `EmitGroups = true` O_o Ok well that's awesome. 

> Then in your Identity Server user service when you implement the AuthenticateExternalAsync() method you get these groups as role claims on the incoming context.

I see the claims, however they never make it into the CustomUser's claims, does that mean they'll only be on the access_token? (Is that the entire point of an access token?)

**Comment by estiller** [comment]
Glad to hear you are making progress. The user service and the Custom User class in the sample are just that - a sample... You are correct that the current sample implementation does not propagate the role claims onwards from Identity Server. You can change the implementation or write your own, which takes the role claims from the incoming context and does something with them (like placing them on the outgoing claim collection in the authentication result.

**Comment by estiller** [comment]
BTW, do feel free to create a PR on the sample and modify it to support groups as well.

**Comment by chazt3n** [comment]
My first public PR! I'd love to, let me see if I can feel my way around to get something visible

**Comment by chazt3n** [comment]
Got it! Thank you sir, I'm building this up in a very small sln so I will have to copy my changes into the original repo real fast to create the PR
 
![image](https://cloud.githubusercontent.com/assets/3843179/15583010/60c3aa2e-2339-11e6-8b4d-f6458fbc4c1c.png)
