### ISSUE TITLE
Does IdentityServer3 implement the Resource Owner Password Credential Flow

### ISSUE THREAD

**Issue by cxc256** [IdentityServer/IdentityServer3.Samples#278]
Does IdentityServer3 implement the Resource Owner Password Credential Flow? If so, where would I find the documentation?

**Comment by cxc256** [comment]
I've found https://identityserver.github.io/Documentation/docsv2/endpoints/token.html and the IdentityModel.TokenClient.

Is there anywhere else I should be looking?

**Comment by brockallen** [comment]
I think you found it.
