### ISSUE TITLE
IDserver3 Samples missing the actual server

### ISSUE THREAD

**Issue by nigel-dewar** [IdentityServer/IdentityServer3.Samples#282]
Hi Im am trying to run the client samples. They reference an id server of https://localhost:44333/core.

Where is that?  Its not located in the samples. Also , when I run up my identityserver3 server, /core does not exist, identity does but not core.

**Comment by pianzide1117** [comment]
Hi, You can take a try with SelfHost (Minimal) Project or other HOST Project.

**Comment by brockallen** [comment]
Or the host from the core repo -- all the configs match the clients samples.
