### ISSUE TITLE
base.IsAuthroized is false, but not when debugged locally

### ISSUE THREAD

**Issue by wiseman13** [IdentityServer/IdentityServer3.Samples#283]
I am using the Identity Server Bearer Token implementation. I have a bearer token that was issued using the client grant flow and it works great when the resource server is run locally, but once I push it to my iis servers (i have an arr server for load balancing and two api nodes) I get a 401. This originates on the server when my custom AurthorizationAttribute calls base.IsAuthroized and this returns false because the Identity.IsAuthorzied is false, but as I said when I run the same test locally it works with using the same identity server for both tests.

I have detailed logging enabled for the identity server, but I did not see how you setup logging for Bearer Token implementation to get more insite in what is going wrong on my IIS server.

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = authorityUri,
                RequiredScopes = requiredScopesIEnumerable.ToArray(), 
            }

Thank you for any insights.

**Comment by leastprivilege** [comment]
did you read the docs?

https://identityserver.github.io/Documentation/docsv2/consuming/diagnostics.html

**Comment by wiseman13** [comment]
I did for the identity server, but I missed this section on the middleware debugging. I will see what that gives me.

**Comment by wiseman13** [comment]
I have enabled logging for Microsoft.Owin, but am not seeing any entries in my console output when running locally or in my file output when running on the server. I tried to get logs by using a token missing the required scope locally, but still nothing was generated. Is there another flag that needs to be set for log generation?

**Comment by wiseman13** [comment]
I added other sources like System.Net and confirmed that I am seeing log entries for those, but nothing is coming through for Owin.

<system.diagnostics>
    <sources>
      <source name="System.Net" switchValue="All">
        <listeners>
          <add name="nlog" />
        </listeners>
      </source>
      <source name="System.Net.Sockets" switchValue="All">
        <listeners>
          <add name="nlog" />
        </listeners>
      </source>
      <source name="Microsoft.Owin" switchName="Microsoft.Owin" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="nlog" />
        </listeners>
      </source>
    </sources>
    <sharedListeners>
      <add name="nlog" type="NLog.NLogTraceListener, NLog" />
    </sharedListeners>
  </system.diagnostics>

**Comment by wiseman13** [comment]
As I continue to read and debug I really thing that ARR and SSL off loading is at the heart of my issue, but I am not sure what changes I need to make to get everything working.

I noticed the following headers when debugging in my non dev environment.

X-Original-URL /api/v2/Account/8704/Transaction
X-Forwarded-For 192.168.xx.xx:xxx
X-ARR-SSL
X-ARR-LOG-ID

**Comment by wiseman13** [comment]
More digging and if I remove ARR I still get an error. While monitoring IIS logs I noticed that it does not appear that the resource server is ever making the call out to /identity/connect/accesstokenvalidation, but I do see that call logged when I run the resource server locally.

401: Unauthorized: {"Message":"Authorization has been denied for this request."}

**Comment by wiseman13** [comment]
In searching the source code I am not seeing any type of trace logging for the IdentityServerBearerTokenAuthentication that would help me debug why the call is not even being attempted. The only logging I see and I get down into the plumbing is for error cases.

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/blob/414b217ccb613b231dedcd09d08a90f774fd232a/source/AccessTokenValidation/IdentityServerBearerTokenValidationMiddleware.cs

**Comment by leastprivilege** [comment]
are you using JWTs or reference tokens?

Can you access the needed endpoints from the resource server?

**Comment by wiseman13** [comment]
I am using JWTs. I can access the needed endpoints from the resource server. I check out all of the documentation and have ensure that machine keys are in sync. At this point I am stumped as to why it works local, but not in our farm. I have even tried removing a node from the farm, but leaving arr. As far as I can see from logs on the node and the arr server the resource server is never calling the accesstokenvalidation, but I see no logging on the resource server side that would let me know that it even getting to this point or to confirm that it properly parsed the discovery document.

**Comment by leastprivilege** [comment]
For JWTs the access token validation endpoint is not used. 

The disco doc is retrieved at API startup and would throw an exception if it fails.

you can inject a middleware after the token validation to inspect the claims - that what I would try.

**Comment by wiseman13** [comment]
I actually have the ValidationMode set to use the end point. I was just about to add introspection when I found that this call was not happening in our server environment.

 // enable token-bearer authentication
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = authorityUri,
                RequiredScopes = requiredScopesIEnumerable.ToArray(),  // Can be null
                DelayLoadMetadata = true,
                EnableValidationResultCache = false,
                ValidationMode = ValidationMode.ValidationEndpoint,
            });

**Comment by leastprivilege** [comment]
JWT and validation endpoint does not make sense. Set it to local.

**Comment by wiseman13** [comment]
When I do local I still get a 401 when running on the server. I am looking at adding a middle ware, but where should I be trying to pull the claims list from in that call?

**Comment by leastprivilege** [comment]
set it to local and check the logs again.

**Comment by wiseman13** [comment]
I set to local and ran again, but nothing came in the logs. I then waited for my token to expire and tried to ensure that my logged worked and I get the following, so I think that if there was a log entry I would see it.

Exception thrown: 'System.IdentityModel.Tokens.SecurityTokenExpiredException' in System.IdentityModel.Tokens.Jwt.dll
Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware::Authentication failed
System.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired.

**Comment by leastprivilege** [comment]
so then token validation succeeded before.

Do you have SuppressDefaultHostAuthentication somewhere in your web api config?

**Comment by leastprivilege** [comment]
add a middleware after the access token one that checks the ClaimsPrincipal on the OWIN context

**Comment by wiseman13** [comment]
Okay I will work on the middleware check and ensuring I am getting complete logs on my server. Thank for the help.

**Comment by wiseman13** [comment]
Well I figured out that while my logging works locally the same config on the server produces no logs for the Microsoft.Owin errors. Do you see anything I am missing in this config? I have an error level diagnostic trace written out for Sync.Auth and it works locally and on the server.

<system.diagnostics>
    <trace autoflush="true"/>
    <sources>
      <source name="Microsoft.Owin" switchValue="All">
        <listeners>
          <add name="nlog"/>
          <add name="file" 
               type="System.Diagnostics.TextWriterTraceListener" 
               initializeData="\\server\logs\owin.log" />
        </listeners>
      </source>
      <source name="System.IdentityModel" switchValue="All">
        <listeners>
          <add name="nlog"/>
        </listeners>
      </source>
      <source name="Sync.Auth" switchValue="All">
        <listeners>
          <add name="file" 
               type="System.Diagnostics.TextWriterTraceListener" 
               initializeData="\\server\logs\owin.log" />
        </listeners>
      </source>
    </sources>
    <switches>
      <add name="Microsoft.Owin" value="Verbose"/>
       <add name="Sync.Auth" value="Verbose"/>
    </switches>
  </system.diagnostics>

**Comment by wiseman13** [comment]
Would the Microsoft.Owin source show me any errors related to the resource server loading the discovery document? I was not seeing any trace entries while surfing the code.

**Comment by leastprivilege** [comment]
if loading the disco doc would fail - you would actually get an exception at start time

**Comment by wiseman13** [comment]
Well now I feel bad wasting your time. Turns out it worked locally when hosted via IIS Express, but the reference for Microsfot.Owin.Host.SystemWeb was missing so the Startup was not being found when hosted in IIS, but the WebAPI routes were registered giving me the impression of it working, but not. Thank you again for taking the time to help me trouble shoot.
