### ISSUE TITLE
Validating Tokens

### ISSUE THREAD

**Issue by Sudkart** [IdentityServer/IdentityServer3.Samples#286]
Hi all,

This might be a dumb question for you who all mastered with thinktecture.. :) 

I am very new to the SSO. I have gone through the basic videos of thinktecture IdentityServer3 and I have downloaded the IdentityManager where in i am able to create users and using javasciprt implicit client i am able to login and am getting the id_token.

So my question is how can i validate the Id_token to know that the token is valid and if i click logout and then check if the token is still valid or not.

Thanks in advance for your support.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
