### ISSUE TITLE
AuthorizationManager does not get call when use in a ApiController

### ISSUE THREAD

**Issue by wishstar99** [IdentityServer/IdentityServer3.Samples#287]
Hi guys,
I followed the "Getting Started: MVC Authentication & Web APIs" and it works. I implemented a similar in my project and it works very well. I set ResourceAuthorize attribute on each of my endpoints and the AuthorizationManager is able to pick up. This is when my controller inherits System.Web.Mvc.Controller. When I inherits System.Web.Http.ApiController, the AuthorizeManager does not get call at all. Every call ignores the ResourceAuthorize. 

Does anyone know a solution for this? Thank you.

**Comment by nkdev89** [comment]
im facing the same issue . Please let me know if you were able to fix this

**Comment by wishstar99** [comment]
i ended up using Mvc.Controller instead

**Comment by pianzide1117** [comment]
There is another namespace  for webapi
https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/source/Owin.ResourceAuthorization.WebApi
