### ISSUE TITLE
Modifying AspNetUsers Table

### ISSUE THREAD

**Issue by Sudkart** [IdentityServer/IdentityServer3.Samples#288]
HI,

I am able to create the database using IdentityManger and succesfully creating users and am able to logging with those users in the thinktecture and validate them now i want to add a extra column into the database and get the value along with the user and send that column details via claims.

How can I Modify AspNetUsers Table and add few more columns into the table.

Thanks in Advance.

**Comment by pianzide1117** [comment]
wrong repo
