### ISSUE TITLE
Claims

### ISSUE THREAD

**Issue by Sudkart** [IdentityServer/IdentityServer3.Samples#289]
Hi,

When i am using the profile in the scope am unable to get the firstname and lastname in the claims.
How to get or return the firstname and lastname of the user in claims.

Thanks

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
