### ISSUE TITLE
The best way to handle situation with no centralized role claims?

### ISSUE THREAD

**Issue by ThisNoName** [IdentityServer/IdentityServer3.Samples#290]
Where I am, everyone wants the convenience of SSO, but no way in hell anyone agree on anything else otherwise.  So SSO only gets you identity and a few piece of information, and each application is going to maintain their own user/role/authorization.  Of course, you can't demand too much changes when implementing the solution, all that IsInRole and web.config stuff has to work.  

Now imagine you tab through 5-6 applications in the same browser session, how do you keep track of application specific information and user roles?

I first tried adding custom claims after authentication.  But claims start leaking when you tab through other applications.  Also subsequent apps don't go through logon process.

Then I tried AuthorizationFilterAttribute and only override IsInRole in ClaimPrincipal.  That works for MVC, but didn't know what to do with WebForm config roles.

Finally I stumbled upon and created a Owin middleware.  So basically for every request, I wipe out role claims from others and add back in those from current the current app.  It works but sounds hack-ish, does it?

I know it's a non-standard situation.  Any hints on what the best approaches are?  Thanks.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
