### ISSUE TITLE
Enable Logging

### ISSUE THREAD

**Issue by Sudkart** [IdentityServer/IdentityServer3.Samples#291]
Hi,

Where will the logs get saved i am running the application locally.

 Where i need to give the path explictily in the web.config.

I have gone through your links

https://identityserver.github.io/Documentation/docs/configuration/logging.html

 but still that doesnt say where to give the path for logging.

Thanks,

**Comment by leastprivilege** [comment]
If you don't specify anything special in `initializeData` - it will use the current directory (trace.log). Make sure the process has write access.
