### ISSUE TITLE
Examples where IdentityServer is hosted on same server as API

### ISSUE THREAD

**Issue by human3820917** [IdentityServer/IdentityServer3.Samples#295]
I have an ASP.NET Web API that I would like to secure using IdentityServer3. The examples I have seen show IdentityServer3 as a separate server (different IP/Port combination than the API). Is it possible to include IdentityServer as part of the API project such that any Javascript web application could first authenticate with IdentityServer3 and then receive a bearer token that could then be passed via the header when attempting to access an API endpoint? If this is possible might you have a tutorial or sample code that covers this use case? Thank you for making IdentiyServer3 available.

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
