### ISSUE TITLE
RequiredScopesMiddleware not handling !context.User.Identity.IsAuthenticated

### ISSUE THREAD

**Issue by SamerX** [IdentityServer/IdentityServer3.Samples#296]
While using ASP.NET Core for my API, I noticed that the **RequiredScopesMiddleware** in the **Invoke** method that its not handling the case when the user is not Authenticated, currently it looks like this:
`
public async Task Invoke(HttpContext context)
        {
            if (context.User.Identity.IsAuthenticated)
            {
                if (!ScopePresent(context.User))
                {
                    context.Response.OnCompleted(Send403, context);
                    return;
                }
            }
            await _next(context);
        }
`

While it should be like this:
`
if (!context.User.Identity.IsAuthenticated || !ScopePresent(context.User))
            {
                context.Response.OnCompleted(Send403, context);
                return;
            }
            await _next(context);
`

The current sample code is not handling `context.User.Identity.IsAuthenticated` and therefore it moves to the next middleware execution.

**Comment by leastprivilege** [comment]
dupe
