### ISSUE TITLE
Do you have a link to the source code for the JS and IdentityServer 3 tutorial

### ISSUE THREAD

**Issue by human3820917** [IdentityServer/IdentityServer3.Samples#298]
You have a tutorial located here ..

https://identityserver.github.io/Documentation/docsv2/overview/jsGettingStarted.html

that covers using IdentiyServer3 with Javascript. Do you have a link to the source code?

**Comment by human3820917** [comment]
In tutorial (link above) you mention that all that is needed to show the users's email it to add email to the scope..

public static class Scopes
{
    public static List<Scope> Get()
    {
        return new List<Scope>
        {
            StandardScopes.OpenId,
            StandardScopes.Profile,
            // New scope
            StandardScopes.Email
        };
    }
}

However, even after doing so the email does not show in the Token contents.

**Comment by WhiteFox0** [comment]
I have it here, recently finished. few details can be a bit different, but it should be working - https://github.com/WhiteFox0/IdentityServer3.Samples/tree/master/source/JsApp

**Comment by human3820917** [comment]
Thanks a bunch!
