### ISSUE TITLE
Javascript Implicit Client - Error using 'Call API' button

### ISSUE THREAD

**Issue by nickgibson-advanced** [IdentityServer/IdentityServer3.Samples#299]
Hi, I'm trying to get the javascript implicit client example working. 

I've tried to run the 'javascript client manual' project straight 'out of the box' and can log in and validate the token fine. But clicking the call API button responds with '`Network Error`' and in the F-12 dev tools window:

`XMLHttpRequest cannot load http://localhost:2727/identity. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:37046' is therefore not allowed access. The response had HTTP status code 500.`

I'm using chrome (51).

I've changed nothing from the source code provided - any advice on getting the example working would be gratefully received.

**Comment by brockallen** [comment]
Looks like CORS is not enabled on the web api. Either we forgot it, or you changed the port of the client.

**Comment by nickgibson-advanced** [comment]
I think the port number was changed. My bad! All working now. Thanks for the quick response.
