### ISSUE TITLE
IdentityServer3.Samples - AspNet5

### ISSUE THREAD

**Issue by samsopheak** [IdentityServer/IdentityServer3.Samples#300]
Hi Guys,

I've been trying to follow the sample code (https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/AspNet5) using the the RTM version of MVC6.

So far I have no luck, so the mvc app can authenticate but for whatever reason it does not have or receive claims - "access_token".

Has anybody experienced similar issue?

Thanks,
Sam

**Comment by leastprivilege** [comment]
the sample has not been updated - you probably rather wanna have a look at idsrv4 for asp.net core.
