### ISSUE TITLE
connect think tecture identity server to dynamics crm

### ISSUE THREAD

**Issue by payamiii** [IdentityServer/IdentityServer3.Samples#301]
Hi. I have microsoft Dynamics CRM 2016 (On-Pemise) on my server. i enabled ifd on this CRM with adfs. how can i connect identity server to adfs for authentication in crm.

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
