### ISSUE TITLE
I am getting clientId as null always from LocalAuthenticationContext 

### ISSUE THREAD

**Issue by naveenkumarreddy** [IdentityServer/IdentityServer3.Samples#302]
I am trying to get the clientId at the time of login but I am always getting it null. do i need to pass the clientId any where so the I get it from context.SignInMessage .

public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
        {
            try
            {
                var test = context.SignInMessage.ClientId;
                using (var pc = new PrincipalContext(ContextType.Domain, "wordandbrown.com"))
                {
                    if (pc.ValidateCredentials(context.UserName, context.Password))
                    {
                        using (var user = UserPrincipal.FindByIdentity(pc, IdentityType.SamAccountName, context.UserName))
                        {
                            if (user != null)
                            {
                                var nameClaim = new List<Claim> {new Claim(Constants.ClaimTypes.Name, context.UserName)};
                                //var test  = Task.FromResult(new AuthenticateResult(subject: Guid.NewGuid().ToString(), name: context.UserName, claims:nameClaim));
                                //return test;
                                context.AuthenticateResult = new AuthenticateResult(Guid.NewGuid().ToString(),context.UserName,nameClaim);
                                return Task.FromResult(0);
                            }
                        }
                    }

                    // The user name or password is incorrect
                    return Task.FromResult<AuthenticateResult>(null);
                }

            }
            catch
            {
                // Server error
                return Task.FromResult<AuthenticateResult>(null);
            }
        }

**Comment by brockallen** [comment]
Where are you triggering login from? If it's not from a OIDC client (e.g.e the permissions page), then it's possible that it's null.

**Comment by naveenkumarreddy** [comment]
actually I am having two JS projects with implicit client flow and I am using Windows Authentication with two AD groups. here I want the Client Id at the time login so that I can get the AD path according to the client Id

**Comment by brockallen** [comment]
Client id should be passed if you are properly triggering an authorization request from an OIDC/OAuth2 client.

**Comment by naveenkumarreddy** [comment]
I am not using OIDC client , I just configured WS-Federation for Windows Authentication

**Comment by brockallen** [comment]
Ah, ok. Then that might not be something we support. Check the WS_Fed repo issue tracker and see if there's an open issue. If not, create one.

**Comment by naveenkumarreddy** [comment]
thanks brokallen, I'll check if there is an open issue on this if not I'll create new issue.
