### ISSUE TITLE
Why PKCE with clientSecret?

### ISSUE THREAD

**Issue by raphaellondner-okta** [IdentityServer/IdentityServer3.Samples#304]
I thought the whole point of Proof Key for Code Exchange (PKCE) was to avoid making a native client aware of the client secret (as mentioned at http://openid.net/2015/05/26/enhancing-oauth-security-for-mobile-applications-with-pkse )

However, the TokenClient class used in the WPF with PKCE code sample (https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/WpfOidcClient/LoginWebView.xaml.cs) still uses the clientSecret and I verified that it doesn't work if I specify the TokenClient constructor without the clientSecret parameter. Is there anything else that should be done in the IdentityModel library to take care of the secret-less scenario?

**Comment by brockallen** [comment]
IdSvr3 requires client secret, even if it's not a secret for public clients. We try to make it well known (like google does).

As for secret-less, PKCE is all about having a secret, albeit dynamically created. Perhaps you're aware of that, and that's not what you mean.

**Comment by raphaellondner-okta** [comment]
Brock, thank you for your swift feedback, I appreciate it.

I am aware that PKCE does imply having a dynamic secret. However, the way IdentityModel seems to be implemented, you still need to pass the static client secret as part as your token request, which seems to defeat the very purpose of PKCE. Note the following pre-condition from RFC 7336 (https://tools.ietf.org/html/rfc7636#page-4) for an authorization code interception attack to be potentially happening:

"The attacker has access to the OAuth 2.0 [RFC6749] "client_id" and "client_secret" (if provisioned).  All OAuth 2.0 native app client-instances use the same "client_id".  **Secrets provisioned in client binary applications cannot be considered confidential**"

It seemed to me that you designed IdentityModel and IdentityModel.OidcClient as generic .NET libraries that could be used with any OIDC/OAuth product that implements the OIDC/OAuth RFCs (in the same way Google's AppAuth was designed) but maybe they were meant them to be used mainly with IdSrv3? If we do manage to make them work with a secret-less implementation (that does not break integration with IdSrv3, of course), will you accept pull requests of such changes?

**Comment by leastprivilege** [comment]
PKCE and client secret are unrelated.

Here's the issue to eliminate the need for the secret in the client lib

https://github.com/IdentityModel/IdentityModel.OidcClient/issues/25
