### ISSUE TITLE
Importing Certificate File Type not Recognized

### ISSUE THREAD

**Issue by rswetnam** [IdentityServer/IdentityServer3.Samples#306]
Hi:

I'm trying to import a sample certificate on my local machine as described in https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Certificates.  When I have found the pfx file and clicked next, I get an error that the file type is not recognizable.  I am doing this on a Windows 10 machine:  Following is a screen shot:

![image](https://cloud.githubusercontent.com/assets/2905367/17940763/64a1aa18-69e5-11e6-84f9-feb183d5e4e5.png)

**Comment by brockallen** [comment]
Not sure what the problem is, but you can always make your own certs: https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/
