### ISSUE TITLE
Non-webpacked JS client?

### ISSUE THREAD

**Issue by dannycallaghan** [IdentityServer/IdentityServer3.Samples#309]
Apologies if I'm just looking in the wrong place, but is it possible to get a non-webpacked version of the JS client?

If I'm being stoopid, please point me in the right direction.

Thanks!

**Comment by brockallen** [comment]
What's the issue?

**Comment by dannycallaghan** [comment]
Apologies, was I not clear?

We use this version in production:

https://github.com/IdentityModel/oidc-token-manager/blob/master/oidc-token-manager.js

I was informed that this was updated, so came here to see the sample of the new JS client, to look at upgraded the version we're using. Was hoping to find the plain old JavaScript, but it's a 1.8MB webpack bundle. I was just wondering if there is a non-webpacked sample I can look at here, or a pointer if I'm looking in the wrong place.

Thanks!

**Comment by brockallen** [comment]
The new library is here: https://github.com/IdentityModel/oidc-client-js. If you're using your own module loader, then you use what's from ~/lib. If you're not then you use the self-contained file (polyfills & all) from ~/dist.

**Comment by dannycallaghan** [comment]
Great, thanks, and thanks for the quick response.
