### ISSUE TITLE
LogoUri is null always if customize view service

### ISSUE THREAD

**Issue by Sonic3R** [IdentityServer/IdentityServer3.Samples#310]
Hi,

I tried to follow to customize IViewService, I set up for a client a logo (by set up `LogoUri` property) uri but in UI, if I do:

```
<div class="col-xs-12">
       <img src="@Model.ClientLogoUrl" alt="logo" class="img img-responsive" />
</div>
```

Seems that `Model.ClientLogoUrl` is null. Why ?

**Comment by brockallen** [comment]
This is a property from the client configuration.
