### ISSUE TITLE
How to use it in WPF without WebBrowser cotnrol (aka IE)

### ISSUE THREAD

**Issue by Spamme1** [IdentityServer/IdentityServer3.Samples#311]
All the examples with WPF are made with the WebBrowser control, is this the only way to use IS3 with WPF? Is there no way to use plain C# code without the burden of IE? I feel like I have to use a Ilyushin Il-62 to just go around the corner to buy the newspaper, I mean it is a very short trip, I can walk or use something very very light like a nice bicycle. I feel really uncomfortable have to use one of the worst if not the worst component made for WPF, aka the WebBrowser, at the end I have to send the user and password and get the token back, is that a so big deal that it can't be done without IE? But let say that I want to have a console application, no UI, no WebBrowser, how can I use IS3 with a simple and nice console application? In there an example?

**Comment by leastprivilege** [comment]
Not the only - but the recommended.

https://tools.ietf.org/html/draft-ietf-oauth-native-apps-03

**Comment by Spamme1** [comment]
Thanks for the reply, but I don't understand how you can "recommend" something that also MS has decided to drop, that everybody hates and that its future is already doomed! You talk about "modern web applications", OpenID Connect and OAuth2, and then you recommend to use IE, the worst ever made web browser in the history of internet, the web browser that was destroying the web, the web browser that wanted to dictated its standards. Recommending IE is not something that a open source community that support the open standards will do. Please tell me that this is a joke, because I can't believe that you really stay behind IE, it would be a very delusion!

**Comment by leastprivilege** [comment]
You haven't read the spec - I am not saying to use IE - I am saying "use the system browser".

**Comment by Spamme1** [comment]
There is no solution without a web browser? Console Applications on head less server can't authenticate without have to use an external application, which is 10 times bigger than themselves?

**Comment by leastprivilege** [comment]
Head less servers don't have interactive users. They use client credential flow.

You can use resource owner flow - with the known limitations.

**Comment by Spamme1** [comment]
I will check it, thanks
