### ISSUE TITLE
Angular 2 and OIDC module

### ISSUE THREAD

**Issue by figuerres** [IdentityServer/IdentityServer3.Samples#312]
I am working on learning Angular 2  and Typescript.
I have not found any complete module / component for Ang 2 and wo ndered if anyone knew of one ?
I am also away for the A2 OIDC starter that is out ther ebut it does not auto configure the client code using the metadata and I think that is a nice thing to use if I can figure out how to make it work.

any info is welcome on other folks trying to cover the same ground.

**Comment by brockallen** [comment]
https://github.com/IdentityModel/oidc-client

**Comment by CodeRevver** [comment]
I'm a bit late to the party here but I'm in the same position as you, I want to use ID server v3 with WebAPI 2 and an Angular2 client.  What I've got is extremely ROUGH but It shows how you can use ID Server v3 with and Angular 2 client.  It's not fully Angular (I'm using implicit flow and redirecting to the ID Server login page at the moment) but it might get you started.  

You can see it here:  https://github.com/CodeRevver/Magnanimous

If you're interested it's also hooked up to a WebApi2 client and I'm planning on passing the token to that in the future.  Also It's using Telerik Angular 2 controls so you might need a free account to download the packages...
