### ISSUE TITLE
Membershipreboot not getting latest claims

### ISSUE THREAD

**Issue by FullyCSharped** [IdentityServer/IdentityServer3.Samples#315]
@brockallen ,

I am writing a custom API , which is for returning UserClaims information for a given account and have a problem that its not getting the latest claims, I mean if i delete a claim or add a claim the output of the CustomuserRepository still remains the same.

CustomuserRepository is a class inherits DbContextUserAccountRepository class, I am actually using one of the samples from github [https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MembershipReboot](url) 

and I am using this method from CustomUserRepository `_customUserRepository.GetByUsername(username);`

**Comment by brockallen** [comment]
Sounds like you are accidentally using a singleton to get your data from MR/database?

**Comment by FullyCSharped** [comment]
Maybe, I was getting the latest list of claims after an IISReset I tried using AutoFac for DI and have registered like below 

`  var config = new HttpConfiguration();
                config.MapHttpAttributeRoutes();
                var builder = new ContainerBuilder();
                builder.RegisterType<CustomUserRepository>().As<IUserAccountRepository<CustomUser>>()
                    .WithParameter("ctx", new CustomDatabase(Constants.CONNECTION_STRING));`

Is singleton the default lifestyle behavior with Autofac?

**Comment by brockallen** [comment]
That looks right, AFAICT.

So in short, I don't know. You'll have to debug thru it.

**Comment by FullyCSharped** [comment]
@brockallen , I tried different ways of registration with the above piece of code, i.e InstancePerRequest() but dont see any changes reflected yet

**Comment by brockallen** [comment]
I'll close since this issue didn't get very far. If you need to reopen.
