### ISSUE TITLE
How to support ResourceOwner Flow with silent renew token

### ISSUE THREAD

**Issue by guerson** [IdentityServer/IdentityServer3.Samples#316]
In order to access resources of my application, i firstly obtained an access token to eventually use an option to refresh the token with /core/connect/.
But, the ResourceOwner flow example only shows how to get and revoke a token.

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptResourceOwner

I am not sure how to make the Silent Renew request in this case.

**Comment by brockallen** [comment]
Silent renew, meaning from a JS client app? Silent review only works if you use the authorize endpoint to log the user in initially.

**Comment by guerson** [comment]
Yeah, my app is a Single Page Application in JS with is own login page
