### ISSUE TITLE
Generating SSL

### ISSUE THREAD

**Issue by cajunitalian** [IdentityServer/IdentityServer3.Samples#323]
I see a lot of documentation on Test Certs but what's the process for doing a SHA 256 cert generating from an internal CA?

**Comment by leastprivilege** [comment]
Ask your internal CA?

**Comment by cajunitalian** [comment]
Dominick,


Not sure what you're getting at, I am the sysadmin for the Web FArm.  I am asking you what kind of certificate do I need to generate for IdentityServer3.  All I could find on your site is that it's a "Signing Cert" which doesn't really say much.


When you do a cert request in AD,there are many, many options.  I am just after requirements.


EX:

[cid:b3f25eeb-2557-42c7-aa84-9576785029b3]
________________________________
Matthew Dartez, M.S.I.T. | M.S.S.E.
Systems Engineer
matteo@forzadartez.com

________________________________

**Comment by leastprivilege** [comment]
You need one that is capable of signing data for token signatures - or a normal SSL/TLS cert for HTTPS. No special requirements, e.g.:

https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/
https://identityserver.github.io/Documentation/docsv2/configuration/crypto.html
