### ISSUE TITLE
Custom login sample doesn't work

### ISSUE THREAD

**Issue by TDK1964** [IdentityServer/IdentityServer3.Samples#324]
IdentityServer3.Samples/source/CustomLoginPage/

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /

**Comment by brockallen** [comment]
Does it work if you browser to ~/core?

**Comment by TDK1964** [comment]
Yes /core works = Welcome to IdentityServer3

**Comment by TDK1964** [comment]
I think we're not aligned, when I said it worked I was referring to the fact the default IS3 welcome page is displayed and not the custom login page.

**Comment by brockallen** [comment]
You said that you did not see any sign of IdentityServer working when visiting the root of the web server. All of our samples are configured to run at ~/core (this is discoverable by looking in Startup), so I was trying to show you that it is running. 

As for your custom login pages, thin about when that's shown with IdentityServer... a login page is only needed in the context of trying to signin to a client application.
