### ISSUE TITLE
Using oidc with sub application (site)

### ISSUE THREAD

**Issue by anthonyjoanes** [IdentityServer/IdentityServer3.Samples#331]
I have a website setup in IIS that is happily using oidc framework. I have now set up a sub application under this main website and I want the same session information to persist and the silent refresh of tokens to work.

Currently I have an issue where I cannot get the user and I believe this is something to do with the check session IFrame not existing once I navigate to a page in the sub application. I can see all the data in local storage but I'm not sure how to hook this sub app up?

**Comment by brockallen** [comment]
Sorry -- totally missed this question/issue. I'm assuming the apps are MVC/cookie based for authentication? You'd need to share the cookies and have both apps validate the same cookie. It can be done, but this is more of a question for Microsoft.
