### ISSUE TITLE
Secondary login of different user

### ISSUE THREAD

**Issue by enablor** [IdentityServer/IdentityServer3.Samples#332]
We're using IdentityServer3 successfully today for authentication/SSO in our suite of applications.  We have a new use case requirement for which I'm inquiring here.  

While a user is already logged in, we need the ability to log in a secondary user to perform a specific action in the application.  Think of it as the primary user hands a tablet to the secondary user to approve a certain activity which primary user is performing in the application.  

Is this a non-starter?  How would I go about this?  I cannot find a single example or mention of this in the documentation or anywhere else.

**Comment by brockallen** [comment]
We've done this before for other customers, but requires some internal knowledge of how to get IdSvr to "do the right thing" for these workflows. Since this issue fell thru the cracks, I imagine you have moved on. I'll close. Sorry for delay.
