### ISSUE TITLE
Web forms example issues

### ISSUE THREAD

**Issue by AshleyTaylor120986** [IdentityServer/IdentityServer3.Samples#334]
I've tried using the Web Forms example to apply to my project, but instead of getting a redirect I'm just getting the Windows Security dialogue appearing

Web.config and Startup.cs attached.

I've tried with and without the authorization node at the system.web level (outside the location node) with no difference.  

Any suggestions on what needs changing please?

[identityserver_web_config.txt](https://github.com/IdentityServer/IdentityServer3.Samples/files/827476/identityserver_web_config.txt)

[Startup.txt](https://github.com/IdentityServer/IdentityServer3.Samples/files/827483/Startup.txt)

**Comment by brockallen** [comment]
> Windows Security dialogue appearing

Do you only have Windows auth enabled? You need to enable anonymous.

**Comment by AshleyTaylor120986** [comment]
I have the option for "Anonymous Authentication" set to True at the project level in Visual Studio, and have it configured in the applicationHost.config as well, does it need to be somewhere else?

**Comment by brockallen** [comment]
Somewhere in your app something is triggering a challenge.

**Comment by AshleyTaylor120986** [comment]
In case anyone else struggles with this, in my case it was this:
<customErrors mode="On" defaultRedirect="Error.aspx" redirectMode="ResponseRewrite" />
