### ISSUE TITLE
Managing session timeout page and logout page

### ISSUE THREAD

**Issue by niaz-a-ak** [IdentityServer/IdentityServer3.Samples#335]
Hi Team,

In our application we have session timeout page and logout page. So once session time out happens we need to logout identity server and redirect to session timeout page. But in log out time we need to redirect to our application login page. So how to handle this in identity server since there is only post_logout_redirect_uri

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
