### ISSUE TITLE
Deploying Windows Auth All-in-One to Dev Server

### ISSUE THREAD

**Issue by mfmaher** [IdentityServer/IdentityServer3.Samples#336]
I have been successful with getting my solution to run locally but when I deploy to a dev server I can run and render fine but my colleagues are unsuccessful. 
They continue to receive the below message:
There was an unexpected error
Request Id: 4e399a8e-3246-47f6-ab87-68da134e9d7c 
I have been trying to troubleshoot this for awhile now and I'm looking for some guidance. 
Things to note. I have used the Windows Auth All-in-One identity server sample along with the client app - JavaScript OAuth only for testing. So I deployed both for testing. Again they work great locally and the gettoken function works for me but not for other users hitting that page.

Thanks in advance.
Mike

**Comment by brockallen** [comment]
Check the logs. Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
