### ISSUE TITLE
Javascript implicit flow - updating jsrsasign

### ISSUE THREAD

**Issue by sattaman** [IdentityServer/IdentityServer3.Samples#337]
I have been trying to get an Implict JavaScript client working using the latest `jsrsasign` but have been having issues updating the call. 

`if (jws.verifyJWSByPemX509Cert(id_token, cert)) {
`
as far as I can tell this needs to change to

`if (KJUR.jws.JWS.verify(id_token, cert)) {`
http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.verify

I am hitting the following error though

```
// 3.3. check whether key is 
RSAKey obj if alg is RS* or PS*.
    if (algType == "RS" || algType == "PS") {
    if (!(key instanceof RSAKey)) {
        throw "key shall be a RSAKey obj for RS* and PS* algs";
    }
} 
```

I have created a question on [SO here.](http://stackoverflow.com/questions/43189577/when-using-identity-server-login-do-i-need-to-validate-implicit-flow-token) I can delete either this issue or the SO question if the crosspost is an issue.

**Comment by brockallen** [comment]
are you using the oidc-client library?

**Comment by sattaman** [comment]
I am in another project , but this particular one is a react native mobile app so I am under the impression I need to use the implement in js directly?

**Comment by brockallen** [comment]
@maxmantz has a react library on oidc-client

**Comment by brockallen** [comment]
Also, IdSvr4 doesn't expose a x5c if you don't use a x509 cert. see how oidc-client handles this.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
