### ISSUE TITLE
ASP.NET Identity SubjectID

### ISSUE THREAD

**Issue by zoltanFlavius** [IdentityServer/IdentityServer3.Samples#339]
Hello,

In our app we use ASP,NET Identity. Is it possible to map the subjectID to another value than the default user ID? How can we do that?
Thank you!

**Comment by brockallen** [comment]
Issue a "sub" claim at login time, and in the profile service look up your use by "sub". This will require digging a bit more into the IdentityServer model beyond what the ASP.NET Identity helpers provided for IdentityServer abstract you from.

**Comment by zoltanFlavius** [comment]
Hello,

Thank you for your response.
I have tried to modify the default behavior by implementing the GetClaimsFromAccount  method and set my own subject ID. 
In the client, when I get the claims from the token I end up with 2 "sub" claims. One is the default sub (the user ID) and the other one is the subject I have set in GetClaimsFromAccount  method. Is this the desired behavior?

Thank you

**Comment by brockallen** [comment]
Override this: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/UserClaimsFactory.cs#L24

and remove the claim from the collection for the PK that the base class adds.
