### ISSUE TITLE
[Question] Single sign out doesn't seem to work

### ISSUE THREAD

**Issue by solnt** [IdentityServer/IdentityServer3.Samples#342]
Hello, 

I followed this link: 
[https://brockallen.com/2016/02/08/single-sign-out-and-identityserver3/](https://brockallen.com/2016/02/08/single-sign-out-and-identityserver3/)
and 
[https://identityserver.github.io/Documentation/docsv2/advanced/signout.html](https://identityserver.github.io/Documentation/docsv2/advanced/signout.html)
and using the samples for my testing.
Server: [https://github.com/IdentityServer/IdentityServer3](https://github.com/IdentityServer/IdentityServer3)
Client: [https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MVC%20OWIN%20Client](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MVC%20OWIN%20Client)

0. Start the Identity Server with port 44333 (https)
1. Opening the client in two different browsers: one in Chrome, another in Edge (https)
2. Both is logged in with username: alice (get from identity server)
3. Logged out from Chrome 
4. Refresh the page in Edge -> alice is still logged in

I think the client in Edge browser have to be logged out as well as it is expected with the single sign out.
I don't now if I misunderstood or not. 
Please help to point out

Thank you.

**Comment by mackie1001** [comment]
At the end of the day the session is still denoted by a cookie so any sign out will only affect the browser it occurred in. Of course you could implement some kind of server-side session storage which has the ability to control all sessions for a given user but that would have to be something you built yourself I think.

**Comment by brockallen** [comment]
> At the end of the day the session is still denoted by a cookie so any sign out will only affect the browser it occurred in

What @mackie1001 says.
