### ISSUE TITLE
Single Sign Out issue in Identity Server 3

### ISSUE THREAD

**Issue by IncRev-Bala** [IdentityServer/IdentityServer3.Samples#350]
@brockallen I'm using JavaScript application in the Client Side and I'm using **Identity Server 3** as an Auth Service. In Client Side I used the OIDC-Client to achieve the Single Sign On and Single Sign Out. I'm having issue in Single Sign Out. I opened a same application in two tabs, If I logged out in one application, the next tab is still alive in the session.

I think the IFRAME is not updating from the check session endpoint, After that, I downloaded a sample JavaScript application from github and I tried the same, there also I faced the same issue. Kindly assist me.

Finally I concluded the issue is in Identity Server Token Service not in Client application. What are all the preliminary checks I need to check in an Identity Server Auth Service regarding Single Sign Out (Check Session Endpoint) ?

**Comment by IncRev-Bala** [comment]
If I commented the following Custom View Service in Startup Factory configuration, Single Sign Out is working fine.

`
factory.ViewService = new IdentityServer3.Core.Configuration.Registration<IViewService,CustomViewService>();`

Kindly assist me whats the actual issue and what need to do to fix this issue. If I use the above said Custom View Service, its failing to logout (automatic logout is not happening) in other tabs (Check Session Endpoint is not updating the log out state) and I press the F5 or refresh then its redirecting to login.

**Comment by brockallen** [comment]
This repository is no longer in active development or maintenance, other than reported security vulnerabilities.

If you have questions and are seeking free support, see [here](http://docs.identityserver.io/en/release/intro/support.html#free-support) for more details.

If you require commercial support, see [here](http://docs.identityserver.io/en/release/intro/support.html#commercial-support) for more details.
