### ISSUE TITLE
What Does the CallAPI's Method 'json' var Expect?

### ISSUE THREAD

**Issue by ConstruKction** [IdentityServer/IdentityServer3.Samples#94]
Working through the WebApi tutorial, we have hit a snag at the end when trying to parse Json.

```
private async Task<string> CallApi(string token)
        {
            var client = new HttpClient();
            client.SetBearerToken(token);

            var json = await client.GetStringAsync("https://localhost:44301/identity");
            return JArray.Parse(json).ToString();
        }
```

Everything goes wrong at 

```
return JArray.Parse(json).ToString();
```

because it returns this error:

```
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```

The reason for that is because it's receiving the entire HTML of https://localhost:44301/identity, and then trying to parse it into Json, which obviously is not possible.
However, the code sample below is the same as mine, and according to the tutorial, is supposed to show something like this: https://cloud.githubusercontent.com/assets/1454075/4625853/2ba6d94a-537b-11e4-9ad0-3be144a913f0.png

https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Controllers/CallApiController.cs

What am I doing wrong here? Any hint would be appreciated.
Sorry for the messy title.

**Comment by leastprivilege** [comment]
Well - it might be worth looking at the html that gets returned (or looking at the endpoint using a browser) - I bet it is an error message ;)

**Comment by ConstruKction** [comment]
Sorry for taking a shamefully long time responding to this.

As far as I can see, there's no error message in this garbled HTML code.
You can check the more readable, raw form right here.
https://gist.github.com/ConstruKction/2e2ee0c309facff7f537

```
"<!DOCTYPE html>\r\n<html ng-app=\"app\" ng-controller=\"LayoutCtrl\">\r\n<head>\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n    <title>Thinktecture IdentityServer v3</title>\r\n    <link rel=\"stylesheet\" href=\"https://localhost:44301/identity/assets/styles.min.css\">\r\n</head>\r\n<body lang=\"en\">\r\n    <div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n        <div class=\"navbar-header\">\r\n            <a href=\"https://localhost:44301/identity\">\r\n                <span class=\"navbar-brand\">\r\n                    Thinktecture IdentityServer3\r\n                </span>\r\n            </a>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"welcome-page container\">\r\n        <div class=\"row page-header\">\r\n            <div class=\"col-sm-10\">\r\n                <h1>\r\n                    Welcome to Thinktecture IdentityServer3\r\n                    <small>(build 1.1.1.0)</small>\r\n                </h1>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"row\">\r\n            <div class=\"col-sm-8\">\r\n                <p>\r\n                    IdentityServer publishes a\r\n                    <a href=\"https://localhost:44301/identity/.well-known/openid-configuration\">discovery document</a>\r\n                    where you can find metadata and links to all the endpoints, key material, etc.\r\n                </p>\r\n            </div>\r\n        </div>\r\n        <div class=\"row\">\r\n            <div class=\"col-sm-8\">\r\n                <p>\r\n                    IdentityServer allows users to view and revoke\r\n                    <a href=\"https://localhost:44301/identity/permissions\">application permissions</a>\r\n                    previously granted to client applications.\r\n                </p>\r\n            </div>\r\n        </div>\r\n        <div class=\"row\">\r\n            <div class=\"col-sm-8\">\r\n                <p>\r\n                    Here are links to the \r\n                    <a href=\"https://identityserver.github.io/Documentation\">documentation</a>,\r\n                    and <a href=\"https://github.com/identityserver/Thinktecture.IdentityServer3.Samples\">ready to use samples</a>.\r\n                </p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n"
```

After further inspecting, the output appears to be the HTML of the https://localhost:44301/identity page, which in return, returns the aforementioned exception.

More break point details:

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

```c#
Line 57: 
Line 58:             var json = await client.GetStringAsync("https://localhost:44301/identity");
Line 59:             return JArray.Parse(json).ToString();
Line 60:         }
Line 61: 
```

I put the break point at line 58, the exception marks line 59 red.

**Comment by leastprivilege** [comment]
And you are sure that there is your Web API Controller listening on the URL you are trying to reach? Why would it return HTML?

The HTML looks like it is from IdentityServer - not the API controller (maybe you want to have a look at the sample code)

**Comment by ConstruKction** [comment]
Hey, thank you for the speedy response.

Your suggestion was accurate; some of my URL ports were wrong.

However, after changing the ports to correct ones, I'm receiving a 401 response error.

![image](https://cloud.githubusercontent.com/assets/10813906/6555033/c2cb18a8-c659-11e4-85db-f011fd27d677.png)

So I tried to experiment a little, and disabled SSL, as suggested here: http://stackoverflow.com/a/28685522

But then this happens.

![image](https://cloud.githubusercontent.com/assets/10813906/6555064/0ec6d97c-c65a-11e4-8bee-3bf726af172c.png)

Would you perhaps have any hints on how to proceed further?

**Comment by leastprivilege** [comment]
Never saw that error before, sorry.

**Comment by cptJack22** [comment]
I was having the exact same error messages. I discovered that I had not enabled SSL on the Api project in visual studio, so client.GetStrignAsync was going to the wrong URL to call the API. I hope that helps.
