### ISSUE TITLE
How to use silent_redirect_uri JavaScript Implicit Client

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/IdentityServer3.Samples#99]

**Comment by brockallen** [comment]
Well, this isn't documented/supported yet really, but you can look at the OAuthJS sample.

**Comment by RajMondaz** [comment]
implementation of silent_redirect_uri for  JavaScript Implicit Client and mvc client. can we excpect in the future

**Comment by brockallen** [comment]
Yes, at some point.
